/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings-v2.ts
 * SPELL-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseSpellSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	// SPELL (206 cards)
	if (refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AdvancedTargetingMonocle,
			CardIds.AncientKrakenbane,
			CardIds.AnimatedMoonwell_EDR_254,
			CardIds.ArcaneArtificer,
			CardIds.ArcaneArtificerCore,
			CardIds.ArchmageAntonidas,
			CardIds.ArchmageAntonidasLegacy,
			CardIds.ArchmageAntonidas_CORE_EX1_559,
			CardIds.ArchmageVargoth,
			CardIds.ArkoniteRevelation_GDB_852,
			CardIds.ArrowSmith,
			CardIds.AudioSplitter,
			CardIds.BabaNaga,
			CardIds.BalindaStonehearth,
			CardIds.BarbaricSorceress,
			CardIds.BenevolentBanker_WW_384,
			CardIds.Bioluminescence,
			CardIds.Bloodbloom,
			CardIds.BookOfSpecters,
			CardIds.BrollBearmantle_EDR_853,
			CardIds.BumblingBellhop_VAC_521,
			CardIds.CactusCutter_WW_327,
			CardIds.CardGrader_TOY_054,
			CardIds.CelestialShot_YOG_082,
			CardIds.ChiaDrake_Cultivate_TOY_801a,
			CardIds.ChiaDrake_SeedlingGrowth_TOY_801b,
			CardIds.ClearancePromoter_TOY_390,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_SCH_Active48,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_Toki_T5,
			CardIds.ClockworkAssistant_GILA_907,
			CardIds.ClockworkAssistant_ONY_005ta11,
			CardIds.CoilskarCommander,
			CardIds.Colossus_SC_758,
			CardIds.CommanderSivara_TSC_087,
			CardIds.ConchsCall,
			CardIds.Conductivity_YOG_522,
			CardIds.ConjuredBookkeeper_TLC_226,
			CardIds.ContaminatedLasher_YOG_528,
			CardIds.CoralKeeper,
			CardIds.CosmicKeyboard,
			CardIds.Cosmonaut_GDB_443,
			CardIds.Cultivate,
			CardIds.DarkmoonMagician_MIS_303,
			CardIds.Deathchiller_CORE_RLK_083,
			CardIds.Deathchiller_RLK_083,
			CardIds.DeckOfLunacy,
			CardIds.DeepwaterEvoker,
			CardIds.DevoutPupil,
			CardIds.DiscoveryOfMagic,
			CardIds.DoorOfShadows,
			CardIds.DoorOfShadows_DoorOfShadowsToken,
			CardIds.DoubleTime,
			CardIds.DozingKelpkeeper,
			CardIds.DragonsFury,
			CardIds.DryscaleDeputy_WW_383,
			CardIds.ElementalInspiration,
			CardIds.EnergyShaper,
			CardIds.ExarchHataaru_TheGalaxysLensToken_GDB_136t,
			CardIds.FaeTrickster_EDR_571,
			CardIds.FarseerNobundo_GDB_447,
			CardIds.GlacialAdvance_RLK_512,
			CardIds.GlowflySwarm,
			CardIds.GreenThumbGardener,
			CardIds.GuffRunetotem_BAR_720,
			CardIds.HallazealTheAscended,
			CardIds.HallazealTheAscended_WON_336,
			CardIds.Handmaiden,
			CardIds.HarnessTheElementsTavernBrawl,
			CardIds.HedraTheHeretic_TSC_658,
			CardIds.HighAbbessAlura,
			CardIds.Hullbreaker,
			CardIds.IcebloodTower,
			CardIds.IdolsOfEluneTavernBrawl,
			CardIds.Illuminate,
			CardIds.IncantersFlow,
			CardIds.InquisitiveCreation,
			CardIds.JotunTheEternal,
			CardIds.JungleJammer,
			CardIds.KhadgarsScryingOrb,
			CardIds.Kindle_DALA_911,
			CardIds.Kindle_ULDA_911,
			CardIds.KingTide_VAC_524,
			CardIds.KnightOfAnointment,
			CardIds.KolkarPackRunner,
			CardIds.LadyAnacondra_WC_006,
			CardIds.LadyStheno_TSC_218,
			CardIds.LadyVashj_VashjPrimeToken,
			CardIds.LearnDraconic,
			CardIds.LifebindersGift,
			CardIds.LifebindersGrowth,
			CardIds.Lifeguard_VAC_919,
			CardIds.LinaShopManager_TOY_531,
			CardIds.LockAndLoad_AT_061,
			CardIds.LockAndLoad_CORE_AT_061,
			CardIds.LockAndLoad_WON_023,
			CardIds.LorewalkerChoLegacy,
			CardIds.LorewalkerChoVanilla,
			CardIds.LorewalkerCho_CORE_EX1_100,
			CardIds.LoveEverlasting,
			CardIds.MagathaBaneOfMusic,
			CardIds.MagisterDawngrasp_AV_200,
			CardIds.MagisterUnchainedTavernBrawlToken,
			CardIds.MalygosTheSpellweaverCore,
			CardIds.ManaCyclone,
			CardIds.MantleShaper_DEEP_004,
			CardIds.MaroonedArchmage_VAC_435,
			CardIds.MarshlandThresher_TLC_256,
			CardIds.Marshspawn_BT_115,
			CardIds.Marshspawn_CORE_BT_115,
			CardIds.MeddlesomeServant_YOG_518,
			CardIds.MistahVistah_VAC_519,
			CardIds.Multicaster,
			CardIds.MurkwaterScribe,
			CardIds.Myrmidon,
			CardIds.NagaGiant,
			CardIds.NostalgicInitiate_NostalgicInitiateToken_TOY_340t1,
			CardIds.NostalgicInitiate_TOY_340,
			CardIds.OopsAllSpellsTavernBrawl,
			CardIds.PalmReading,
			CardIds.ParchedDesperado_WW_407,
			CardIds.PartyPortalTavernBrawl_PVPDR_SCH_Active08,
			CardIds.Pelagos_CORE_REV_250,
			CardIds.Pelagos_REV_250,
			CardIds.Pelagos_REV_781,
			CardIds.PortalmancerSkyla_WORK_063,
			CardIds.PowerWordFortitude,
			CardIds.PreparationCore,
			CardIds.PreparationLegacy,
			CardIds.PreparationVanilla,
			CardIds.PriestessValishj,
			CardIds.PrimordialProtector_BAR_042,
			CardIds.PrisonBreaker_YOG_411,
			CardIds.Pyrotechnician,
			CardIds.QueenAzshara_TSC_641,
			CardIds.Queensguard,
			CardIds.RaidTheSkyTemple,
			CardIds.RajNazjan,
			CardIds.RayllaSandSculptor_VAC_424,
			CardIds.RazzleDazzler_VAC_301,
			CardIds.Reforestation_AidOfTheForest_EDR_843a,
			CardIds.RefreshingSpringWater,
			CardIds.Rewind_ETC_532,
			CardIds.RhoninsScryingOrbTavernBrawl,
			CardIds.RimefangSwordCore,
			CardIds.RimefangSword_LEG_RLK_710,
			CardIds.RimescaleSiren,
			CardIds.RingOfRefreshmentTavernBrawl,
			CardIds.RitualOfTheNewMoon_EDR_461,
			CardIds.RobeOfTheApprenticeTavernBrawl,
			CardIds.RobeOfTheMagi,
			CardIds.RobesOfShrinkingTavernBrawl,
			CardIds.RuleModifier_SpreadOfCorruptionToken_TTN_002t45,
			CardIds.RuneDagger,
			CardIds.SaroniteShambler_YOG_521,
			CardIds.ScrollSavvy,
			CardIds.ShadowOfDemise,
			CardIds.ShadowVisions,
			CardIds.ShatariCloakfield_GDB_103,
			CardIds.SheldrasMoontree,
			CardIds.ShieldBattery_SC_759,
			CardIds.ShirvallahTheTiger,
			CardIds.ShiveringSorceress,
			CardIds.Sif,
			CardIds.SkulkingGeist_CORE_ICC_701,
			CardIds.SkulkingGeist_ICC_701,
			CardIds.SlitheringDeathscale,
			CardIds.SpectralTrainee,
			CardIds.Spellcoiler,
			CardIds.SpitefulSummoner,
			CardIds.Starscryer,
			CardIds.SunstridersCrownTavernBrawl,
			CardIds.Surfalopod_VAC_443,
			CardIds.SwiftscaleTrickster,
			CardIds.TalentedArcanist,
			CardIds.TangledWrath,
			CardIds.TheFistOfRaDen,
			CardIds.TheStoneOfJordanTavernBrawlToken,
			CardIds.TheUpperHand,
			CardIds.ThriveInTheShadowsCore,
			CardIds.TidePools_VAC_522,
			CardIds.TidepoolPupil_VAC_304,
			CardIds.TortollanPilgrim,
			CardIds.Triangulate_GDB_451,
			CardIds.TrolleyProblem_WW_436,
			CardIds.TwinbowTerrorcoil,
			CardIds.Tyrande_EDR_464,
			CardIds.UnderTheSea_VAC_431,
			CardIds.UngoroBrochure_DalaranBrochureToken_WORK_050t,
			CardIds.UrchinSpines,
			CardIds.Ursol_EDR_259,
			CardIds.VelensChosen,
			CardIds.ViciousSlitherspear_CORE_TSC_827,
			CardIds.ViciousSlitherspear_TSC_827,
			CardIds.VoidFlayer,
			CardIds.VolumeUp,
			CardIds.WeaverOfTheCycle_EDR_472,
			CardIds.Whirlweaver,
			CardIds.WickedWitchdoctor,
			CardIds.WickedWitchdoctor_WON_083,
			CardIds.WildPyromancerCore,
			CardIds.WildPyromancerLegacy,
			CardIds.WildPyromancerVanilla,
			CardIds.WisdomOfNorgannon,
			CardIds.WishOfTheNewMoon_EDR_460,
			CardIds.YoggSaronHopesEnd_OG_134,
			CardIds.YoggSaronMasterOfFate
		));
	}

	// COST_EQUAL_7 + SPELL (1 cards)
	if (refCard.cost === 7 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_8 + SPELL (1 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_9 + SPELL (1 cards)
	if (refCard.cost === 9 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_10 + SPELL (1 cards)
	if (refCard.cost === 10 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// ARCANE (2 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneFluxTavernBrawl,
			CardIds.ArcaniteCrystalTavernBrawl
		));
	}

	// COST_MORE_4 + SPELL (3 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AshleafPixie_FIR_961,
			CardIds.Groundskeeper,
			CardIds.HagathaTheFabled_TOY_504
		));
	}

	// COST_EQUAL_1 + SPELL (4 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551,
			CardIds.Gazlowe,
			CardIds.TrinketTracker
		));
	}

	// COST_EQUAL_2 + SPELL (2 cards)
	if (refCard.cost === 2 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551
		));
	}

	// COST_EQUAL_3 + SPELL (2 cards)
	if (refCard.cost === 3 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551
		));
	}

	// FROST (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BitterColdTavernBrawl
		));
	}

	// HOLY + SPELL (15 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CarielRoame_BAR_902,
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.FlickeringLightbot_MIS_918,
			CardIds.GuardianLightTavernBrawl,
			CardIds.HeraldOfLight,
			CardIds.HiHoSilverwing_WW_344,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.InvigoratingLightTavernBrawl,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ShimmeringSunfish,
			CardIds.StarlightGroove,
			CardIds.TheGardensGrace,
			CardIds.VeteranWarmedic
		));
	}

	// NATURE (2 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ChampionOfStorms,
			CardIds.CrashOfThunder
		));
	}

	// FEL (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CorruptedFelstoneTavernBrawl
		));
	}

	// SHADOW (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CrystalsmithCultist,
			CardIds.Darkbomb,
			CardIds.Darkbomb_WON_095
		));
	}

	// NATURE + SPELL (10 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DeviateDreadfang,
			CardIds.GroveShaper_EDR_271,
			CardIds.HeraldOfNature,
			CardIds.IronRootsTavernBrawl,
			CardIds.MendingPoolsTavernBrawl,
			CardIds.NaturalForceTavernBrawl,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.ToadOfTheWilds,
			CardIds.TopiorTheShrubbagazzor,
			CardIds.WidowbloomSeedsman
		));
	}

	// HOLY (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DivineIlluminationTavernBrawl
		));
	}

	// SHADOW + SPELL (11 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.EerieStoneTavernBrawl,
			CardIds.HeraldOfShadows,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.LadyDarkvein,
			CardIds.LadyDarkvein_CORE_REV_373,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.Shadowborn,
			CardIds.ShadowclothNeedle,
			CardIds.SketchArtist_TOY_916,
			CardIds.StaffOfPainTavernBrawl,
			CardIds.TwilightDeceptor
		));
	}

	// FEL + SPELL (10 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FelfireBlaze_FIR_904,
			CardIds.Felgorger_SW_043,
			CardIds.FossilFanatic,
			CardIds.GraveDefiler,
			CardIds.HeraldOfChaos,
			CardIds.IllidanStormrage_FelInside_THD_004p,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.Scorchreaver_FIR_952,
			CardIds.WitherTheWeakTavernBrawl
		));
	}

	// FIRE + SPELL (12 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FirekeepersIdolTavernBrawl,
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.HotStreak,
			CardIds.InfernoHerald_FIR_913,
			CardIds.KindlingFlameTavernBrawl,
			CardIds.LivingFlame_FIR_929,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.ScorchingWinds_FIR_910,
			CardIds.SunfuryChampion,
			CardIds.Thoribelore,
			CardIds.VolcanicThrasher_TLC_223
		));
	}

	// FROST + SPELL (8 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.HarbingerOfWinterCore_RLK_511,
			CardIds.HeraldOfLokholar,
			CardIds.IceRevenant,
			CardIds.LadyDeathwhisper_RLK_713,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.Rimetongue,
			CardIds.WatercolorArtist_TOY_376
		));
	}

	// COST_MORE_5 + SPELL (1 cards)
	if (refCard.cost > 5 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GreySageParrot
		));
	}

	// ARCANE + SPELL (7 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.HalduronBrightwing,
			CardIds.MagistersApprentice,
			CardIds.SilvermoonFarstrider_RLK_826,
			CardIds.Stargazing_WW_425,
			CardIds.StarlightReactor_GDB_108,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.Vexallus
		));
	}

	// COST_MORE_1 + SPELL (1 cards)
	if (refCard.cost > 1 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.PlaguebringerTavernBrawl
		));
	}

	// COST_LESS_4 + SPELL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.StonehearthVindicator
		));
	}

	// COST_LESS_3 + SPELL (2 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.VioletTreasuregill_TLC_438
		));
	}

	// COST_MORE_0 + SHADOW + SPELL (1 cards)
	if (refCard.cost > 0 && refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TamsinRoame_BAR_918
		));
	}

	return null;
};