/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings-v2.ts
 * MINION-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseMinionSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	// MECH + MINION (4 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('MECH') && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AbsorbentParasite,
			CardIds.CollectorsIreTavernBrawlToken,
			CardIds.DrocomurchanicasTavernBrawlToken,
			CardIds.GorillabotA3Core
		));
	}

	// BEAST + MINION (3 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AbsorbentParasite,
			CardIds.Banjosaur,
			CardIds.TheCurator_CORE_KAR_061
		));
	}

	// UNDEAD (28 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('UNDEAD')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AcolyteOfDeath_CORE_RLK_121,
			CardIds.AmateurPuppeteer_AmateurPuppeteerToken_TOY_828t,
			CardIds.ArmsDealer_RLK_824,
			CardIds.Banshee_RLK_957,
			CardIds.BoneFlinger,
			CardIds.Bonecaller,
			CardIds.DeadAir,
			CardIds.DrakkariEmbalmer_RLK_119,
			CardIds.ElderNadox,
			CardIds.FleshBehemoth_RLK_Prologue_RLK_830,
			CardIds.GluthSicleTavernBrawl,
			CardIds.GluthTavernBrawl_PVPDR_Sai_T1,
			CardIds.GraveDigging,
			CardIds.Invincible,
			CardIds.LesserSpinelSpellstone_GreaterSpinelSpellstoneToken_TOY_825t2,
			CardIds.NecroticMortician_CORE_RLK_116,
			CardIds.NerubianVizier,
			CardIds.NoxiousInfiltrator,
			CardIds.PoisonBreath_CORE_EDR_002,
			CardIds.RottingNecromancer,
			CardIds.ShadowWordUndeath,
			CardIds.SicklyGrimewalker_YOG_512,
			CardIds.SkeletalSidekickCore_RLK_958,
			CardIds.SoulburnerVaria_YOG_520,
			CardIds.TwistedTether,
			CardIds.UndyingAllies,
			CardIds.UnlivingChampion,
			CardIds.Wither
		));
	}

	// BEAST (51 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AddledGrizzly_WON_009,
			CardIds.AzsharanSaber_SunkenSaberToken,
			CardIds.BigDreams,
			CardIds.BunnyStomper_WW_435,
			CardIds.ButchTavernBrawl,
			CardIds.CallPet_GVG_017,
			CardIds.CastleKennels_REV_790,
			CardIds.CattleRustler_WW_351,
			CardIds.CowerInFear_TLC_823,
			CardIds.Dinositter_TLC_822,
			CardIds.ExoticHoundmaster_EDR_226,
			CardIds.FaithfulCompanions,
			CardIds.FangboundDruid,
			CardIds.Goldrinn_EDR_480,
			CardIds.HarpoonGun,
			CardIds.HemetFoamMarksman_TOY_355,
			CardIds.HerbivoreAssistant_DINO_419,
			CardIds.JungleGym_TOY_359,
			CardIds.KathrenaWinterwisp,
			CardIds.KingOfBeasts_WON_162,
			CardIds.KnightOfTheWild_WON_003,
			CardIds.LivingSeedRank1_LivingSeedRank3Token,
			CardIds.Malorne_WON_011,
			CardIds.MenagerieWarden_WON_305,
			CardIds.MessengerBuzzard_WW_807,
			CardIds.MysteryEgg_MysteryEggToken_TOY_351t,
			CardIds.Oondasta,
			CardIds.PaintedCanvasaur_TOY_350,
			CardIds.PeacefulPiper,
			CardIds.PeacefulPiper_FriendlyFace,
			CardIds.PossessedAnimancer_DINO_131,
			CardIds.PredatoryInstincts,
			CardIds.RamkahenWildtamer,
			CardIds.RoostingGargoyle_CORE_REV_351,
			CardIds.ScavengersIngenuity,
			CardIds.ScrapShot,
			CardIds.SelectiveBreederCore,
			CardIds.Serpentbloom,
			CardIds.Shadehound,
			CardIds.ShandoWildclaw_Transfiguration,
			CardIds.StarvingTavernBrawl,
			CardIds.StormpikeBattleRam,
			CardIds.SupremeDinomancy_TLC_828,
			CardIds.TavishStormpike_BAR_038,
			CardIds.TendingDragonkin_FIR_960,
			CardIds.ThornmantleMusician,
			CardIds.Thunderbringer_WW_440,
			CardIds.VirmenSensei_WON_300,
			CardIds.WarsongWrangler,
			CardIds.WingCommanderIchman_AV_336,
			CardIds.WitchingHour
		));
	}

	// PIRATE (18 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('PIRATE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AdrenalineFiend_VAC_927,
			CardIds.Ancharrr,
			CardIds.BeckoningBicornTavernBrawl,
			CardIds.CannonBarrage,
			CardIds.CaptainsParrotVanilla,
			CardIds.CutlassCourier,
			CardIds.HarborScamp,
			CardIds.HozenRoughhouser_VAC_938,
			CardIds.PatchesThePirate_CFM_637,
			CardIds.PatchesThePirate_LockedAndLoaded_THD_025p,
			CardIds.PirateAdmiralHooktusk,
			CardIds.SailboatCaptain_VAC_937,
			CardIds.ShadyDealer,
			CardIds.SharkPuncher_WON_138,
			CardIds.ShipsCannon,
			CardIds.ShoplifterGoldbeard_TOY_511,
			CardIds.Swordfish,
			CardIds.TreasureDistributor_TOY_518
		));
	}

	// MINION (184 cards)
	if (refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AegwynnTheGuardian_LEG_CS3_001,
			CardIds.AlarmedSecuritybot_YOG_510,
			CardIds.AllianceBannerman,
			CardIds.AlwaysABiggerJormungar,
			CardIds.AmitusThePeacekeeper,
			CardIds.AmitusThePeacekeeper_ReinforcedToken,
			CardIds.AncestorsCall,
			CardIds.AnimaExtractor_CORE_REV_332,
			CardIds.AnimatedBerserker_ICC_238,
			CardIds.Anubrekhan_RLK_659,
			CardIds.ApexisBlast,
			CardIds.Artanis_SC_754,
			CardIds.Assembly_Assembly,
			CardIds.Aviana_WON_012,
			CardIds.AzsharanGardens_SunkenGardensToken,
			CardIds.BackstageBouncer,
			CardIds.BanelingBarrage_SC_001,
			CardIds.Barnes,
			CardIds.BeanstalkBrute_EDR_230,
			CardIds.Birdwatching_VAC_408,
			CardIds.BlackrockNRoll,
			CardIds.BladeOfTheBurningSun,
			CardIds.Blink_SC_761,
			CardIds.BloodCrusader,
			CardIds.BloodMoonTavernBrawl,
			CardIds.BloodOfGhuun,
			CardIds.BobTheBartender_FindATripleToken_BG31_BOBt4,
			CardIds.Breakdance,
			CardIds.BronzeSignetTavernBrawl,
			CardIds.BusyBot_WORK_002,
			CardIds.CapturedFlag,
			CardIds.CarnivorousCube,
			CardIds.CarnivorousCubicle_WORK_042,
			CardIds.CharredChameleon_FIR_908,
			CardIds.ChemicalSpill_TOY_602,
			CardIds.ChorusRiff,
			CardIds.ClawMachine,
			CardIds.CliffDive_VAC_926,
			CardIds.CloningDevice,
			CardIds.ColdFeet,
			CardIds.ColiferoTheArtist_TOY_703,
			CardIds.Commencement,
			CardIds.CowardlyGrunt,
			CardIds.CreationProtocol_CreationProtocolToken,
			CardIds.CreepTumor_SC_011,
			CardIds.CursedCatacombs_TLC_451,
			CardIds.DealWithADevil,
			CardIds.DeckOfChaos,
			CardIds.DevilsaurMask_DINO_403,
			CardIds.DimensionalRipper,
			CardIds.DisciplinarianGandling,
			CardIds.DiscoMaul,
			CardIds.DivineStar_GDB_460,
			CardIds.DreamboundRaptor_EDR_849,
			CardIds.EchoOfMedivh,
			CardIds.EliseBadlandsSavior_WW_392,
			CardIds.ElixirOfVigorTavernBrawl,
			CardIds.ElvenMinstrelCore,
			CardIds.Embiggen,
			CardIds.Ensmallen_TOY_805,
			CardIds.EternalServitude_ICC_213,
			CardIds.Eureka,
			CardIds.FeldoreiWarband,
			CardIds.Firegill_DINO_404,
			CardIds.FlashSale_TOY_716,
			CardIds.FoodFight_EntréeToken_VAC_533t,
			CardIds.FrontLines_Story_11_FrontLines,
			CardIds.FungalFortunes,
			CardIds.GatherYourParty,
			CardIds.GreedyGainsTavernBrawl,
			CardIds.GrimestreetOutfitterCore,
			CardIds.GrimyGadgeteer,
			CardIds.HabeasCorpses,
			CardIds.HagathasEmbraceTavernBrawl,
			CardIds.Hallucination_SC_757,
			CardIds.HarmonicMetal_DissonantMetalToken,
			CardIds.HatcheryHelper_TLC_233,
			CardIds.HatchingCeremony_DINO_405,
			CardIds.HawkstriderRancher,
			CardIds.HealingWave_WON_320,
			CardIds.Hellion_HellbatToken_SC_412t,
			CardIds.HolyEggbearer_DINO_411,
			CardIds.HopeOfQuelthalas,
			CardIds.ImpendingCatastrophe,
			CardIds.ImployeeOfTheMonth_WORK_009,
			CardIds.ImprisonedScrapImp,
			CardIds.Infestor_SC_002,
			CardIds.Insight_InsightToken,
			CardIds.InvigoratingSermon,
			CardIds.IxlidFungalLord,
			CardIds.JalTheSharpshot,
			CardIds.JepettoJoybuzz,
			CardIds.JimRaynor_Stimpack_SC_400p,
			CardIds.KabalTalonpriest,
			CardIds.KeeperOfFlame_FIR_928,
			CardIds.KeepersStrength_YOG_509,
			CardIds.LadyInWhite,
			CardIds.LeadDancer,
			CardIds.Lightspeed_GDB_457,
			CardIds.LivingGarden_EDR_518,
			CardIds.LohTheLivingLegend_TLC_257,
			CardIds.LokenJailerOfYoggSaron,
			CardIds.LongneckEgg_DINO_130,
			CardIds.LorthemarTheron_RLK_593,
			CardIds.Malfunction_MIS_107,
			CardIds.ManufacturingError_TOY_371,
			CardIds.MaskedReveler,
			CardIds.MasterJouster,
			CardIds.MaximaBlastenheimer,
			CardIds.MeatGrinder_RLK_120,
			CardIds.Melomania,
			CardIds.Merithra_EDR_238,
			CardIds.MoatLurker,
			CardIds.MonstrousMosquito_EDR_816,
			CardIds.MoshPit,
			CardIds.Muckmorpher,
			CardIds.MuscleOTron_YOG_525,
			CardIds.MutatingInjection_NAX11_04,
			CardIds.NightmareLordXavius_EDR_856,
			CardIds.OldMilitiaHorn_VeteransMilitiaHornTavernBrawl,
			CardIds.OrbitalHalo_GDB_439,
			CardIds.OrbitalMoon_GDB_475,
			CardIds.OutfitTailor,
			CardIds.OverlordsWhip,
			CardIds.PaintersVirtue_TOY_810,
			CardIds.PantherMask_DINO_432,
			CardIds.PendantOfEarth_DEEP_026,
			CardIds.PhotonCannon_SC_753,
			CardIds.PileOnHeroic,
			CardIds.PowerChordSynchronize,
			CardIds.ProvingGrounds,
			CardIds.Psychopomp,
			CardIds.PuppetmasterDorian_MIS_026,
			CardIds.RaidBossOnyxia_ONY_004,
			CardIds.Ravage_SC_004hp,
			CardIds.Reforestation_Fertilize_EDR_843b,
			CardIds.RiskySkipper,
			CardIds.Roach_SC_012,
			CardIds.RotheartDryad_EDR_485,
			CardIds.RunningWild_RunningWild,
			CardIds.SalhetsPride,
			CardIds.SeafloorSavior_TSC_083,
			CardIds.Seismopod_DINO_421,
			CardIds.Sentry_SC_764,
			CardIds.SesselieOfTheFaeCourt_REV_782,
			CardIds.ShadowEssence_ICC_235,
			CardIds.Shadowcaster,
			CardIds.Shadowcasting101TavernBrawl,
			CardIds.ShadowstepVanilla,
			CardIds.ShroudOfConcealment,
			CardIds.SilvermoonBrochure_WORK_017,
			CardIds.SilvermoonPortal_WON_309,
			CardIds.SmolderingStrength_FIR_914,
			CardIds.SoulrestCeremony_DINO_417,
			CardIds.SowTheSeedsTavernBrawl,
			CardIds.SpawningPool_SC_000,
			CardIds.SpiritOfTheBadlands_MirageToken_WW_337t,
			CardIds.SpiritPeddler_WORK_015,
			CardIds.SpotTheDifference_TOY_374,
			CardIds.SrExcavatorTavernBrawl,
			CardIds.StewardOfDarkshire_WON_310,
			CardIds.StrengthInNumbers,
			CardIds.SuperchargeTavernBrawl,
			CardIds.SurvivalOfTheFittest,
			CardIds.Switcheroo,
			CardIds.TenGallonHat_WW_811,
			CardIds.TheBoomReaver,
			CardIds.TheBoomship,
			CardIds.TheDarkPortal_BT_302,
			CardIds.TheLichKing_ArmyOfTheFrozenThroneToken,
			CardIds.TogwagglesScheme,
			CardIds.TravelmasterDungar_WORK_043,
			CardIds.UngoroBrochure_WORK_050,
			CardIds.UnlockedPotential,
			CardIds.VarianWrynn_AT_072,
			CardIds.ViciousBloodworm_RLK_711,
			CardIds.Viper_SC_018,
			CardIds.VitalitySurge,
			CardIds.WarpGate_SC_751,
			CardIds.WarsongCommanderVanilla,
			CardIds.WebOfDeception_EDR_523,
			CardIds.YoggInTheBox_TOY_372,
			CardIds.YouthfulBrewmasterVanilla,
			CardIds.YshaarjRageUnbound
		));
	}

	// DEMON (17 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('DEMON')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AllShallServeTavernBrawl,
			CardIds.BlackHole_GDB_126,
			CardIds.BloodreaverGuldan_ICC_831,
			CardIds.CariaFelsoul,
			CardIds.CraneGame_TOY_884,
			CardIds.Demonfuse_DarkFusionEnchantment,
			CardIds.Felosophy,
			CardIds.GameMasterNemsy_TOY_524,
			CardIds.InfernalStratagem_GDB_122,
			CardIds.Malganis_GVG_021,
			CardIds.PitCommander,
			CardIds.RagingFelscreamer_BT_416,
			CardIds.SenseDemonsVanilla_VAN_EX1_317,
			CardIds.SigilOfReckoning,
			CardIds.TabletopRoleplayer_TOY_915,
			CardIds.UmpiresGrasp_TOY_641,
			CardIds.VoidcallerCore
		));
	}

	// MINION + NOT_TRIBELESS (11 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races && refCard.races.length > 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AllYouCanEat_VAC_528,
			CardIds.AmalgamOfTheDeep,
			CardIds.FlightOfTheFirehawk_TLC_222,
			CardIds.MenagerieMug_CORE_WON_141,
			CardIds.PartyAnimal,
			CardIds.RoaringApplause,
			CardIds.RockMasterVoone_ETC_121,
			CardIds.SpiritOfTheMountain_TLC_229,
			CardIds.ThePurator,
			CardIds.TortollanStoryteller_TLC_254,
			CardIds.TrustyCompanion_WW_027
		));
	}

	// DRAGON (49 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('DRAGON')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AmberWhelp,
			CardIds.BlackwingCorruptor_WON_329,
			CardIds.BreathOfDreams,
			CardIds.BroodKeeper_EDR_457,
			CardIds.CandleBreath,
			CardIds.Chillmaw_CORE_AT_123,
			CardIds.CloudSerpent_TLC_888,
			CardIds.ClutchOfCorruption_EDR_454,
			CardIds.DaringDrake,
			CardIds.Darkrider_EDR_456,
			CardIds.DesertNestmatron_WW_826,
			CardIds.DraconicDreamTavernBrawl,
			CardIds.DragonAffinityTavernBrawl,
			CardIds.DragonBreeder,
			CardIds.DragonConsort,
			CardIds.DragonGolem_WW_822,
			CardIds.DragonbloodTavernBrawl,
			CardIds.DragonboneRitualTavernBrawl,
			CardIds.Dragoncaster,
			CardIds.DrakonidOperativeCore,
			CardIds.FlyOffTheShelves_TOY_714,
			CardIds.FrizzKindleroost,
			CardIds.FutureEmissary_WON_140,
			CardIds.GiftwrappedWhelp_TOY_386,
			CardIds.HeraldOfFlame_TRLA_176,
			CardIds.HornOfWrathion,
			CardIds.Kazakusan_ONY_005,
			CardIds.MalygosAspectOfMagic,
			CardIds.NaralexHeraldOfTheFlights_EDR_844,
			CardIds.NetherBreath_DRG_205,
			CardIds.OnyxianWarder,
			CardIds.PetalPeddler_EDR_889,
			CardIds.RedscaleDragontamer_CORE_DMF_194,
			CardIds.ScaleReplica_TOY_387,
			CardIds.Scalerider,
			CardIds.Scaleworm,
			CardIds.Skyfin,
			CardIds.Soridormi_WON_146,
			CardIds.SpinetailDrake_WW_820,
			CardIds.SplishSplashWhelp_WW_819,
			CardIds.Stormhammer,
			CardIds.SuccumbToMadness_EDR_455,
			CardIds.TakeToTheSkies_WW_816,
			CardIds.TastyFlyfish,
			CardIds.Timewarden,
			CardIds.TimewinderZarimi_TOY_385,
			CardIds.TormentedDreadwing_EDR_572,
			CardIds.TwilightGuardian,
			CardIds.WingCommander
		));
	}

	// MINION + UNDEAD (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('UNDEAD')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AmorphousSlime,
			CardIds.SinisterSoulcage_YOG_513
		));
	}

	// COST_LESS_4 + MINION (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AnimateDead
		));
	}

	// ELEMENTAL (39 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('ELEMENTAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AnimatedAvalanche,
			CardIds.AquaArchivist,
			CardIds.AridStormer,
			CardIds.AzeriteGiant_WW_025,
			CardIds.Blazecaller,
			CardIds.BralmaSearstone_TLC_228,
			CardIds.CloudSerpent_TLC_888,
			CardIds.DangBlastedElemental_WW_397,
			CardIds.ElementalEvocation,
			CardIds.ElementaryReaction,
			CardIds.ErodedSediment_WW_428,
			CardIds.FireBreath_DINO_406,
			CardIds.FirePlumeHarbinger,
			CardIds.FlameRevenant,
			CardIds.FrostLichJaina_CORE_ICC_833,
			CardIds.FrostfinChomper,
			CardIds.GraniteForgeborn,
			CardIds.Gyreworm,
			CardIds.KalimosPrimalLord_Core_UNG_211,
			CardIds.KindlingElemental,
			CardIds.Lamplighter_VAC_442,
			CardIds.LilypadLurker,
			CardIds.LivingPrairie_WW_024,
			CardIds.MesaduneTheFractured_WW_429,
			CardIds.MinecartCruiser_WW_326,
			CardIds.OverflowSurger_WW_424,
			CardIds.Sandbinder,
			CardIds.ShaleSpider_DEEP_034,
			CardIds.SkarrTheCatastrophe_WW_026,
			CardIds.SolarFlare_GDB_305,
			CardIds.SpontaneousCombustion_GDB_456,
			CardIds.SteamSurger,
			CardIds.StoneSentinel,
			CardIds.TaintedRemnant_YOG_519,
			CardIds.Therazane_DEEP_036,
			CardIds.Thunderbringer_WW_440,
			CardIds.UnchainedGladiator,
			CardIds.WailingVapor_CORE_WC_042,
			CardIds.WindsweptPageturner_TLC_220
		));
	}

	// COST_EQUAL_1 + MINION (5 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ApothecarysCaravan,
			CardIds.BoogieDown,
			CardIds.K90tron,
			CardIds.SonyaWaterdancer_TOY_515,
			CardIds.TrustyFishingRod_VAC_960
		));
	}

	// MURLOC (14 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('MURLOC')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AzsharanScavenger_SunkenScavengerToken,
			CardIds.Braingill_GDB_878,
			CardIds.CookiesLadleTavernBrawl,
			CardIds.DiveTheGolakkaDepths_TLC_426,
			CardIds.FinjaTheFlyingStar_CORE_CFM_344,
			CardIds.GorlocRavager,
			CardIds.HotSpringGlider_TLC_428,
			CardIds.IceFishing_ICC_089,
			CardIds.ItsRainingFin,
			CardIds.LushwaterScout,
			CardIds.SirFinleyMrrgglton_ScalesOfJustice_THD_044p,
			CardIds.TidelostBurrower,
			CardIds.TinyfinsCaravan,
			CardIds.UnderbellyAngler
		));
	}

	// COST_LESS_3 + MINION (3 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BandOfBeesTavernBrawl,
			CardIds.CallToArms,
			CardIds.OracleOfElune
		));
	}

	// NAGA (8 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('NAGA')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarbedNets,
			CardIds.CoilCastingTavernBrawl,
			CardIds.ConchsCall,
			CardIds.NagasPride,
			CardIds.OasisOutlaws_WW_404,
			CardIds.Predation,
			CardIds.SeaweedStrike,
			CardIds.SerpentWig_TSC_215
		));
	}

	// MECH (26 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('MECH')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Bubblebot_TSC_059,
			CardIds.ClickClocker,
			CardIds.ClockworkKnight,
			CardIds.DrBoomMadGenius,
			CardIds.DrBoom_BoomBarrage_THD_034p,
			CardIds.DynOMaticCore,
			CardIds.FrequencyOscillator,
			CardIds.GaiaTheTechtonic_TSC_029,
			CardIds.GoboglideTech,
			CardIds.IniStormcoil_TSC_649,
			CardIds.InventorsAura,
			CardIds.KangorsEndlessArmy,
			CardIds.MechaShark_TSC_054,
			CardIds.MimironTheMastermind,
			CardIds.PitStop,
			CardIds.RadarDetector_TSC_079,
			CardIds.SeafloorGateway_TSC_055,
			CardIds.SeascoutOperator_TSC_646,
			CardIds.SecurityAutomaton_TSC_928,
			CardIds.SootSpewer_WON_033,
			CardIds.TimelineAccelerator_WON_139,
			CardIds.TinyWorldbreaker_YOG_527,
			CardIds.TramOperator,
			CardIds.TrenchSurveyor_TSC_642,
			CardIds.Ursatron,
			CardIds.WreckemAndDeckem_TOY_603
		));
	}

	// COST_MORE_4 + MINION (1 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CaricatureArtist_TOY_391
		));
	}

	// ATTACK_MORE_4 + MINION (2 cards)
	if (refCard.attack > 4 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ClimbingHook_VAC_932,
			CardIds.GiantAnaconda
		));
	}

	// DRAGON + MINION (3 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('DRAGON') && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CollectorsIreTavernBrawlToken,
			CardIds.DrocomurchanicasTavernBrawlToken,
			CardIds.TheCurator_CORE_KAR_061
		));
	}

	// MINION + PIRATE (1 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('PIRATE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CollectorsIreTavernBrawlToken
		));
	}

	// ATTACK_MORE_0 + MINION (1 cards)
	if (refCard.attack > 0 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Crystology
		));
	}

	// DEMON + MINION (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('DEMON') && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DirgeOfDespair,
			CardIds.KanrethadEbonlocke_KanrethadPrimeToken
		));
	}

	// LEGENDARY + MINION (4 cards)
	if (refCard.rarity?.toUpperCase() === 'LEGENDARY' && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DisksOfLegendTavernBrawl,
			CardIds.InspiringPresenceTavernBrawl,
			CardIds.RingOfPhaseshiftingTavernBrawl,
			CardIds.RoyalGreatswordTavernBrawlToken
		));
	}

	// TOTEM (5 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('TOTEM')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DraeneiTotemcarver_CORE_AT_047,
			CardIds.Gigantotem,
			CardIds.SplittingAxe,
			CardIds.TheStonewright,
			CardIds.ThingFromBelowCore
		));
	}

	// MINION + MURLOC (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('MURLOC')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DrocomurchanicasTavernBrawlToken,
			CardIds.TheCurator_CORE_KAR_061
		));
	}

	// ELEMENTAL + LEGENDARY (1 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('ELEMENTAL') && refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AlakirTheWindlord_ElementalEvocation_THD_026p
		));
	}

	// COST_LESS_5 + MINION (2 cards)
	if (refCard.cost < 5 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GrizzledGuardian,
			CardIds.OakenSummons_CORE_LOOT_309
		));
	}

	// BEAST + COST_LESS_6 (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 6) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GuardianAnimals,
			CardIds.PetCollector
		));
	}

	// COST_MORE_0 + MINION (1 cards)
	if (refCard.cost > 0 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Hybridization_TLC_236
		));
	}

	// COST_EQUAL_7 + MINION (1 cards)
	if (refCard.cost === 7 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// COST_EQUAL_8 + MINION (2 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon,
			CardIds.SilverVanguard
		));
	}

	// COST_EQUAL_9 + MINION (1 cards)
	if (refCard.cost === 9 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// COST_EQUAL_10 + MINION (1 cards)
	if (refCard.cost === 10 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// MINION + NEUTRAL (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.MeekMasteryTavernBrawl,
			CardIds.MulchMadnessTavernBrawl
		));
	}

	// COST_LESS_4 + COST_MORE_0 + MINION (1 cards)
	if (refCard.cost < 4 && refCard.cost > 0 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Rally
		));
	}

	// COST_MORE_5 + MINION (1 cards)
	if (refCard.cost > 5 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ScepterOfSummoning
		));
	}

	// MINION + TOTEM (1 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('TOTEM')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TotemicSurge
		));
	}

	// BEAST + COST_LESS_4 (1 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TrialOfTheJormungars_WON_028
		));
	}

	// COST_LESS_4 + MINION + NEUTRAL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.WarCommandsTavernBrawl
		));
	}

	return null;
};