/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings.ts
 * SPELL-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseSpellSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	const matchingCardIds: CardIds[] = [];

	// ARCANE + SPELL (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.HalduronBrightwing,
			CardIds.MagistersApprentice,
			CardIds.Stargazing_WW_425
		);
	}

	// COST_EQUAL_1 + SPELL (1 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.TrinketTracker
		);
	}

	// COST_EQUAL_2 + SPELL (2 cards)
	if (refCard.cost === 2 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551
		);
	}

	// COST_EQUAL_8 + SPELL (1 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.ArcaneBrilliance
		);
	}

	// COST_LESS_3 + SPELL (1 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.VioletTreasuregill_TLC_438
		);
	}

	// COST_LESS_4 + SPELL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.StonehearthVindicator
		);
	}

	// COST_MORE_1 + SPELL (1 cards)
	if (refCard.cost > 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.PlaguebringerTavernBrawl
		);
	}

	// COST_MORE_4 + SPELL (1 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.HagathaTheFabled_TOY_504
		);
	}

	// FEL + SPELL (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.Felgorger_SW_043,
			CardIds.FossilFanatic,
			CardIds.GraveDefiler
		);
	}

	// FIRE + SPELL (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.FirekeepersIdolTavernBrawl,
			CardIds.LivingFlame_FIR_929,
			CardIds.VolcanicThrasher_TLC_223
		);
	}

	// FROST + SPELL (4 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.HarbingerOfWinterCore_RLK_511,
			CardIds.HeraldOfLokholar,
			CardIds.IceRevenant,
			CardIds.WatercolorArtist_TOY_376
		);
	}

	// HOLY + SPELL (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.InvigoratingLightTavernBrawl
		);
	}

	// NATURE + SPELL (2 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.MendingPoolsTavernBrawl,
			CardIds.WidowbloomSeedsman
		);
	}

	// SHADOW + SPELL (4 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.EerieStoneTavernBrawl,
			CardIds.HeraldOfShadows,
			CardIds.SketchArtist_TOY_916,
			CardIds.TwilightDeceptor
		);
	}

	// ARCANE (7 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE') {
		matchingCardIds.push(
			CardIds.ArcaneFluxTavernBrawl,
			CardIds.ArcaneQuiver_RLK_817,
			CardIds.ArcaniteCrystalTavernBrawl,
			CardIds.SilvermoonFarstrider_RLK_826,
			CardIds.StarlightReactor_GDB_108,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.Vexallus
		);
	}

	// FEL (9 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL') {
		matchingCardIds.push(
			CardIds.CorruptedFelstoneTavernBrawl,
			CardIds.FelfireBlaze_FIR_904,
			CardIds.FelfireInTheHole,
			CardIds.HeraldOfChaos,
			CardIds.IllidanStormrage_FelInside_THD_004p,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.Scorchreaver_FIR_952,
			CardIds.WitherTheWeakTavernBrawl
		);
	}

	// FIRE (9 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE') {
		matchingCardIds.push(
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.HotStreak,
			CardIds.InfernoHerald_FIR_913,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.ScorchingWinds_FIR_910,
			CardIds.SteamGuardian,
			CardIds.SunfuryChampion,
			CardIds.Thoribelore
		);
	}

	// FROST (8 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST') {
		matchingCardIds.push(
			CardIds.FrostweaveDungeoneer,
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.LadyDeathwhisper_RLK_713,
			CardIds.OverseerFrigidaraCore_RLK_224,
			CardIds.OverseerFrigidaraCore_RLK_Prologue_RLK_224,
			CardIds.OverseerFrigidara_LEG_RLK_224,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.Rimetongue
		);
	}

	// HOLY (18 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY') {
		matchingCardIds.push(
			CardIds.CarielRoame_BAR_902,
			CardIds.DevoutDungeoneer,
			CardIds.DivineIlluminationTavernBrawl,
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.FlickeringLightbot_MIS_918,
			CardIds.GuardianLightTavernBrawl,
			CardIds.HeraldOfLight,
			CardIds.HiHoSilverwing_WW_344,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ShimmeringSunfish,
			CardIds.SpiritGuide,
			CardIds.SpiritGuide_CORE_AV_328,
			CardIds.StarlightGroove,
			CardIds.TheGardensGrace,
			CardIds.VeteranWarmedic
		);
	}

	// NATURE (11 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE') {
		matchingCardIds.push(
			CardIds.ChampionOfStorms,
			CardIds.CrashOfThunder,
			CardIds.DeviateDreadfang,
			CardIds.GroveShaper_EDR_271,
			CardIds.HamuulRunetotem_EDR_845,
			CardIds.HeraldOfNature,
			CardIds.IronRootsTavernBrawl,
			CardIds.PrimalDungeoneer,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.ToadOfTheWilds,
			CardIds.TopiorTheShrubbagazzor
		);
	}

	// SHADOW (13 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		matchingCardIds.push(
			CardIds.CrystalsmithCultist,
			CardIds.Darkbomb,
			CardIds.Darkbomb_WON_095,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.LadyDarkvein,
			CardIds.LadyDarkvein_CORE_REV_373,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.Shadowborn,
			CardIds.ShadowclothNeedle,
			CardIds.SpiritGuide,
			CardIds.SpiritGuide_CORE_AV_328,
			CardIds.StaffOfPainTavernBrawl,
			CardIds.TamsinRoame_BAR_918
		);
	}

	// SPELL (310 cards)
	if (refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.AdvancedTargetingMonocle,
			CardIds.AncientKrakenbane,
			CardIds.AnimatedMoonwell_EDR_254,
			CardIds.ApexisSmuggler,
			CardIds.ArcaneArtificer,
			CardIds.ArcaneArtificerCore,
			CardIds.ArcaneFlakmage,
			CardIds.ArcaneQuiver_RLK_817,
			CardIds.ArchmageAntonidas,
			CardIds.ArchmageAntonidasLegacy,
			CardIds.ArchmageAntonidas_CORE_EX1_559,
			CardIds.ArchmageVargoth,
			CardIds.ArkoniteRevelation_GDB_852,
			CardIds.ArrowSmith,
			CardIds.AshleafPixie_FIR_961,
			CardIds.AudioSplitter,
			CardIds.BabaNaga,
			CardIds.BalindaStonehearth,
			CardIds.BarbaricSorceress,
			CardIds.BargainBin_MIS_105,
			CardIds.BenevolentBanker_WW_384,
			CardIds.Bioluminescence,
			CardIds.BlackjackStunner,
			CardIds.Bloodbloom,
			CardIds.BookOfSpecters,
			CardIds.BrollBearmantle_EDR_853,
			CardIds.BumblingBellhop_VAC_521,
			CardIds.CactusCutter_WW_327,
			CardIds.CannonmasterSmythe_BAR_879,
			CardIds.CardGrader_TOY_054,
			CardIds.CarielRoame_BAR_902,
			CardIds.CelestialShot_YOG_082,
			CardIds.ChiaDrake_ChiaDrakeToken_TOY_801t,
			CardIds.ChiaDrake_Cultivate_TOY_801a,
			CardIds.ChiaDrake_SeedlingGrowth_TOY_801b,
			CardIds.ChiaDrake_TOY_801,
			CardIds.ClearancePromoter_TOY_390,
			CardIds.ClericOfAnshe,
			CardIds.ClericOfScales,
			CardIds.CloakedHuntress_CORE_KAR_006,
			CardIds.CloakedHuntress_KAR_006,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_SCH_Active48,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_Toki_T5,
			CardIds.ClockworkAssistant_GILA_907,
			CardIds.ClockworkAssistant_ONY_005ta11,
			CardIds.CoilskarCommander,
			CardIds.Colossus_SC_758,
			CardIds.CommanderRhyssa,
			CardIds.CommanderSivara_TSC_087,
			CardIds.ConchsCall,
			CardIds.Conductivity_YOG_522,
			CardIds.ConjuredBookkeeper_TLC_226,
			CardIds.ContaminatedLasher_YOG_528,
			CardIds.ContractConjurer,
			CardIds.CoralKeeper,
			CardIds.CosmicKeyboard,
			CardIds.Cosmonaut_GDB_443,
			CardIds.DarkmoonMagician_MIS_303,
			CardIds.Deathchiller_CORE_RLK_083,
			CardIds.Deathchiller_RLK_083,
			CardIds.DeckOfLunacy,
			CardIds.DeepwaterEvoker,
			CardIds.DeviateDreadfang,
			CardIds.DevoutDungeoneer,
			CardIds.DevoutPupil,
			CardIds.DiscoveryOfMagic,
			CardIds.DoorOfShadows,
			CardIds.DoorOfShadows_DoorOfShadowsToken,
			CardIds.DoubleTime,
			CardIds.DozingKelpkeeper,
			CardIds.DragonsFury,
			CardIds.DragonscaleArmaments_EDR_251,
			CardIds.DryscaleDeputy_WW_383,
			CardIds.ElementalAllies,
			CardIds.ElementalInspiration,
			CardIds.EnergyShaper,
			CardIds.EtherealOracle_GDB_310,
			CardIds.ExarchHataaru_TheGalaxysLensToken_GDB_136t,
			CardIds.FaeTrickster_EDR_571,
			CardIds.FarseerNobundo_GDB_447,
			CardIds.FelfireBlaze_FIR_904,
			CardIds.FelfireInTheHole,
			CardIds.Fetch_TOY_352,
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.FlickeringLightbot_MIS_918,
			CardIds.Flowrider,
			CardIds.FrostweaveDungeoneer,
			CardIds.Gazlowe,
			CardIds.GlacialAdvance_RLK_512,
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.GlowflySwarm,
			CardIds.GreenThumbGardener,
			CardIds.GreySageParrot,
			CardIds.Groundskeeper,
			CardIds.GroveShaper_EDR_271,
			CardIds.GuardianLightTavernBrawl,
			CardIds.GuffRunetotem_BAR_720,
			CardIds.GuitarSoloist,
			CardIds.Halkias,
			CardIds.HallazealTheAscended,
			CardIds.HallazealTheAscended_WON_336,
			CardIds.HamuulRunetotem_EDR_845,
			CardIds.Handmaiden,
			CardIds.HarnessTheElementsTavernBrawl,
			CardIds.HedraTheHeretic_TSC_658,
			CardIds.HeraldOfChaos,
			CardIds.HeraldOfLight,
			CardIds.HeraldOfNature,
			CardIds.HiHoSilverwing_WW_344,
			CardIds.HighAbbessAlura,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.HotStreak,
			CardIds.Hullbreaker,
			CardIds.IcebloodTower,
			CardIds.IdolsOfEluneTavernBrawl,
			CardIds.IllidanStormrage_FelInside_THD_004p,
			CardIds.Illuminate,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.IncantersFlow,
			CardIds.InconspicuousRider,
			CardIds.InfernoHerald_FIR_913,
			CardIds.InquisitiveCreation,
			CardIds.IronRootsTavernBrawl,
			CardIds.JotunTheEternal,
			CardIds.JungleJammer,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.KhadgarsScryingOrb,
			CardIds.Kindle_DALA_911,
			CardIds.Kindle_ULDA_911,
			CardIds.KingTide_VAC_524,
			CardIds.KnightOfAnointment,
			CardIds.KolkarPackRunner,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.LadyAnacondra_WC_006,
			CardIds.LadyDarkvein,
			CardIds.LadyDarkvein_CORE_REV_373,
			CardIds.LadyDeathwhisper_RLK_713,
			CardIds.LadyStheno_TSC_218,
			CardIds.LadyVashj_VashjPrimeToken,
			CardIds.LearnDraconic,
			CardIds.LesserEmeraldSpellstone,
			CardIds.LesserEmeraldSpellstone_EmeraldSpellstoneToken,
			CardIds.LesserEmeraldSpellstone_GreaterEmeraldSpellstoneToken,
			CardIds.LifebindersGift,
			CardIds.LifebindersGrowth,
			CardIds.Lifeguard_VAC_919,
			CardIds.LinaShopManager_TOY_531,
			CardIds.LockAndLoad_AT_061,
			CardIds.LockAndLoad_CORE_AT_061,
			CardIds.LockAndLoad_WON_023,
			CardIds.LorewalkerChoLegacy,
			CardIds.LorewalkerChoVanilla,
			CardIds.LorewalkerCho_CORE_EX1_100,
			CardIds.LoveEverlasting,
			CardIds.MagathaBaneOfMusic,
			CardIds.MagisterUnchainedTavernBrawlToken,
			CardIds.MalygosTheSpellweaverCore,
			CardIds.ManaCyclone,
			CardIds.MantleShaper_DEEP_004,
			CardIds.MaroonedArchmage_VAC_435,
			CardIds.MarshlandThresher_TLC_256,
			CardIds.Marshspawn_BT_115,
			CardIds.Marshspawn_CORE_BT_115,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.MeddlesomeServant_YOG_518,
			CardIds.MedivhsValet,
			CardIds.MistahVistah_VAC_519,
			CardIds.Multicaster,
			CardIds.MurkwaterScribe,
			CardIds.Myrmidon,
			CardIds.NagaGiant,
			CardIds.NostalgicInitiate_NostalgicInitiateToken_TOY_340t1,
			CardIds.NostalgicInitiate_TOY_340,
			CardIds.OopsAllSpellsTavernBrawl,
			CardIds.OrionMansionManager,
			CardIds.OverseerFrigidaraCore_RLK_224,
			CardIds.OverseerFrigidaraCore_RLK_Prologue_RLK_224,
			CardIds.OverseerFrigidara_LEG_RLK_224,
			CardIds.PalmReading,
			CardIds.ParchedDesperado_WW_407,
			CardIds.PartyPortalTavernBrawl_PVPDR_SCH_Active08,
			CardIds.Pelagos_CORE_REV_250,
			CardIds.Pelagos_REV_250,
			CardIds.Pelagos_REV_781,
			CardIds.PettingZoo,
			CardIds.PhaseStalker,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.PortalmancerSkyla_WORK_063,
			CardIds.PowerWordFortitude,
			CardIds.PreparationCore,
			CardIds.PreparationLegacy,
			CardIds.PreparationVanilla,
			CardIds.PriestessValishj,
			CardIds.PrimalDungeoneer,
			CardIds.PrimordialProtector_BAR_042,
			CardIds.PrisonBreaker_YOG_411,
			CardIds.ProfessorPutricide_CORE_ICC_204,
			CardIds.ProfessorPutricide_ICC_204,
			CardIds.Pyrotechnician,
			CardIds.QueenAzshara_TSC_641,
			CardIds.Queensguard,
			CardIds.RaidTheSkyTemple,
			CardIds.RajNazjan,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.RayllaSandSculptor_VAC_424,
			CardIds.RazzleDazzler_VAC_301,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.Reforestation_AidOfTheForest_EDR_843a,
			CardIds.Reforestation_EDR_843,
			CardIds.Reforestation_ReforestationToken_EDR_843t1,
			CardIds.RefreshingSpringWater,
			CardIds.Rewind_ETC_532,
			CardIds.RhoninsScryingOrbTavernBrawl,
			CardIds.RimefangSwordCore,
			CardIds.RimefangSword_LEG_RLK_710,
			CardIds.RimescaleSiren,
			CardIds.Rimetongue,
			CardIds.RingOfRefreshmentTavernBrawl,
			CardIds.RitualOfTheNewMoon_EDR_461,
			CardIds.RobeOfTheApprenticeTavernBrawl,
			CardIds.RobeOfTheMagi,
			CardIds.RobesOfShrinkingTavernBrawl,
			CardIds.RuleModifier_SpreadOfCorruptionToken_TTN_002t45,
			CardIds.RuneDagger,
			CardIds.SaroniteShambler_YOG_521,
			CardIds.SaygeSeerOfDarkmoon,
			CardIds.ScorchingWinds_FIR_910,
			CardIds.Scorchreaver_FIR_952,
			CardIds.ScrollSavvy,
			CardIds.SecretkeeperLegacy,
			CardIds.SecretkeeperVanilla,
			CardIds.ShadowOfDemise,
			CardIds.ShadowVisions,
			CardIds.Shadowborn,
			CardIds.ShadowclothNeedle,
			CardIds.ShatariCloakfield_GDB_103,
			CardIds.SheldrasMoontree,
			CardIds.ShieldBattery_SC_759,
			CardIds.ShimmeringSunfish,
			CardIds.ShirvallahTheTiger,
			CardIds.ShiveringSorceress,
			CardIds.Sif,
			CardIds.SilvermoonFarstrider_RLK_826,
			CardIds.SkulkingGeist_CORE_ICC_701,
			CardIds.SkulkingGeist_ICC_701,
			CardIds.SlitheringDeathscale,
			CardIds.SparkjoyCheat,
			CardIds.SpectralTrainee,
			CardIds.Spellcoiler,
			CardIds.SpiritGuide,
			CardIds.SpiritGuide_CORE_AV_328,
			CardIds.SpitefulSummoner,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.StaffOfPainTavernBrawl,
			CardIds.StarlightGroove,
			CardIds.StarlightReactor_GDB_108,
			CardIds.Starscryer,
			CardIds.StarstrungBow,
			CardIds.SteamGuardian,
			CardIds.SunfuryChampion,
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.SunstridersCrownTavernBrawl,
			CardIds.Surfalopod_VAC_443,
			CardIds.SwiftscaleTrickster,
			CardIds.TalentedArcanist,
			CardIds.TamsinRoame_BAR_918,
			CardIds.TangledWrath,
			CardIds.TheFistOfRaDen,
			CardIds.TheGardensGrace,
			CardIds.TheStoneOfJordanTavernBrawlToken,
			CardIds.TheUpperHand,
			CardIds.Thoribelore,
			CardIds.ThriveInTheShadowsCore,
			CardIds.TidePools_VAC_522,
			CardIds.TidepoolPupil_VAC_304,
			CardIds.ToadOfTheWilds,
			CardIds.TopiorTheShrubbagazzor,
			CardIds.TortollanPilgrim,
			CardIds.Triangulate_GDB_451,
			CardIds.TrolleyProblem_WW_436,
			CardIds.TwinbowTerrorcoil,
			CardIds.Tyrande_EDR_464,
			CardIds.UnderTheSea_VAC_431,
			CardIds.UngoroBrochure_DalaranBrochureToken_WORK_050t,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.UrchinSpines,
			CardIds.Ursol_EDR_259,
			CardIds.VelensChosen,
			CardIds.VeteranWarmedic,
			CardIds.Vexallus,
			CardIds.ViciousSlitherspear_CORE_TSC_827,
			CardIds.ViciousSlitherspear_TSC_827,
			CardIds.VoidFlayer,
			CardIds.VolumeUp,
			CardIds.WeaverOfTheCycle_EDR_472,
			CardIds.Whirlweaver,
			CardIds.WickedWitchdoctor,
			CardIds.WickedWitchdoctor_WON_083,
			CardIds.WildPyromancerCore,
			CardIds.WildPyromancerLegacy,
			CardIds.WildPyromancerVanilla,
			CardIds.WisdomOfNorgannon,
			CardIds.WishOfTheNewMoon_EDR_460,
			CardIds.WitherTheWeakTavernBrawl,
			CardIds.YoggSaronHopesEnd_OG_134,
			CardIds.YoggSaronMasterOfFate
		);
	}

	// Return combined selector if any matches found
	if (matchingCardIds.length > 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(...matchingCardIds));
	}
	return null;
};