/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings.ts
 * GENERAL REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseGeneralSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	const matchingCardIds: CardIds[] = [];

	// COST_LESS_4 + MINION + NEUTRAL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		matchingCardIds.push(
			CardIds.WarCommandsTavernBrawl
		);
	}

	// BEAST + COST_LESS_4 (1 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 4) {
		matchingCardIds.push(
			CardIds.TrialOfTheJormungars_WON_028
		);
	}

	// BEAST + COST_LESS_6 (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 6) {
		matchingCardIds.push(
			CardIds.GuardianAnimals,
			CardIds.PetCollector
		);
	}

	// COST_EQUAL_1 + MINION (4 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.ApothecarysCaravan,
			CardIds.BoogieDown,
			CardIds.K90tron,
			CardIds.TrustyFishingRod_VAC_960
		);
	}

	// COST_EQUAL_1 + SPELL (1 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.TrinketTracker
		);
	}

	// COST_EQUAL_2 + SPELL (2 cards)
	if (refCard.cost === 2 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551
		);
	}

	// COST_EQUAL_8 + MINION (2 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.JuicyPsychmelon,
			CardIds.SilverVanguard
		);
	}

	// COST_EQUAL_8 + SPELL (1 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.ArcaneBrilliance
		);
	}

	// COST_LESS_3 + MINION (2 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.CallToArms,
			CardIds.OracleOfElune
		);
	}

	// COST_LESS_3 + SPELL (1 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.VioletTreasuregill_TLC_438
		);
	}

	// COST_LESS_4 + MINION (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.AnimateDead
		);
	}

	// COST_LESS_4 + SPELL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.StonehearthVindicator
		);
	}

	// COST_LESS_5 + MINION (3 cards)
	if (refCard.cost < 5 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.GrizzledGuardian,
			CardIds.OakenSummons,
			CardIds.OakenSummons_CORE_LOOT_309
		);
	}

	// COST_MORE_0 + MINION (1 cards)
	if (refCard.cost > 0 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.Rally
		);
	}

	// COST_MORE_1 + SPELL (1 cards)
	if (refCard.cost > 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.PlaguebringerTavernBrawl
		);
	}

	// COST_MORE_4 + MINION (1 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.CaricatureArtist_TOY_391
		);
	}

	// COST_MORE_4 + SPELL (1 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.HagathaTheFabled_TOY_504
		);
	}

	// LEGENDARY + MINION (2 cards)
	if (refCard.rarity?.toUpperCase() === 'LEGENDARY' && refCard.type?.toUpperCase() === 'MINION') {
		matchingCardIds.push(
			CardIds.InspiringPresenceTavernBrawl,
			CardIds.RoyalGreatswordTavernBrawlToken
		);
	}

	// MINION + NEUTRAL (1 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		matchingCardIds.push(
			CardIds.MulchMadnessTavernBrawl
		);
	}

	// COST_EQUAL_1 (7 cards)
	if (refCard.cost === 1) {
		matchingCardIds.push(
			CardIds.Gazlowe,
			CardIds.NiriOfTheCrater_TLC_836,
			CardIds.PipThePotent_WW_394,
			CardIds.PrinceLiam,
			CardIds.RollingStone,
			CardIds.SonyaWaterdancer_TOY_515,
			CardIds.ThirstyDrifter_WW_387
		);
	}

	// COST_EQUAL_2 (1 cards)
	if (refCard.cost === 2) {
		matchingCardIds.push(
			CardIds.GreedyPartner_WW_901
		);
	}

	// COST_EQUAL_3 (1 cards)
	if (refCard.cost === 3) {
		matchingCardIds.push(
			CardIds.LinedancePartner_WW_433
		);
	}

	// COST_EQUAL_4 (1 cards)
	if (refCard.cost === 4) {
		matchingCardIds.push(
			CardIds.RowdyPartner_WW_906
		);
	}

	// COST_LESS_3 (3 cards)
	if (refCard.cost < 3) {
		matchingCardIds.push(
			CardIds.BandOfBeesTavernBrawl,
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.UnendingSwarm
		);
	}

	// COST_LESS_4 (3 cards)
	if (refCard.cost < 4) {
		matchingCardIds.push(
			CardIds.DreadRaptor_TLC_432,
			CardIds.Razorboar,
			CardIds.Resuscitate_TLC_818
		);
	}

	// COST_LESS_5 (2 cards)
	if (refCard.cost < 5) {
		matchingCardIds.push(
			CardIds.Hybridization_TLC_236,
			CardIds.RazorfenBeastmaster
		);
	}

	// COST_MORE_0 (2 cards)
	if (refCard.cost > 0) {
		matchingCardIds.push(
			CardIds.Resuscitate_TLC_818,
			CardIds.TamsinRoame_BAR_918
		);
	}

	// COST_MORE_1 (1 cards)
	if (refCard.cost > 1) {
		matchingCardIds.push(
			CardIds.TaethelanBloodwatcher_WW_430
		);
	}

	// COST_MORE_2 (2 cards)
	if (refCard.cost > 2) {
		matchingCardIds.push(
			CardIds.AllTogetherNowTavernBrawl,
			CardIds.OrbOfRevelationTavernBrawl
		);
	}

	// COST_MORE_3 (1 cards)
	if (refCard.cost > 3) {
		matchingCardIds.push(
			CardIds.HemetJungleHunter
		);
	}

	// COST_MORE_4 (6 cards)
	if (refCard.cost > 4) {
		matchingCardIds.push(
			CardIds.AshleafPixie_FIR_961,
			CardIds.FerociousFelbat_EDR_892,
			CardIds.Groundskeeper,
			CardIds.InventorBoom_TOY_607,
			CardIds.StranglethornHeart,
			CardIds.TimberTambourine
		);
	}

	// COST_MORE_5 (3 cards)
	if (refCard.cost > 5) {
		matchingCardIds.push(
			CardIds.GreySageParrot,
			CardIds.ScepterOfSummoning,
			CardIds.SummerFlowerchild
		);
	}

	// COST_MORE_7 (1 cards)
	if (refCard.cost > 7) {
		matchingCardIds.push(
			CardIds.FlamesOfTheFirelord_FIR_923
		);
	}

	// LEGENDARY (4 cards)
	if (refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		matchingCardIds.push(
			CardIds.AlakirTheWindlord_ElementalEvocation_THD_026p,
			CardIds.ArchVillainRafaam_BeholdMyStuff_THD_032p,
			CardIds.DisksOfLegendTavernBrawl,
			CardIds.RingOfPhaseshiftingTavernBrawl
		);
	}

	// LOCATION (2 cards)
	if (refCard.type?.toUpperCase() === 'LOCATION') {
		matchingCardIds.push(
			CardIds.DispossessedSoul,
			CardIds.DispossessedSoul_CORE_REV_901
		);
	}

	// NEUTRAL (5 cards)
	if (refCard.classes?.includes('NEUTRAL')) {
		matchingCardIds.push(
			CardIds.ClassActionLawyer,
			CardIds.EnvoyOfTheGlade_EDR_873,
			CardIds.MeekMasteryTavernBrawl,
			CardIds.TheCountess,
			CardIds.WyrmrestPurifier
		);
	}

	// WEAPON (38 cards)
	if (refCard.type?.toUpperCase() === 'WEAPON') {
		matchingCardIds.push(
			CardIds.AbyssalBassist,
			CardIds.AirGuitarist,
			CardIds.AxeBerserker,
			CardIds.BargainBin_MIS_105,
			CardIds.BlackscaleBrute,
			CardIds.CorsairCache,
			CardIds.FogsailFreebooterCore,
			CardIds.ForgedInFlame,
			CardIds.GrimtotemBuzzkill,
			CardIds.GrommashsArmguardsTavernBrawl,
			CardIds.GuitarSoloist,
			CardIds.InstrumentSmasher,
			CardIds.InstrumentTech,
			CardIds.Khazgoroth,
			CardIds.Khazgoroth_TitanforgeToken,
			CardIds.LadyAshvane_Story_11_LadyAshvane,
			CardIds.LadyAshvane_TSC_943,
			CardIds.ManAtArms,
			CardIds.Obsidiansmith,
			CardIds.PillageTheFallenTavernBrawl,
			CardIds.Plunder,
			CardIds.RaidTheDocks,
			CardIds.RatchetPrivateer,
			CardIds.RuneforgingCore,
			CardIds.Runeforging_LEG_RLK_715,
			CardIds.SelflessSidekick,
			CardIds.ShadestoneSkulker_DEEP_012,
			CardIds.SharpShipment_WORK_005,
			CardIds.SmallTimeBuccaneer,
			CardIds.SmallTimeBuccaneer_WON_351,
			CardIds.SouthseaDeckhandLegacy,
			CardIds.SouthseaDeckhandVanilla,
			CardIds.SouthseaDeckhand_CORE_CS2_146,
			CardIds.SpacePirate_GDB_333,
			CardIds.SwarthySwordshiner_VAC_701,
			CardIds.VulperaToxinblade,
			CardIds.WeaponsAttendant_VAC_924,
			CardIds.WeaponsExpert
		);
	}

	// Return combined selector if any matches found
	if (matchingCardIds.length > 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(...matchingCardIds));
	}
	return null;
};