/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings.ts
 * Run: npm run build:reverse-synergies to update
 * SPELL-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseSpellSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	// Spell school reverse synergies
	if (refCard.spellSchool && refCard.type?.toUpperCase() === 'SPELL') {
	}

	// Spell-specific complex conditions
	// type:spell+cost:equal:7 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost === 7) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// type:spell+cost:more:4 (3 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost > 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AshleafPixie_FIR_961,
			CardIds.Groundskeeper,
			CardIds.HagathaTheFabled_TOY_504
		));
	}

	// type:spell+cost:equal:1 (3 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost === 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_CORE_BAR_551,
			CardIds.Gazlowe,
			CardIds.TrinketTracker
		));
	}

	// school:frost+other:dealsDamage (1 card)
	if (refCard.spellSchool?.toUpperCase() === 'FROST' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BitterColdTavernBrawl
		));
	}

	// type:spell+cost:costMore:4 (3 cards)
	if (refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BumblingBellhop_VAC_521,
			CardIds.FaeTrickster_EDR_571,
			CardIds.WeaverOfTheCycle_EDR_472
		));
	}

	// school:holy+type:spell (15 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'HOLY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CarielRoame_BAR_902,
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.GuardianLightTavernBrawl,
			CardIds.HeraldOfLight,
			CardIds.HiHoSilverwing_WW_344,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.InvigoratingLightTavernBrawl,
			CardIds.KnightOfAnointment,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ShimmeringSunfish,
			CardIds.StarlightGroove,
			CardIds.TheGardensGrace,
			CardIds.VeteranWarmedic
		));
	}

	// tribe:naga+type:spell (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.races?.map(r => r.toUpperCase()).includes('NAGA')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ConchsCall
		));
	}

	// school:nature+type:spell (11 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'NATURE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DeviateDreadfang,
			CardIds.GroveShaper_EDR_271,
			CardIds.GuffRunetotem_BAR_720,
			CardIds.HeraldOfNature,
			CardIds.IronRootsTavernBrawl,
			CardIds.LadyAnacondra_WC_006,
			CardIds.MendingPoolsTavernBrawl,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.ToadOfTheWilds,
			CardIds.TopiorTheShrubbagazzor,
			CardIds.WidowbloomSeedsman
		));
	}

	// school:shadow+type:spell (10 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.EerieStoneTavernBrawl,
			CardIds.HeraldOfShadows,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.LadyDarkvein_CORE_REV_373,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.Shadowborn,
			CardIds.ShadowclothNeedle,
			CardIds.SketchArtist_TOY_916,
			CardIds.StaffOfPainTavernBrawl,
			CardIds.TwilightDeceptor
		));
	}

	// school:fel+type:spell (10 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'FEL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FelfireBlaze_FIR_904,
			CardIds.Felgorger_SW_043,
			CardIds.FossilFanatic,
			CardIds.GraveDefiler,
			CardIds.HeraldOfChaos,
			CardIds.IllidanStormrage_FelInside_THD_004p,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.Scorchreaver_FIR_952,
			CardIds.WitherTheWeakTavernBrawl
		));
	}

	// school:fire+type:spell (11 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'FIRE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FirekeepersIdolTavernBrawl,
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.HotStreak,
			CardIds.InfernoHerald_FIR_913,
			CardIds.LivingFlame_FIR_929,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.ScorchingWinds_FIR_910,
			CardIds.SunfuryChampion,
			CardIds.Thoribelore,
			CardIds.VolcanicThrasher_TLC_223
		));
	}

	// school:frost+type:spell (8 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'FROST') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.HarbingerOfWinterCore_RLK_511,
			CardIds.HeraldOfLokholar,
			CardIds.IceRevenant,
			CardIds.LadyDeathwhisper_RLK_713,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.Rimetongue,
			CardIds.WatercolorArtist_TOY_376
		));
	}

	// type:spell+cost:more:5 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost > 5) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GreySageParrot
		));
	}

	// school:arcane+type:spell (7 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'ARCANE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.HalduronBrightwing,
			CardIds.MagistersApprentice,
			CardIds.SilvermoonFarstrider_RLK_826,
			CardIds.Stargazing_WW_425,
			CardIds.StarlightReactor_GDB_108,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.Vexallus
		));
	}

	// type:spell+other:hasSpellSchool (2 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && !!refCard.spellSchool) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.MagisterDawngrasp_AV_200,
			CardIds.RazzleDazzler_VAC_301
		));
	}

	// type:spell+mechanics:chooseOne (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JerryRigCarpenter
		));
	}

	// school:fire+type:spell+other:dealsDamage (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'FIRE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.KindlingFlameTavernBrawl
		));
	}

	// school:nature+type:spell+other:dealsDamage (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'NATURE') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.NaturalForceTavernBrawl
		));
	}

	// type:spell+mechanics:discover+cost:more:2 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost > 2) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.OrbOfRevelationTavernBrawl
		));
	}

	// type:spell+cost:more:1 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost > 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.PlaguebringerTavernBrawl
		));
	}

	// type:spell+cost:baseEqual:1 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost === 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SkulkingGeist_ICC_701
		));
	}

	// type:spell+mechanics:secret (3 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.mechanics?.includes('SECRET')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SecretkeeperLegacy,
			CardIds.SrTombDiverTavernBrawl,
			CardIds.SwordOfTheFallen
		));
	}

	// type:spell+cost:less:4 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.StonehearthVindicator
		));
	}

	// type:spell+cost:less:3 (2 cards)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.cost < 3) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.VioletTreasuregill_TLC_438
		));
	}

	// school:shadow+type:spell+cost:more:0 (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.cost > 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TamsinRoame_BAR_918
		));
	}

	return null;
};