/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings.ts
 * Run: npm run build:reverse-synergies to update
 * MINION-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseMinionSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	// Race-based reverse synergies
	if (refCard.races?.length) {
		if (refCard.races.map(r => r.toUpperCase()).includes('UNDEAD')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AcolyteOfDeath_CORE_RLK_121,
			CardIds.AmateurPuppeteer_AmateurPuppeteerToken_TOY_828t,
			CardIds.ArmsDealer_RLK_824,
			CardIds.Banshee_RLK_957,
			CardIds.BoneFlinger,
			CardIds.Bonecaller,
			CardIds.DeadAir,
			CardIds.DrakkariEmbalmer_RLK_119,
			CardIds.ElderNadox,
			CardIds.FleshBehemoth_RLK_Prologue_RLK_830,
			CardIds.GluthSicleTavernBrawl,
			CardIds.GluthTavernBrawl_PVPDR_Sai_T1,
			CardIds.GraveDigging,
			CardIds.Invincible,
			CardIds.LesserSpinelSpellstone_GreaterSpinelSpellstoneToken_TOY_825t2,
			CardIds.NecroticMortician_CORE_RLK_116,
			CardIds.NerubianVizier,
			CardIds.NoxiousInfiltrator,
			CardIds.PoisonBreath_CORE_EDR_002,
			CardIds.RottingNecromancer,
			CardIds.ShadowWordUndeath,
			CardIds.SicklyGrimewalker_YOG_512,
			CardIds.SkeletalSidekickCore_RLK_958,
			CardIds.SoulburnerVaria_YOG_520,
			CardIds.TwistedTether,
			CardIds.UndyingAllies,
			CardIds.UnlivingChampion,
			CardIds.Wither
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('BEAST')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AddledGrizzly_WON_009,
			CardIds.AzsharanSaber_SunkenSaberToken,
			CardIds.BigDreams,
			CardIds.BunnyStomper_WW_435,
			CardIds.ButchTavernBrawl,
			CardIds.CallPet_GVG_017,
			CardIds.CastleKennels_REV_790,
			CardIds.CattleRustler_WW_351,
			CardIds.CowerInFear_TLC_823,
			CardIds.Dinositter_TLC_822,
			CardIds.ExoticHoundmaster_EDR_226,
			CardIds.FaithfulCompanions,
			CardIds.FangboundDruid,
			CardIds.Goldrinn_EDR_480,
			CardIds.HarpoonGun,
			CardIds.HemetFoamMarksman_TOY_355,
			CardIds.HerbivoreAssistant_DINO_419,
			CardIds.JungleGym_TOY_359,
			CardIds.KathrenaWinterwisp,
			CardIds.KingOfBeasts_WON_162,
			CardIds.KnightOfTheWild_WON_003,
			CardIds.LivingSeedRank1_LivingSeedRank3Token,
			CardIds.Malorne_WON_011,
			CardIds.MenagerieWarden_WON_305,
			CardIds.MessengerBuzzard_WW_807,
			CardIds.MysteryEgg_MysteryEggToken_TOY_351t,
			CardIds.Oondasta,
			CardIds.PaintedCanvasaur_TOY_350,
			CardIds.PeacefulPiper,
			CardIds.PeacefulPiper_FriendlyFace,
			CardIds.PossessedAnimancer_DINO_131,
			CardIds.PredatoryInstincts,
			CardIds.RamkahenWildtamer,
			CardIds.RoostingGargoyle_CORE_REV_351,
			CardIds.ScavengersIngenuity,
			CardIds.ScrapShot,
			CardIds.SelectiveBreederCore,
			CardIds.Serpentbloom,
			CardIds.Shadehound,
			CardIds.ShandoWildclaw_Transfiguration,
			CardIds.StarvingTavernBrawl,
			CardIds.StormpikeBattleRam,
			CardIds.SupremeDinomancy_TLC_828,
			CardIds.TavishStormpike_BAR_038,
			CardIds.TendingDragonkin_FIR_960,
			CardIds.ThornmantleMusician,
			CardIds.Thunderbringer_WW_440,
			CardIds.VirmenSensei_WON_300,
			CardIds.WarsongWrangler,
			CardIds.WingCommanderIchman_AV_336,
			CardIds.WitchingHour
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('PIRATE')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AdrenalineFiend_VAC_927,
			CardIds.Ancharrr,
			CardIds.BeckoningBicornTavernBrawl,
			CardIds.CannonBarrage,
			CardIds.CaptainsParrotVanilla,
			CardIds.CutlassCourier,
			CardIds.HarborScamp,
			CardIds.HozenRoughhouser_VAC_938,
			CardIds.PatchesThePirate_CFM_637,
			CardIds.PatchesThePirate_LockedAndLoaded_THD_025p,
			CardIds.PirateAdmiralHooktusk,
			CardIds.SailboatCaptain_VAC_937,
			CardIds.ShadyDealer,
			CardIds.SharkPuncher_WON_138,
			CardIds.ShipsCannon,
			CardIds.ShoplifterGoldbeard_TOY_511,
			CardIds.Swordfish,
			CardIds.TreasureDistributor_TOY_518
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('DEMON')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AllShallServeTavernBrawl,
			CardIds.BlackHole_GDB_126,
			CardIds.BloodreaverGuldan_ICC_831,
			CardIds.CariaFelsoul,
			CardIds.CraneGame_TOY_884,
			CardIds.Demonfuse_DarkFusionEnchantment,
			CardIds.Felosophy,
			CardIds.GameMasterNemsy_TOY_524,
			CardIds.InfernalStratagem_GDB_122,
			CardIds.Malganis_GVG_021,
			CardIds.PitCommander,
			CardIds.RagingFelscreamer_BT_416,
			CardIds.SenseDemonsVanilla_VAN_EX1_317,
			CardIds.SigilOfReckoning,
			CardIds.TabletopRoleplayer_TOY_915,
			CardIds.UmpiresGrasp_TOY_641,
			CardIds.VoidcallerCore
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('DRAGON')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AmberWhelp,
			CardIds.BlackwingCorruptor_WON_329,
			CardIds.BreathOfDreams,
			CardIds.BroodKeeper_EDR_457,
			CardIds.CandleBreath,
			CardIds.Chillmaw_CORE_AT_123,
			CardIds.CloudSerpent_TLC_888,
			CardIds.ClutchOfCorruption_EDR_454,
			CardIds.DaringDrake,
			CardIds.Darkrider_EDR_456,
			CardIds.DesertNestmatron_WW_826,
			CardIds.DraconicDreamTavernBrawl,
			CardIds.DragonAffinityTavernBrawl,
			CardIds.DragonBreeder,
			CardIds.DragonConsort,
			CardIds.DragonGolem_WW_822,
			CardIds.DragonbloodTavernBrawl,
			CardIds.DragonboneRitualTavernBrawl,
			CardIds.Dragoncaster,
			CardIds.DrakonidOperativeCore,
			CardIds.FlyOffTheShelves_TOY_714,
			CardIds.FrizzKindleroost,
			CardIds.FutureEmissary_WON_140,
			CardIds.GiftwrappedWhelp_TOY_386,
			CardIds.HeraldOfFlame_TRLA_176,
			CardIds.HornOfWrathion,
			CardIds.Kazakusan_ONY_005,
			CardIds.MalygosAspectOfMagic,
			CardIds.NaralexHeraldOfTheFlights_EDR_844,
			CardIds.NetherBreath_DRG_205,
			CardIds.OnyxianWarder,
			CardIds.PetalPeddler_EDR_889,
			CardIds.RedscaleDragontamer_CORE_DMF_194,
			CardIds.ScaleReplica_TOY_387,
			CardIds.Scalerider,
			CardIds.Scaleworm,
			CardIds.Skyfin,
			CardIds.Soridormi_WON_146,
			CardIds.SpinetailDrake_WW_820,
			CardIds.SplishSplashWhelp_WW_819,
			CardIds.Stormhammer,
			CardIds.SuccumbToMadness_EDR_455,
			CardIds.TakeToTheSkies_WW_816,
			CardIds.TastyFlyfish,
			CardIds.Timewarden,
			CardIds.TimewinderZarimi_TOY_385,
			CardIds.TormentedDreadwing_EDR_572,
			CardIds.TwilightGuardian,
			CardIds.WingCommander
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('ELEMENTAL')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AnimatedAvalanche,
			CardIds.AquaArchivist,
			CardIds.AridStormer,
			CardIds.AzeriteGiant_WW_025,
			CardIds.Blazecaller,
			CardIds.BralmaSearstone_TLC_228,
			CardIds.DangBlastedElemental_WW_397,
			CardIds.ElementalEvocation,
			CardIds.ElementaryReaction,
			CardIds.ErodedSediment_WW_428,
			CardIds.FireBreath_DINO_406,
			CardIds.FirePlumeHarbinger,
			CardIds.FlameRevenant,
			CardIds.FrostLichJaina_CORE_ICC_833,
			CardIds.FrostfinChomper,
			CardIds.GraniteForgeborn,
			CardIds.Gyreworm,
			CardIds.KalimosPrimalLord_Core_UNG_211,
			CardIds.KindlingElemental,
			CardIds.Lamplighter_VAC_442,
			CardIds.LilypadLurker,
			CardIds.LivingPrairie_WW_024,
			CardIds.MesaduneTheFractured_WW_429,
			CardIds.MinecartCruiser_WW_326,
			CardIds.OverflowSurger_WW_424,
			CardIds.Sandbinder,
			CardIds.ShaleSpider_DEEP_034,
			CardIds.SkarrTheCatastrophe_WW_026,
			CardIds.SolarFlare_GDB_305,
			CardIds.SpontaneousCombustion_GDB_456,
			CardIds.SteamSurger,
			CardIds.StoneSentinel,
			CardIds.TaintedRemnant_YOG_519,
			CardIds.Therazane_DEEP_036,
			CardIds.UnchainedGladiator,
			CardIds.WailingVapor_CORE_WC_042,
			CardIds.WindsweptPageturner_TLC_220
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('MURLOC')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.AzsharanScavenger_SunkenScavengerToken,
			CardIds.Braingill_GDB_878,
			CardIds.CookiesLadleTavernBrawl,
			CardIds.DiveTheGolakkaDepths_TLC_426,
			CardIds.FinjaTheFlyingStar_CORE_CFM_344,
			CardIds.FiremancerFlurgl,
			CardIds.GorlocRavager,
			CardIds.HotSpringGlider_TLC_428,
			CardIds.IceFishing_ICC_089,
			CardIds.ItsRainingFin,
			CardIds.LushwaterScout,
			CardIds.SirFinleyMrrgglton_ScalesOfJustice_THD_044p,
			CardIds.TidelostBurrower,
			CardIds.TinyfinsCaravan,
			CardIds.UnderbellyAngler
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('NAGA')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.BarbedNets,
			CardIds.CoilCastingTavernBrawl,
			CardIds.NagasPride,
			CardIds.OasisOutlaws_WW_404,
			CardIds.Predation,
			CardIds.SeaweedStrike,
			CardIds.SerpentWig_TSC_215
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('MECH')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.Bubblebot_TSC_059,
			CardIds.ClickClocker,
			CardIds.ClockworkKnight,
			CardIds.DrBoomMadGenius,
			CardIds.DrBoom_BoomBarrage_THD_034p,
			CardIds.DynOMaticCore,
			CardIds.FrequencyOscillator,
			CardIds.GaiaTheTechtonic_TSC_029,
			CardIds.GoboglideTech,
			CardIds.IniStormcoil_TSC_649,
			CardIds.InventorsAura,
			CardIds.KangorsEndlessArmy,
			CardIds.MechaShark_TSC_054,
			CardIds.MimironTheMastermind,
			CardIds.PitStop,
			CardIds.RadarDetector_TSC_079,
			CardIds.SeafloorGateway_TSC_055,
			CardIds.SeascoutOperator_TSC_646,
			CardIds.SecurityAutomaton_TSC_928,
			CardIds.SootSpewer_WON_033,
			CardIds.TimelineAccelerator_WON_139,
			CardIds.TinyWorldbreaker_YOG_527,
			CardIds.TramOperator,
			CardIds.TrenchSurveyor_TSC_642,
			CardIds.Ursatron,
			CardIds.WreckemAndDeckem_TOY_603
			));
		}
		if (refCard.races.map(r => r.toUpperCase()).includes('TOTEM')) {
			return and(side(inputSide), or(inDeck, inHand), cardIs(
				CardIds.DraeneiTotemcarver_CORE_AT_047,
			CardIds.Gigantotem,
			CardIds.SplittingAxe,
			CardIds.TheStonewright,
			CardIds.ThingFromBelowCore
			));
		}
	}

	// Minion-specific complex conditions
	// tribe:beast+type:minion (3 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('BEAST')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AbsorbentParasite,
			CardIds.Banjosaur,
			CardIds.TheCurator_CORE_KAR_061
		));
	}

	// type:minion+mechanics:rush (9 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.mechanics?.includes('RUSH')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AkaliTheRhino,
			CardIds.ClearTheWay,
			CardIds.DivingGryphon,
			CardIds.PotionOfSparkingTavernBrawl,
			CardIds.RocketBackpacksTavernBrawl,
			CardIds.RushTheStage,
			CardIds.SpecialDeliveryTavernBrawl,
			CardIds.StageDive_StageDive,
			CardIds.TownCrier_CORE_GIL_580
		));
	}

	// type:minion+other:tribeless (11 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && !refCard.races || refCard.races.length === 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AllYouCanEat_VAC_528,
			CardIds.AmalgamOfTheDeep,
			CardIds.FlightOfTheFirehawk_TLC_222,
			CardIds.MenagerieMug_CORE_WON_141,
			CardIds.PartyAnimal,
			CardIds.RoaringApplause,
			CardIds.RockMasterVoone_ETC_121,
			CardIds.SpiritOfTheMountain_TLC_229,
			CardIds.ThePurator,
			CardIds.TortollanStoryteller_TLC_254,
			CardIds.TrustyCompanion_WW_027
		));
	}

	// tribe:undead+type:minion (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('UNDEAD')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AmorphousSlime,
			CardIds.SinisterSoulcage_YOG_513
		));
	}

	// type:minion+mechanics:deathrattle (35 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AmuletOfUndying,
			CardIds.ArchdruidOfThorns_EDR_491,
			CardIds.AwakenTheMakers,
			CardIds.BrittleboneBuccaneer_VAC_436,
			CardIds.CarrionStudies,
			CardIds.DeadRinger,
			CardIds.DeathBlossomWhomper,
			CardIds.DeathGrowl,
			CardIds.DeathlyDeathTavernBrawl,
			CardIds.DeathstriderTavernBrawl,
			CardIds.DevoutBlessingsTavernBrawlToken,
			CardIds.ExpeditedBurialTavernBrawl,
			CardIds.FelfireBonfire_VAC_952,
			CardIds.ForsakenLieutenant_AV_601,
			CardIds.HedgeMaze_REV_792,
			CardIds.HighCultistHerenn_TLC_810,
			CardIds.JewelOfNzoth,
			CardIds.MummyMagic,
			CardIds.NecriumApothecary,
			CardIds.NineLives,
			CardIds.NzothTheCorruptor,
			CardIds.NzothTheCorruptor_DarkMachinations_THD_039p,
			CardIds.PrincessTavernBrawl,
			CardIds.RavenousFelhunter_EDR_891,
			CardIds.ScourgeIllusionist,
			CardIds.Shattershambler,
			CardIds.TamsinsPhylactery,
			CardIds.TerrorscaleStalker_CORE_UNG_800,
			CardIds.TombLurker_ICC_098,
			CardIds.Tuskpiercer_CORE_BAR_330,
			CardIds.TwilightsCall,
			CardIds.UnearthedRaptor,
			CardIds.VengefulSpirit_BAR_328,
			CardIds.XyrellaTheDevout,
			CardIds.YellingYodeler
		));
	}

	// type:minion+cost:less:4 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AnimateDead
		));
	}

	// type:minion+cost:equal:1 (5 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost === 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ApothecarysCaravan,
			CardIds.BoogieDown,
			CardIds.K90tron,
			CardIds.SonyaWaterdancer_TOY_515,
			CardIds.TrustyFishingRod_VAC_960
		));
	}

	// tribe:demon+other:notInInitialDeck (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('DEMON')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Archimonde_GDB_128,
			CardIds.ForebodingFlame_GDB_121
		));
	}

	// type:minion+mechanics:battlecry (7 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.mechanics?.includes('BATTLECRY')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AuctionhouseGavel,
			CardIds.BrannBronzebeard_BrannsSaddle_THD_042p,
			CardIds.FairyTaleForest_TOY_507,
			CardIds.Murmur_GDB_448,
			CardIds.ParrotSanctuary_VAC_409,
			CardIds.Snapdragon,
			CardIds.Turbulus_WORK_013
		));
	}

	// type:minion+cost:less:3 (3 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 3) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BandOfBeesTavernBrawl,
			CardIds.CallToArms,
			CardIds.OracleOfElune
		));
	}

	// type:minion+mechanics:taunt (12 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.mechanics?.includes('TAUNT')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Battlepickaxe_WW_347,
			CardIds.Bolster,
			CardIds.BulkUp,
			CardIds.DetonationJuggernaut_WW_329,
			CardIds.EnduranceTrainingTavernBrawl,
			CardIds.FirePlumesHeart,
			CardIds.IntoTheFray,
			CardIds.QualityAssurance_TOY_605,
			CardIds.RazormaneBattleguard,
			CardIds.TortollanTraveler_VAC_518,
			CardIds.UnluckyPowderman_WW_367,
			CardIds.ValstannStaghelm_WON_345
		));
	}

	// tribe:mech+mechanics:deathrattle (1 card)
	if (refCard.races?.map(r => r.toUpperCase()).includes('MECH') && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BoomWrench_BoomWrenchToken_TOY_604t
		));
	}

	// type:minion+attack:equal:1 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack === 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BusyBot_WORK_002
		));
	}

	// type:minion+cost:more:4 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost > 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CaricatureArtist_TOY_391
		));
	}

	// type:minion+attack:greater:4 (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack > 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ClimbingHook_VAC_932,
			CardIds.GiantAnaconda
		));
	}

	// tribe:dragon+type:minion (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('DRAGON')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CollectorsIreTavernBrawlToken,
			CardIds.DrocomurchanicasTavernBrawlToken
		));
	}

	// tribe:naga+type:spell (1 card)
	if (refCard.type?.toUpperCase() === 'SPELL' && refCard.races?.map(r => r.toUpperCase()).includes('NAGA')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ConchsCall
		));
	}

	// type:minion+attack:greater:0,less:2 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack > 0 && refCard.attack < 2) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Crystology
		));
	}

	// type:minion+mechanics:deathrattle+cost:less:6 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 6 && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DeathSpeakerBlackthorn_BAR_329
		));
	}

	// tribe:demon+type:minion (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('DEMON')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DirgeOfDespair,
			CardIds.KanrethadEbonlocke_KanrethadPrimeToken
		));
	}

	// type:minion+mechanics:legendary+other:legendary (4 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DisksOfLegendTavernBrawl,
			CardIds.InspiringPresenceTavernBrawl,
			CardIds.RingOfPhaseshiftingTavernBrawl,
			CardIds.RoyalGreatswordTavernBrawlToken
		));
	}

	// type:minion+mechanics:deathrattle+cost:less:4 (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 4 && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DreadRaptor_TLC_432,
			CardIds.Razorboar
		));
	}

	// tribe:elemental+mechanics:legendary+other:legendary (1 card)
	if (refCard.races?.map(r => r.toUpperCase()).includes('ELEMENTAL') && refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AlakirTheWindlord_ElementalEvocation_THD_026p
		));
	}

	// type:minion+mechanics:divineShield (3 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.mechanics?.includes('DIVINE_SHIELD')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FancyPackaging_TOY_881,
			CardIds.Funkfin,
			CardIds.RighteousReservesTavernBrawl
		));
	}

	// type:minion+mechanics:deathrattle+cost:more:4 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost > 4 && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FerociousFelbat_EDR_892
		));
	}

	// tribe:mech+type:minion (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('MECH')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GorillabotA3Core
		));
	}

	// type:minion+cost:less:5 (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 5) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GrizzledGuardian,
			CardIds.OakenSummons_CORE_LOOT_309
		));
	}

	// tribe:beast+cost:less:6 (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 6) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GuardianAnimals,
			CardIds.PetCollector
		));
	}

	// type:minion+attack:less:3 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack < 3) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.HatcheryHelper_TLC_233
		));
	}

	// type:minion+attack:equal:0 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack === 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.HolyEggbearer_DINO_411
		));
	}

	// type:minion+cost:less:5,more:0 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost > 0 && refCard.cost < 5) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Hybridization_TLC_236
		));
	}

	// type:minion+cost:equal:7 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost === 7) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// type:minion+attack:less:4 (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.attack < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.LeadDancer,
			CardIds.WarsongCommanderVanilla
		));
	}

	// type:minion+mechanics:combo (1 card)
	if (refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.LuckyComet_GDB_873
		));
	}

	// type:minion+cost:costMore:7 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Merithra_EDR_238
		));
	}

	// type:minion+other:neutral (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.MeekMasteryTavernBrawl,
			CardIds.MulchMadnessTavernBrawl
		));
	}

	// tribe:mech+mechanics:magnetic (1 card)
	if (refCard.races?.map(r => r.toUpperCase()).includes('MECH')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.OptimizedPolarityTavernBrawl
		));
	}

	// type:minion+cost:less:4,more:0 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost > 0 && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Rally
		));
	}

	// type:minion+mechanics:deathrattle+cost:less:5 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 5 && refCard.mechanics?.includes('DEATHRATTLE')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.RazorfenBeastmaster
		));
	}

	// type:minion+cost:costMore:6 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.RotheartDryad_EDR_485
		));
	}

	// type:minion+health:less:2 (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.health < 2) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SalhetsPride,
			CardIds.StewardOfDarkshire_WON_310
		));
	}

	// type:minion+cost:more:5 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost > 5) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ScepterOfSummoning
		));
	}

	// type:minion+cost:equal:8 (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost === 8) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SilverVanguard
		));
	}

	// tribe:totem+type:minion (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.races?.map(r => r.toUpperCase()).includes('TOTEM')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TotemicSurge
		));
	}

	// tribe:beast+cost:less:4 (1 card)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TrialOfTheJormungars_WON_028
		));
	}

	// type:minion+health:biggerThanAttack (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.health > refCard.attack) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.UnlockedPotential
		));
	}

	// type:minion+cost:less:4+other:neutral (1 card)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.cost < 4 && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.WarCommandsTavernBrawl
		));
	}

	return null;
};