/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings-v2.ts
 * GENERAL REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { DeckCard } from '@firestone/game-state';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseGeneralSelector = (
	cardId: string,
	card: DeckCard | undefined,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	// WEAPON (27 cards)
	if (refCard.type?.toUpperCase() === 'WEAPON') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AbyssalBassist,
			CardIds.AirGuitarist,
			CardIds.AxeBerserker,
			CardIds.BlackscaleBrute,
			CardIds.CorsairCache,
			CardIds.FogsailFreebooterCore,
			CardIds.ForgedInFlame,
			CardIds.GrimtotemBuzzkill,
			CardIds.GrommashsArmguardsTavernBrawl,
			CardIds.InstrumentSmasher,
			CardIds.InstrumentTech,
			CardIds.Khazgoroth_TitanforgeToken,
			CardIds.LadyAshvane_Story_11_LadyAshvane,
			CardIds.ManAtArms,
			CardIds.PillageTheFallenTavernBrawl,
			CardIds.Plunder,
			CardIds.RatchetPrivateer,
			CardIds.Runeforging_LEG_RLK_715,
			CardIds.SelflessSidekick,
			CardIds.ShadestoneSkulker_DEEP_012,
			CardIds.SharpShipment_WORK_005,
			CardIds.SmallTimeBuccaneer_WON_351,
			CardIds.SouthseaDeckhandVanilla,
			CardIds.SpacePirate_GDB_333,
			CardIds.SwarthySwordshiner_VAC_701,
			CardIds.VulperaToxinblade,
			CardIds.WeaponsExpert
		));
	}

	// COST_LESS_4 + MINION (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AnimateDead
		));
	}

	// COST_EQUAL_1 + MINION (5 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ApothecarysCaravan,
			CardIds.BoogieDown,
			CardIds.K90tron,
			CardIds.SonyaWaterdancer_TOY_515,
			CardIds.TrustyFishingRod_VAC_960
		));
	}

	// COST_EQUAL_7 + SPELL (1 cards)
	if (refCard.cost === 7 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_8 + SPELL (1 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_9 + SPELL (1 cards)
	if (refCard.cost === 9 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_EQUAL_10 + SPELL (1 cards)
	if (refCard.cost === 10 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArcaneBrilliance
		));
	}

	// COST_MORE_4 + SPELL (3 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AshleafPixie_FIR_961,
			CardIds.Groundskeeper,
			CardIds.HagathaTheFabled_TOY_504
		));
	}

	// COST_LESS_3 + MINION (3 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BandOfBeesTavernBrawl,
			CardIds.CallToArms,
			CardIds.OracleOfElune
		));
	}

	// COST_EQUAL_1 + SPELL (3 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_CORE_BAR_551,
			CardIds.Gazlowe,
			CardIds.TrinketTracker
		));
	}

	// COST_EQUAL_2 + SPELL (1 cards)
	if (refCard.cost === 2 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_CORE_BAR_551
		));
	}

	// COST_EQUAL_3 + SPELL (1 cards)
	if (refCard.cost === 3 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.BarakKodobane_CORE_BAR_551
		));
	}

	// LEGENDARY (2 cards)
	if (refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ArchVillainRafaam_BeholdMyStuff_THD_032p,
			CardIds.BountyBoard_WW_003
		));
	}

	// COST_MORE_4 + MINION (1 cards)
	if (refCard.cost > 4 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.CaricatureArtist_TOY_391
		));
	}

	// NEUTRAL (4 cards)
	if (refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ClassActionLawyer,
			CardIds.EnvoyOfTheGlade_EDR_873,
			CardIds.TheCountess,
			CardIds.WyrmrestPurifier
		));
	}

	// LEGENDARY + MINION (4 cards)
	if (refCard.rarity?.toUpperCase() === 'LEGENDARY' && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DisksOfLegendTavernBrawl,
			CardIds.InspiringPresenceTavernBrawl,
			CardIds.RingOfPhaseshiftingTavernBrawl,
			CardIds.RoyalGreatswordTavernBrawlToken
		));
	}

	// LOCATION (1 cards)
	if (refCard.type?.toUpperCase() === 'LOCATION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.DispossessedSoul_CORE_REV_901
		));
	}

	// ELEMENTAL + LEGENDARY (1 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('ELEMENTAL') && refCard.rarity?.toUpperCase() === 'LEGENDARY') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.AlakirTheWindlord_ElementalEvocation_THD_026p
		));
	}

	// COST_MORE_7 (1 cards)
	if (refCard.cost > 7) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.FlamesOfTheFirelord_FIR_923
		));
	}

	// COST_EQUAL_2 (1 cards)
	if (refCard.cost === 2) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GreedyPartner_WW_901
		));
	}

	// COST_MORE_5 + SPELL (1 cards)
	if (refCard.cost > 5 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GreySageParrot
		));
	}

	// COST_LESS_5 + MINION (2 cards)
	if (refCard.cost < 5 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GrizzledGuardian,
			CardIds.OakenSummons_CORE_LOOT_309
		));
	}

	// BEAST + COST_LESS_6 (2 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 6) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.GuardianAnimals,
			CardIds.PetCollector
		));
	}

	// COST_MORE_3 (1 cards)
	if (refCard.cost > 3) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.HemetJungleHunter
		));
	}

	// COST_MORE_0 + MINION (1 cards)
	if (refCard.cost > 0 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Hybridization_TLC_236
		));
	}

	// COST_EQUAL_7 + MINION (1 cards)
	if (refCard.cost === 7 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// COST_EQUAL_8 + MINION (2 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon,
			CardIds.SilverVanguard
		));
	}

	// COST_EQUAL_9 + MINION (1 cards)
	if (refCard.cost === 9 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// COST_EQUAL_10 + MINION (1 cards)
	if (refCard.cost === 10 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.JuicyPsychmelon
		));
	}

	// COST_EQUAL_3 (1 cards)
	if (refCard.cost === 3) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.LinedancePartner_WW_433
		));
	}

	// MINION + NEUTRAL (2 cards)
	if (refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.MeekMasteryTavernBrawl,
			CardIds.MulchMadnessTavernBrawl
		));
	}

	// COST_MORE_2 (1 cards)
	if (refCard.cost > 2) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.OrbOfRevelationTavernBrawl
		));
	}

	// COST_EQUAL_1 (4 cards)
	if (refCard.cost === 1) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.PipThePotent_WW_394,
			CardIds.PrinceLiam,
			CardIds.RollingStone,
			CardIds.ThirstyDrifter_WW_387
		));
	}

	// COST_MORE_1 + SPELL (1 cards)
	if (refCard.cost > 1 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.PlaguebringerTavernBrawl
		));
	}

	// COST_LESS_4 + COST_MORE_0 + MINION (1 cards)
	if (refCard.cost < 4 && refCard.cost > 0 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.Rally
		));
	}

	// COST_EQUAL_4 (1 cards)
	if (refCard.cost === 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.RowdyPartner_WW_906
		));
	}

	// COST_MORE_5 + MINION (1 cards)
	if (refCard.cost > 5 && refCard.type?.toUpperCase() === 'MINION') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.ScepterOfSummoning
		));
	}

	// COST_LESS_4 + SPELL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.StonehearthVindicator
		));
	}

	// COST_MORE_5 (1 cards)
	if (refCard.cost > 5) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SummerFlowerchild
		));
	}

	// COST_LESS_3 + SPELL (2 cards)
	if (refCard.cost < 3 && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.VioletTreasuregill_TLC_438
		));
	}

	// COST_MORE_0 + SHADOW + SPELL (1 cards)
	if (refCard.cost > 0 && refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TamsinRoame_BAR_918
		));
	}

	// COST_MORE_4 (1 cards)
	if (refCard.cost > 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TimberTambourine
		));
	}

	// BEAST + COST_LESS_4 (1 cards)
	if (refCard.races?.map(r => r.toUpperCase()).includes('BEAST') && refCard.cost < 4) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.TrialOfTheJormungars_WON_028
		));
	}

	// COST_LESS_4 + MINION + NEUTRAL (1 cards)
	if (refCard.cost < 4 && refCard.type?.toUpperCase() === 'MINION' && refCard.classes?.includes('NEUTRAL')) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(
			CardIds.WarCommandsTavernBrawl
		));
	}

	return null;
};