/* eslint-disable no-mixed-spaces-and-tabs */
// Legendary Invitation (REV_951t): 2 Mana Paladin Spell
// Generated by The Countess (REV_951 / CORE_REV_951)
// "<b>Discover</b> a <b>Legendary</b> minion from another class. It costs (0)."

import { ALL_CLASSES, CardClass, CardIds, CardRarity, CardType, ReferenceCard } from '@firestone-hs/reference-data';
import { GuessedInfo } from '../../models/deck-card';
import { fromAnotherClass, hasCorrectRarity, hasCorrectType } from '../../related-cards/dynamic-pools';
import { GeneratingCard, GuessInfoInput, StaticGeneratingCard, StaticGeneratingCardInput } from './_card.type';
import { filterCards } from './utils';

const isMatch = (c: ReferenceCard, currentClass?: string) =>
	hasCorrectType(c, CardType.MINION) &&
	hasCorrectRarity(c, CardRarity.LEGENDARY) &&
	fromAnotherClass(c, currentClass);

export const LegendaryInvitation: GeneratingCard & StaticGeneratingCard = {
	cardIds: [CardIds.TheCountess_LegendaryInvitationToken],
	publicCreator: true,
	dynamicPool: (input: StaticGeneratingCardInput) =>
		filterCards(
			LegendaryInvitation.cardIds[0],
			input.allCards,
			(c) => isMatch(c, input.inputOptions.currentClass),
			input.inputOptions,
		),
	guessInfo: (input: GuessInfoInput): GuessedInfo | null => {
		const currentClass = input.deckState.getCurrentClass();
		const otherClasses = ALL_CLASSES.filter((c) => c.toUpperCase() !== currentClass?.toUpperCase()).map(
			(c) => CardClass[c.toUpperCase() as keyof typeof CardClass],
		);
		const possibleCards = filterCards(
			LegendaryInvitation.cardIds[0],
			input.allCards,
			(c) => isMatch(c, currentClass),
			input.options,
		);
		return {
			cardType: CardType.MINION,
			rarity: CardRarity.LEGENDARY,
			cardClasses: otherClasses,
			possibleCards,
		};
	},
};
