import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { Achievement } from '../../models/achievement';
import { CompletedAchievement } from '../../models/completed-achievement';
import { FilterOption } from '../../models/filter-option';
import { IndexedVisualAchievement } from '../../models/indexed-visual-achievement';
import { CompletionStep, VisualAchievement } from '../../models/visual-achievement';
import { VisualAchievementCategory } from '../../models/visual-achievement-category';
import { AchievementsLoaderService } from './data/achievements-loader.service';
import { RemoteAchievementsService } from './remote-achievements.service';

@Injectable()
export class AchievementsRepository {
	public modulesLoaded = new BehaviorSubject<boolean>(false);

	private categories: readonly VisualAchievementCategory[];

	constructor(
		private remoteAchievements: RemoteAchievementsService,
		private achievementsLoader: AchievementsLoaderService,
	) {
		this.init();
	}

	public async getTopLevelCategories(): Promise<readonly VisualAchievementCategory[]> {
		await this.waitForInit();
		return this.categories;
	}

	private async init() {
		const [[allAchievements, challenges], completedAchievements] = await Promise.all([
			this.achievementsLoader.initializeAchievements(),
			this.remoteAchievements.loadAchievements(),
		]);
		const mergedAchievements = this.mergeAchievements(allAchievements, completedAchievements);
		this.categories = await this.buildCategories(mergedAchievements);
		console.log('[achievements-repository] achievements initialised');
		this.modulesLoaded.next(true);
	}

	private mergeAchievements(
		allAchievements: readonly Achievement[],
		completedAchievements?: readonly CompletedAchievement[],
	): readonly VisualAchievement[] {
		const mergedAchievements: readonly Achievement[] = !completedAchievements
			? allAchievements
			: allAchievements.map((ref: Achievement) => {
					const completedAchievement = completedAchievements.filter(compl => compl.id === ref.id).pop();
					const numberOfCompletions = completedAchievement ? completedAchievement.numberOfCompletions : 0;
					return Object.assign(new Achievement(), ref, {
						numberOfCompletions: numberOfCompletions,
					} as Achievement);
			  });
		// console.log('[perf] getting full achievements');
		const fullAchievements: VisualAchievement[] = mergedAchievements
			.filter(achievement => this.isAchievementVisualRoot(achievement))
			.map((achievement, index) => this.convertToVisual(achievement, index, mergedAchievements))
			.map(obj => obj.achievement)
			.sort((a, b) => {
				if (a.id < b.id) {
					return -1;
				}
				if (a.id > b.id) {
					return 1;
				}
				return 0;
			});
		// console.log('[perf] returning result');
		return fullAchievements;
	}

	private convertToVisual(
		achievement: Achievement,
		index: number,
		allAchievements: readonly Achievement[],
	): IndexedVisualAchievement {
		const achievementForCompletionSteps: Achievement[] = allAchievements
			.filter(achv => achv.type === achievement.type)
			.sort((a, b) => a.priority - b.priority);
		let text = achievement.text || achievement.emptyText;
		const [completionSteps, textFromStep] = AchievementsRepository.buildCompletionSteps(
			achievementForCompletionSteps,
			achievement,
			text,
		);
		text = text || textFromStep;
		return {
			achievement: VisualAchievement.create({
				id: achievement.id,
				name: achievement.name,
				type: achievement.type,
				cardId: achievement.displayCardId,
				cardType: achievement.displayCardType,
				text: text,
				completionSteps: completionSteps,
			} as VisualAchievement),
			index: index,
		};
	}

	private async buildCategories(
		achievements: readonly VisualAchievement[],
	): Promise<readonly VisualAchievementCategory[]> {
		const categoryConfiguration: AchievementConfiguration = {
			categories: [
				{
					id: 'global',
					name: 'Global',
					icon: 'globals',
					achievementTypes: [
						'global_damage_to_enemy_heroes',
						'global_enemy_minions_dead',
						'global_mana_spent',
						'global_total_duration',
						'global_total_match',
					],
				},
				{
					id: 'competitive_ladder',
					name: 'Ladder',
					icon: 'competitive_ladder',
					achievementTypes: [
						'competitive_ladder_nemesis_demonhunter',
						'competitive_ladder_nemesis_druid',
						'competitive_ladder_nemesis_hunter',
						'competitive_ladder_nemesis_mage',
						'competitive_ladder_nemesis_paladin',
						'competitive_ladder_nemesis_priest',
						'competitive_ladder_nemesis_rogue',
						'competitive_ladder_nemesis_shaman',
						'competitive_ladder_nemesis_warlock',
						'competitive_ladder_nemesis_warrior',
					],
				},
				{
					id: 'amazing_plays',
					name: 'Amazing Plays',
					icon: 'amazing_plays',
					achievementTypes: [
						'amazing_plays_win_with_one_hp',
						'amazing_plays_win_with_full_hp',
						'amazing_plays_game_tie',
						'amazing_plays_win_without_taking_damage',
						'amazing_plays_summon_highkeeper_ra',
						'amazing_plays_discard_cards',
						'amazing_plays_hero_heal',
						'amazing_plays_deal_damage',
						'amazing_plays_gain_armor',
						'amazing_plays_desert_obelisk',
						'amazing_plays_recurring_villains',
						'amazing_plays_fatigue_count',
					],
				},
				{
					id: 'deckbuilding',
					name: 'Deckbuilding',
					icon: 'deckbuilding',
					achievementTypes: [
						'deckbuilding_win_balanced',
						'deckbuilding_win_classic',
						'deckbuilding_win_complex',
						'deckbuilding_win_epic',
						'deckbuilding_win_fragile_nature',
						'deckbuilding_win_free_speech',
						'deckbuilding_win_lifesteal',
						'deckbuilding_win_lone_survivor',
						'deckbuilding_win_minion',
						'deckbuilding_win_miracle',
						'deckbuilding_win_random',
						'deckbuilding_win_richly_balanced',
						'deckbuilding_win_simple',
						'deckbuilding_win_so_quiet',
						'deckbuilding_win_sorcerer',
						'deckbuilding_win_summoner',
						'deckbuilding_win_sword_and_spell',
						'deckbuilding_win_the_void',
						'deckbuilding_win_thousand_cuts',
					],
				},
				{
					id: 'thijs',
					name: 'Thijs',
					icon: 'thijs',
					achievementTypes: [
						'thijs_attack_multiple_times',
						'thijs_big_deck',
						'thijs_close_call',
						'thijs_echo_cavern',
						'thijs_heal',
						'thijs_no_minions',
						'thijs_no_spells',
						'thijs_quick_win',
						'thijs_secrets',
						'thijs_tea_time',
						'thijs_thijs',
						'thijs_total_damage',
						'thijs_untouchable',
						'thijs_whoneedscards',
					],
				},
				{
					id: 'battlegrounds',
					name: 'Battlegrounds',
					icon: 'battlegrounds',
					categories: [
						{
							id: 'battlegrounds_tracking',
							name: 'Tracking',
							icon: 'achievements_progression',
							achievementTypes: [
								'battlegrounds_coin_spent',
								'battlegrounds_damage_to_enemy_heroes',
								'battlegrounds_eliminate_other_players',
								'battlegrounds_enemy_minions_dead',
								'battlegrounds_lock_all',
								'battlegrounds_reroll_tavern',
								'battlegrounds_tavern_upgrade',
								'battlegrounds_total_duration',
								'battlegrounds_total_match',
								'battlegrounds_tribe_played_beast',
								'battlegrounds_tribe_played_demon',
								'battlegrounds_tribe_played_dragon',
								'battlegrounds_tribe_played_elemental',
								'battlegrounds_tribe_played_mechanical',
								'battlegrounds_tribe_played_murloc',
								'battlegrounds_tribe_played_pirate',
							],
						},
						{
							id: 'battlegrounds_competitive',
							name: 'Competitive',
							icon: 'achievements_boss',
							achievementTypes: [
								'battlegrounds_0ranking',
								'battlegrounds_0win_streak',
								'battlegrounds_hero_TB_BaconShop_HERO_01',
								'battlegrounds_hero_TB_BaconShop_HERO_02',
								'battlegrounds_hero_TB_BaconShop_HERO_08',
								'battlegrounds_hero_TB_BaconShop_HERO_11',
								'battlegrounds_hero_TB_BaconShop_HERO_12',
								'battlegrounds_hero_TB_BaconShop_HERO_14',
								'battlegrounds_hero_TB_BaconShop_HERO_15',
								'battlegrounds_hero_TB_BaconShop_HERO_16',
								'battlegrounds_hero_TB_BaconShop_HERO_17',
								'battlegrounds_hero_TB_BaconShop_HERO_18',
								'battlegrounds_hero_TB_BaconShop_HERO_21',
								'battlegrounds_hero_TB_BaconShop_HERO_22',
								'battlegrounds_hero_TB_BaconShop_HERO_23',
								'battlegrounds_hero_TB_BaconShop_HERO_25',
								'battlegrounds_hero_TB_BaconShop_HERO_27',
								'battlegrounds_hero_TB_BaconShop_HERO_28',
								'battlegrounds_hero_TB_BaconShop_HERO_33',
								'battlegrounds_hero_TB_BaconShop_HERO_34',
								'battlegrounds_hero_TB_BaconShop_HERO_35',
								'battlegrounds_hero_TB_BaconShop_HERO_36',
								'battlegrounds_hero_TB_BaconShop_HERO_37',
								'battlegrounds_hero_TB_BaconShop_HERO_38',
								'battlegrounds_hero_TB_BaconShop_HERO_39',
								'battlegrounds_hero_TB_BaconShop_HERO_40',
								'battlegrounds_hero_TB_BaconShop_HERO_41',
								'battlegrounds_hero_TB_BaconShop_HERO_42',
								'battlegrounds_hero_TB_BaconShop_HERO_43',
								'battlegrounds_hero_TB_BaconShop_HERO_45',
								'battlegrounds_hero_TB_BaconShop_HERO_49',
								'battlegrounds_hero_TB_BaconShop_HERO_50',
								'battlegrounds_hero_TB_BaconShop_HERO_52',
								'battlegrounds_hero_TB_BaconShop_HERO_53',
								'battlegrounds_hero_TB_BaconShop_HERO_55',
								'battlegrounds_hero_TB_BaconShop_HERO_56',
								'battlegrounds_hero_TB_BaconShop_HERO_57',
								'battlegrounds_hero_TB_BaconShop_HERO_58',
								'battlegrounds_hero_TB_BaconShop_HERO_59',
								'battlegrounds_hero_TB_BaconShop_HERO_60',
								'battlegrounds_hero_TB_BaconShop_HERO_62',
								'battlegrounds_hero_TB_BaconShop_HERO_64',
								'battlegrounds_hero_TB_BaconShop_HERO_67',
								'battlegrounds_hero_TB_BaconShop_HERO_68',
								'battlegrounds_hero_TB_BaconShop_HERO_70',
								'battlegrounds_hero_TB_BaconShop_HERO_71',
								'battlegrounds_hero_TB_BaconShop_HERO_72',
								'battlegrounds_hero_TB_BaconShop_HERO_74',
								'battlegrounds_hero_TB_BaconShop_HERO_75',
								'battlegrounds_hero_TB_BaconShop_HERO_76',
								'battlegrounds_hero_TB_BaconShop_HERO_78',
								'battlegrounds_hero_TB_BaconShop_HERO_90',
								'battlegrounds_hero_TB_BaconShop_HERO_91',
							],
						},
						{
							id: 'battlegrounds_minions',
							name: 'Minions',
							icon: 'achievements_treasure',
							achievementTypes: [
								'battlegrounds_minion_play_TB_BaconShop_HP_033t',
								'battlegrounds_minion_play_TB_BaconUps_093',
								'battlegrounds_minion_play_TB_BaconUps_093t',
								'battlegrounds_minion_play_TB_BaconUps_125',
								'battlegrounds_minion_play_TB_BaconUps_094',
								'battlegrounds_minion_play_TB_BaconUps_011',
								'battlegrounds_minion_play_TB_BaconUps_003',
								'battlegrounds_minion_play_TB_BaconUps_003t',
								'battlegrounds_minion_play_ICC_038',
								'battlegrounds_minion_play_TB_BaconUps_061',
								'battlegrounds_minion_play_LOOT_013',
								'battlegrounds_minion_play_TB_BaconUps_079',
								'battlegrounds_minion_play_TB_BaconUps_112',
								'battlegrounds_minion_play_BGS_039',
								'battlegrounds_minion_play_TB_BaconUps_102',
								'battlegrounds_minion_play_TB_BaconUps_126',
								'battlegrounds_minion_play_TB_BaconUps_141',
								'battlegrounds_minion_play_ULD_217',
								'battlegrounds_minion_play_TB_BaconUps_156',
								'battlegrounds_minion_play_TB_BaconUps_167',
								'battlegrounds_minion_play_BGS_115t',
								'battlegrounds_minion_play_TB_BaconUps_006',
								'battlegrounds_minion_play_TB_BaconUps_028',
								'battlegrounds_minion_play_TB_BaconUps_004',
								'battlegrounds_minion_play_TB_BaconUps_066',
								'battlegrounds_minion_play_TB_BaconUps_008',
								'battlegrounds_minion_play_TB_BaconUps_062',
								'battlegrounds_minion_play_TB_BaconUps_036',
								'battlegrounds_minion_play_TB_BaconUps_027',
								'battlegrounds_minion_play_TB_BaconUps_043',
								'battlegrounds_minion_play_TB_BaconUps_025',
								'battlegrounds_minion_play_TB_BaconUps_113',
								'battlegrounds_minion_play_TB_BaconUps_115',
								'battlegrounds_minion_play_TB_BaconUps_107',
								'battlegrounds_minion_play_TB_BaconUps_105',
								'battlegrounds_minion_play_TB_BaconUps_118',
								'battlegrounds_minion_play_TB_BaconUps_136',
								'battlegrounds_minion_play_TB_BaconUps_135',
								'battlegrounds_minion_play_TB_BaconUps_127',
								'battlegrounds_minion_play_TB_BaconUps_144',
								'battlegrounds_minion_play_TB_BaconUps_160',
								'battlegrounds_minion_play_TB_Baconups_202',
								'battlegrounds_minion_play_TB_BaconUps_014',
								'battlegrounds_minion_play_TB_BaconUps_064',
								'battlegrounds_minion_play_TB_BaconUps_037',
								'battlegrounds_minion_play_TB_BaconUps_070',
								'battlegrounds_minion_play_TB_BaconUps_068',
								'battlegrounds_minion_play_TB_BaconUps_030',
								'battlegrounds_minion_play_TB_BaconUps_026',
								'battlegrounds_minion_play_TB_BaconUps_034',
								'battlegrounds_minion_play_TB_BaconUps_086',
								'battlegrounds_minion_play_TB_BaconUps_035',
								'battlegrounds_minion_play_TB_BaconUps_032',
								'battlegrounds_minion_play_TB_BaconUps_069',
								'battlegrounds_minion_play_TB_BaconUps_095',
								'battlegrounds_minion_play_TB_BaconUps_075',
								'battlegrounds_minion_play_TB_BaconUps_101',
								'battlegrounds_minion_play_BGS_034',
								'battlegrounds_minion_play_TB_BaconUps_104',
								'battlegrounds_minion_play_TB_BaconUps_123',
								'battlegrounds_minion_play_TB_BaconUps_124',
								'battlegrounds_minion_play_BGS_060',
								'battlegrounds_minion_play_TB_BaconUps_143',
								'battlegrounds_minion_play_TB_BaconUps_138',
								'battlegrounds_minion_play_TB_BaconUps_161',
								'battlegrounds_minion_play_TB_Baconups_203',
								'battlegrounds_minion_play_TB_BaconUps_159',
								'battlegrounds_minion_play_TB_BaconUps_099',
								'battlegrounds_minion_play_TB_BaconUps_047',
								'battlegrounds_minion_play_LOOT_078',
								'battlegrounds_minion_play_TB_BaconUps_009',
								'battlegrounds_minion_play_TB_BaconUps_044',
								'battlegrounds_minion_play_TB_BaconUps_046',
								'battlegrounds_minion_play_TB_BaconUps_041',
								'battlegrounds_minion_play_TB_BaconUps_053',
								'battlegrounds_minion_play_TB_BaconUps_042',
								'battlegrounds_minion_play_DAL_077',
								'battlegrounds_minion_play_TB_BaconUps_074',
								'battlegrounds_minion_play_TB_BaconUps_117',
								'battlegrounds_minion_play_TB_BaconUps_103',
								'battlegrounds_minion_play_TB_BaconUps_120',
								'battlegrounds_minion_play_TB_BaconUps_140',
								'battlegrounds_minion_play_TB_BaconUps_130',
								'battlegrounds_minion_play_TB_BaconUps_139',
								'battlegrounds_minion_play_TB_BaconUps_145',
								'battlegrounds_minion_play_TB_BaconUps_166',
								'battlegrounds_minion_play_TB_BaconUps_207',
								'battlegrounds_minion_play_TB_BaconUps_083',
								'battlegrounds_minion_play_TB_BaconUps_055',
								'battlegrounds_minion_play_TB_BaconUps_045',
								'battlegrounds_minion_play_TB_BaconUps_051',
								'battlegrounds_minion_play_TB_BaconUps_082',
								'battlegrounds_minion_play_TB_BaconUps_060',
								'battlegrounds_minion_play_TB_BaconUps_039',
								'battlegrounds_minion_play_TB_BaconUps_089',
								'battlegrounds_minion_play_TB_BaconUps_049',
								'battlegrounds_minion_play_TB_BaconUps_072',
								'battlegrounds_minion_play_TB_BaconUps_100',
								'battlegrounds_minion_play_TB_BaconUps_110',
								'battlegrounds_minion_play_TB_BaconUps_108',
								'battlegrounds_minion_play_TB_BaconUps_106',
								'battlegrounds_minion_play_TB_BaconUps_142',
								'battlegrounds_minion_play_TB_BaconUps_132',
								'battlegrounds_minion_play_TB_BaconUps_133',
								'battlegrounds_minion_play_TB_BaconUps_201',
								'battlegrounds_minion_play_TB_BaconUps_162',
								'battlegrounds_minion_play_TB_BaconUps_251',
								'battlegrounds_minion_play_TB_BaconUps_165',
								'battlegrounds_minion_play_TB_BaconUps_085',
								'battlegrounds_minion_play_GVG_113',
								'battlegrounds_minion_play_TB_BaconUps_057',
								'battlegrounds_minion_play_TB_BaconUps_087',
								'battlegrounds_minion_play_FP1_010',
								'battlegrounds_minion_play_TB_BaconUps_090',
								'battlegrounds_minion_play_TB_BaconUps_080',
								'battlegrounds_minion_play_TB_BaconUps_059',
								'battlegrounds_minion_play_TB_BaconUps_091',
								'battlegrounds_minion_play_TB_BaconUps_116',
								'battlegrounds_minion_play_BGS_041',
								'battlegrounds_minion_play_BGS_040',
								'battlegrounds_minion_play_TB_BaconUps_134',
								'battlegrounds_minion_play_TB_BaconUps_121',
								'battlegrounds_minion_play_TB_BaconUps_137',
								'battlegrounds_minion_play_TB_BaconUps_163',
								'battlegrounds_minion_play_TB_BaconUps_200',
							],
						},
					],
				},
				{
					id: 'galakrond',
					name: 'Galakrond',
					icon: 'galakrond',
					categories: [
						{
							id: 'galakrond_tracking',
							name: 'Tracking',
							icon: 'achievements_progression',
							achievementTypes: [
								'galakrond_coin_spent',
								'galakrond_damage_to_enemy_heroes',
								'galakrond_enemy_minions_dead',
								'galakrond_total_duration',
								'galakrond_total_match',
							],
						},
						{
							id: 'galakrond_domination',
							name: 'Domination',
							icon: 'achievements_boss',
							achievementTypes: [
								'galakrond_domination_DRGA_BOSS_01h3',
								'galakrond_domination_DRGA_BOSS_01h4',
								'galakrond_domination_DRGA_BOSS_03h2_H',
								'galakrond_domination_DRGA_BOSS_05h',
								'galakrond_domination_DRGA_BOSS_06h',
								'galakrond_domination_DRGA_BOSS_07h3',
								'galakrond_domination_DRGA_BOSS_08h',
								'galakrond_domination_DRGA_BOSS_09h',
								'galakrond_domination_DRGA_BOSS_10h',
								'galakrond_domination_DRGA_BOSS_11h',
								'galakrond_domination_DRGA_BOSS_11h2',
								'galakrond_domination_DRGA_BOSS_13h',
								'galakrond_domination_DRGA_BOSS_18h',
								'galakrond_domination_DRGA_BOSS_19h',
								'galakrond_domination_DRGA_BOSS_20h',
								'galakrond_domination_DRGA_BOSS_22h',
								'galakrond_domination_DRGA_BOSS_23h2',
								'galakrond_domination_DRGA_BOSS_24h',
								'galakrond_domination_DRGA_BOSS_25h',
								'galakrond_domination_DRGA_BOSS_26h',
								'galakrond_domination_DRGA_BOSS_27h',
								'galakrond_domination_DRGA_BOSS_30h2',
								'galakrond_domination_DRGA_BOSS_31h',
								'galakrond_domination_DRGA_BOSS_32h',
							],
						},
					],
				},
				{
					id: 'tombs_of_terror',
					name: 'Tombs of Terror',
					icon: 'tombs_of_terror',
					categories: [
						{
							id: 'tombs_of_terror_treasure',
							name: 'Treasures',
							icon: 'achievements_treasure',
							achievementTypes: [
								'tombs_of_terror_treasure_play_ULDA_001',
								'tombs_of_terror_treasure_play_ULDA_002',
								'tombs_of_terror_treasure_play_ULDA_003',
								'tombs_of_terror_treasure_play_ULDA_004',
								'tombs_of_terror_treasure_play_ULDA_006',
								'tombs_of_terror_treasure_play_ULDA_008',
								'tombs_of_terror_treasure_play_ULDA_010',
								'tombs_of_terror_treasure_play_ULDA_012',
								'tombs_of_terror_treasure_play_ULDA_013',
								'tombs_of_terror_treasure_play_ULDA_015',
								'tombs_of_terror_treasure_play_ULDA_016',
								'tombs_of_terror_treasure_play_ULDA_017',
								'tombs_of_terror_treasure_play_ULDA_018',
								'tombs_of_terror_treasure_play_ULDA_020',
								'tombs_of_terror_treasure_play_ULDA_021',
								'tombs_of_terror_treasure_play_ULDA_022',
								'tombs_of_terror_treasure_play_ULDA_023',
								'tombs_of_terror_treasure_play_ULDA_034',
								'tombs_of_terror_treasure_play_ULDA_035',
								'tombs_of_terror_treasure_play_ULDA_036',
								'tombs_of_terror_treasure_play_ULDA_040',
								'tombs_of_terror_treasure_play_ULDA_041',
								'tombs_of_terror_treasure_play_ULDA_043',
								'tombs_of_terror_treasure_play_ULDA_044',
								'tombs_of_terror_treasure_play_ULDA_110',
								'tombs_of_terror_treasure_play_ULDA_111',
								'tombs_of_terror_treasure_play_ULDA_112',
								'tombs_of_terror_treasure_play_ULDA_113',
								'tombs_of_terror_treasure_play_ULDA_114',
								'tombs_of_terror_treasure_play_ULDA_115',
								'tombs_of_terror_treasure_play_ULDA_118',
								'tombs_of_terror_treasure_play_ULDA_201',
								'tombs_of_terror_treasure_play_ULDA_202',
								'tombs_of_terror_treasure_play_ULDA_203',
								'tombs_of_terror_treasure_play_ULDA_204',
								'tombs_of_terror_treasure_play_ULDA_206',
								'tombs_of_terror_treasure_play_ULDA_207',
								'tombs_of_terror_treasure_play_ULDA_301',
								'tombs_of_terror_treasure_play_ULDA_302',
								'tombs_of_terror_treasure_play_ULDA_303',
								'tombs_of_terror_treasure_play_ULDA_304',
								'tombs_of_terror_treasure_play_ULDA_305',
								'tombs_of_terror_treasure_play_ULDA_306',
								'tombs_of_terror_treasure_play_ULDA_307',
								'tombs_of_terror_treasure_play_ULDA_401',
								'tombs_of_terror_treasure_play_ULDA_402',
								'tombs_of_terror_treasure_play_ULDA_403',
								'tombs_of_terror_treasure_play_ULDA_404',
								'tombs_of_terror_treasure_play_ULDA_405',
								'tombs_of_terror_treasure_play_ULDA_406',
								'tombs_of_terror_treasure_play_ULDA_407',
								'tombs_of_terror_treasure_play_ULDA_501',
								'tombs_of_terror_treasure_play_ULDA_502',
								'tombs_of_terror_treasure_play_ULDA_503',
								'tombs_of_terror_treasure_play_ULDA_505',
								'tombs_of_terror_treasure_play_ULDA_507',
							],
						},
						{
							id: 'tombs_of_terror_passive',
							name: 'Passives',
							icon: 'achievements_passive',
							achievementTypes: [
								'tombs_of_terror_passive_play_DALA_728',
								'tombs_of_terror_passive_play_DALA_731',
								'tombs_of_terror_passive_play_DALA_737',
								'tombs_of_terror_passive_play_DALA_739',
								'tombs_of_terror_passive_play_DALA_746',
								'tombs_of_terror_passive_play_DALA_747',
								'tombs_of_terror_passive_play_GILA_506',
								'tombs_of_terror_passive_play_LOOTA_803',
								'tombs_of_terror_passive_play_LOOTA_824',
								'tombs_of_terror_passive_play_LOOTA_828',
								'tombs_of_terror_passive_play_LOOTA_831',
								'tombs_of_terror_passive_play_LOOTA_832',
								'tombs_of_terror_passive_play_LOOTA_833',
								'tombs_of_terror_passive_play_LOOTA_846',
								'tombs_of_terror_passive_play_ULDA_005',
								'tombs_of_terror_passive_play_ULDA_007',
								'tombs_of_terror_passive_play_ULDA_009',
								'tombs_of_terror_passive_play_ULDA_011',
								'tombs_of_terror_passive_play_ULDA_014',
								'tombs_of_terror_passive_play_ULDA_042',
								'tombs_of_terror_passive_play_ULDA_045',
								'tombs_of_terror_passive_play_ULDA_046',
								'tombs_of_terror_passive_play_ULDA_101',
								'tombs_of_terror_passive_play_ULDA_102',
								'tombs_of_terror_passive_play_ULDA_103',
								'tombs_of_terror_passive_play_ULDA_116',
								'tombs_of_terror_passive_play_ULDA_117',
								'tombs_of_terror_passive_play_ULDA_205',
								'tombs_of_terror_passive_play_ULDA_208',
								'tombs_of_terror_passive_play_ULDA_508',
							],
						},
						{
							id: 'tombs_of_terror_bob_treats',
							name: `Bob's Treats`,
							icon: 'achievements_treasure',
							achievementTypes: [
								'tombs_of_terror_bob_treat_DALA_902',
								'tombs_of_terror_bob_treat_DALA_903',
								'tombs_of_terror_bob_treat_DALA_904',
								'tombs_of_terror_bob_treat_DALA_905',
								'tombs_of_terror_bob_treat_DALA_906',
								'tombs_of_terror_bob_treat_DALA_907',
								'tombs_of_terror_bob_treat_DALA_908',
								'tombs_of_terror_bob_treat_DALA_909',
								'tombs_of_terror_bob_treat_DALA_910',
								'tombs_of_terror_bob_treat_DALA_912',
								'tombs_of_terror_bob_treat_DALA_913',
								'tombs_of_terror_bob_treat_DALA_914',
								'tombs_of_terror_bob_treat_ULDA_019',
								'tombs_of_terror_bob_treat_ULDA_024',
								'tombs_of_terror_bob_treat_ULDA_038',
								'tombs_of_terror_bob_treat_ULDA_504',
								'tombs_of_terror_bob_treat_ULDA_601',
								'tombs_of_terror_bob_treat_ULDA_602',
								'tombs_of_terror_bob_treat_ULDA_603',
								'tombs_of_terror_bob_treat_ULDA_604',
								'tombs_of_terror_bob_treat_ULDA_605',
								'tombs_of_terror_bob_treat_ULDA_606',
								'tombs_of_terror_bob_treat_ULDA_607',
								'tombs_of_terror_bob_treat_ULDA_608',
								'tombs_of_terror_bob_treat_ULDA_911',
								'tombs_of_terror_bob_treat_ULDA_912',
							],
						},
						{
							id: 'tombs_of_terror_boss',
							name: 'Bosses',
							icon: 'achievements_boss',
							achievementTypes: [
								'tombs_of_terror_boss_ULDA_BOSS_01h',
								'tombs_of_terror_boss_ULDA_BOSS_02h',
								'tombs_of_terror_boss_ULDA_BOSS_03h',
								'tombs_of_terror_boss_ULDA_BOSS_04h',
								'tombs_of_terror_boss_ULDA_BOSS_05h',
								'tombs_of_terror_boss_ULDA_BOSS_06h',
								'tombs_of_terror_boss_ULDA_BOSS_07h',
								'tombs_of_terror_boss_ULDA_BOSS_08h',
								'tombs_of_terror_boss_ULDA_BOSS_09h',
								'tombs_of_terror_boss_ULDA_BOSS_10h',
								'tombs_of_terror_boss_ULDA_BOSS_11h',
								'tombs_of_terror_boss_ULDA_BOSS_12h',
								'tombs_of_terror_boss_ULDA_BOSS_13h',
								'tombs_of_terror_boss_ULDA_BOSS_14h',
								'tombs_of_terror_boss_ULDA_BOSS_15h',
								'tombs_of_terror_boss_ULDA_BOSS_16h',
								'tombs_of_terror_boss_ULDA_BOSS_17h',
								'tombs_of_terror_boss_ULDA_BOSS_18h',
								'tombs_of_terror_boss_ULDA_BOSS_19h',
								'tombs_of_terror_boss_ULDA_BOSS_20h',
								'tombs_of_terror_boss_ULDA_BOSS_21h',
								'tombs_of_terror_boss_ULDA_BOSS_22h',
								'tombs_of_terror_boss_ULDA_BOSS_23h',
								'tombs_of_terror_boss_ULDA_BOSS_24h',
								'tombs_of_terror_boss_ULDA_BOSS_25h',
								'tombs_of_terror_boss_ULDA_BOSS_26h',
								'tombs_of_terror_boss_ULDA_BOSS_27h',
								'tombs_of_terror_boss_ULDA_BOSS_28h',
								'tombs_of_terror_boss_ULDA_BOSS_29h',
								'tombs_of_terror_boss_ULDA_BOSS_30h',
								'tombs_of_terror_boss_ULDA_BOSS_31h',
								'tombs_of_terror_boss_ULDA_BOSS_32h',
								'tombs_of_terror_boss_ULDA_BOSS_33h',
								'tombs_of_terror_boss_ULDA_BOSS_34h',
								'tombs_of_terror_boss_ULDA_BOSS_35h',
								'tombs_of_terror_boss_ULDA_BOSS_36h',
								'tombs_of_terror_boss_ULDA_BOSS_41h',
								'tombs_of_terror_boss_ULDA_BOSS_42h',
								'tombs_of_terror_boss_ULDA_BOSS_43h',
								'tombs_of_terror_boss_ULDA_BOSS_44h',
								'tombs_of_terror_boss_ULDA_BOSS_45h',
								'tombs_of_terror_boss_ULDA_BOSS_46h',
								'tombs_of_terror_boss_ULDA_BOSS_47h',
								'tombs_of_terror_boss_ULDA_BOSS_48h',
								'tombs_of_terror_boss_ULDA_BOSS_49h',
								'tombs_of_terror_boss_ULDA_BOSS_50h',
								'tombs_of_terror_boss_ULDA_BOSS_51h',
								'tombs_of_terror_boss_ULDA_BOSS_52h',
								'tombs_of_terror_boss_ULDA_BOSS_53h',
								'tombs_of_terror_boss_ULDA_BOSS_54h',
								'tombs_of_terror_boss_ULDA_BOSS_55h',
								'tombs_of_terror_boss_ULDA_BOSS_56h',
								'tombs_of_terror_boss_ULDA_BOSS_57h',
								'tombs_of_terror_boss_ULDA_BOSS_58h',
								'tombs_of_terror_boss_ULDA_BOSS_59h',
								'tombs_of_terror_boss_ULDA_BOSS_60h',
								'tombs_of_terror_boss_ULDA_BOSS_61h',
								'tombs_of_terror_boss_ULDA_BOSS_62h',
								'tombs_of_terror_boss_ULDA_BOSS_63h',
								'tombs_of_terror_boss_ULDA_BOSS_65h',
								'tombs_of_terror_boss_ULDA_BOSS_66h',
								'tombs_of_terror_boss_ULDA_BOSS_68h',
								'tombs_of_terror_boss_ULDA_BOSS_69h',
								'tombs_of_terror_boss_ULDA_BOSS_70h',
								'tombs_of_terror_boss_ULDA_BOSS_71h',
								'tombs_of_terror_boss_ULDA_BOSS_72h',
								'tombs_of_terror_boss_ULDA_BOSS_73h',
								'tombs_of_terror_boss_ULDA_BOSS_74h',
								'tombs_of_terror_boss_ULDA_BOSS_75h',
								'tombs_of_terror_boss_ULDA_BOSS_76h',
								'tombs_of_terror_boss_ULDA_BOSS_77h',
								'tombs_of_terror_boss_ULDA_BOSS_78h',
								'tombs_of_terror_boss_ULDA_BOSS_79h',
							],
						},
						{
							id: 'tombs_of_terror_plague_lords',
							name: 'Plague Lords',
							icon: 'achievements_boss',
							achievementTypes: [
								'tombs_of_terror_boss_ULDA_BOSS_37h',
								'tombs_of_terror_boss_ULDA_BOSS_38h',
								'tombs_of_terror_boss_ULDA_BOSS_39h',
								'tombs_of_terror_boss_ULDA_BOSS_40h',
								'tombs_of_terror_boss_ULDA_BOSS_67h',
							],
						},
						{
							id: 'tombs_of_terror_amazing_plays',
							name: 'Amazing Plays',
							icon: 'achievements_shrine',
							achievementTypes: [
								'tombs_of_terror_amazing_plays_aegis_bulwark',
								'tombs_of_terror_amazing_plays_fatigue_vash',
								'tombs_of_terror_amazing_plays_full_tinyfin',
								'tombs_of_terror_amazing_plays_gatling_wand',
								'tombs_of_terror_amazing_plays_high_attack_minion',
								'tombs_of_terror_amazing_plays_legendary_seven_copies_on_board',
								'tombs_of_terror_amazing_plays_plague_lord_tie',
								'tombs_of_terror_amazing_plays_siamat_servant',
								'tombs_of_terror_amazing_plays_unstoppable_ULDA_BOSS_37h',
								'tombs_of_terror_amazing_plays_unstoppable_ULDA_BOSS_38h',
								'tombs_of_terror_amazing_plays_unstoppable_ULDA_BOSS_39h',
								'tombs_of_terror_amazing_plays_unstoppable_ULDA_BOSS_40h',
								'tombs_of_terror_amazing_plays_unstoppable_ULDA_BOSS_67h',
								'tombs_of_terror_amazing_treasure_play_ULDA_032',
								'tombs_of_terror_amazing_treasure_play_ULDA_033',
							],
						},
					],
				},

				{
					id: 'dalaran_heist',
					name: 'Dalaran Heist',
					icon: 'dalaran_heist',
					categories: [
						{
							id: 'dalaran_heist_treasure',
							name: 'Treasures',
							icon: 'achievements_treasure',
							achievementTypes: [
								'dalaran_heist_treasure_play_DALA_700',
								'dalaran_heist_treasure_play_DALA_701',
								'dalaran_heist_treasure_play_DALA_702',
								'dalaran_heist_treasure_play_DALA_703',
								'dalaran_heist_treasure_play_DALA_704',
								'dalaran_heist_treasure_play_DALA_705',
								'dalaran_heist_treasure_play_DALA_706',
								'dalaran_heist_treasure_play_DALA_707',
								'dalaran_heist_treasure_play_DALA_708',
								'dalaran_heist_treasure_play_DALA_709',
								'dalaran_heist_treasure_play_DALA_711',
								'dalaran_heist_treasure_play_DALA_712',
								'dalaran_heist_treasure_play_DALA_713',
								'dalaran_heist_treasure_play_DALA_714',
								'dalaran_heist_treasure_play_DALA_715',
								'dalaran_heist_treasure_play_DALA_716',
								'dalaran_heist_treasure_play_DALA_717',
								'dalaran_heist_treasure_play_DALA_718',
								'dalaran_heist_treasure_play_DALA_719',
								'dalaran_heist_treasure_play_DALA_720',
								'dalaran_heist_treasure_play_DALA_721',
								'dalaran_heist_treasure_play_DALA_722',
								'dalaran_heist_treasure_play_DALA_723',
								'dalaran_heist_treasure_play_DALA_724',
								'dalaran_heist_treasure_play_DALA_725',
								'dalaran_heist_treasure_play_DALA_726',
								'dalaran_heist_treasure_play_DALA_727',
								'dalaran_heist_treasure_play_DALA_729',
								'dalaran_heist_treasure_play_DALA_730',
							],
						},
						{
							id: 'dalaran_heist_passive',
							name: 'Passives',
							icon: 'achievements_passive',
							achievementTypes: [
								'dalaran_heist_passive_play_DALA_728',
								'dalaran_heist_passive_play_DALA_731',
								'dalaran_heist_passive_play_DALA_733',
								'dalaran_heist_passive_play_DALA_735',
								'dalaran_heist_passive_play_DALA_736',
								'dalaran_heist_passive_play_DALA_737',
								'dalaran_heist_passive_play_DALA_738',
								'dalaran_heist_passive_play_DALA_739',
								'dalaran_heist_passive_play_DALA_740',
								'dalaran_heist_passive_play_DALA_741',
								'dalaran_heist_passive_play_DALA_743',
								'dalaran_heist_passive_play_DALA_744',
								'dalaran_heist_passive_play_DALA_745',
								'dalaran_heist_passive_play_DALA_746',
								'dalaran_heist_passive_play_DALA_747',
								'dalaran_heist_passive_play_DALA_748',
								'dalaran_heist_passive_play_GILA_506',
								'dalaran_heist_passive_play_GILA_813',
								'dalaran_heist_passive_play_LOOTA_800',
								'dalaran_heist_passive_play_LOOTA_801',
								'dalaran_heist_passive_play_LOOTA_803',
								'dalaran_heist_passive_play_LOOTA_804',
								'dalaran_heist_passive_play_LOOTA_825',
								'dalaran_heist_passive_play_LOOTA_828',
								'dalaran_heist_passive_play_LOOTA_831',
								'dalaran_heist_passive_play_LOOTA_832',
								'dalaran_heist_passive_play_LOOTA_833',
								'dalaran_heist_passive_play_LOOTA_845',
								'dalaran_heist_passive_play_LOOTA_846',
							],
						},
						{
							id: 'dalaran_heist_boss',
							name: 'Bosses',
							icon: 'achievements_boss',
							achievementTypes: [
								'dalaran_heist_boss_DALA_BOSS_01h',
								'dalaran_heist_boss_DALA_BOSS_02h',
								'dalaran_heist_boss_DALA_BOSS_03h',
								'dalaran_heist_boss_DALA_BOSS_04h',
								'dalaran_heist_boss_DALA_BOSS_05h',
								'dalaran_heist_boss_DALA_BOSS_06h',
								'dalaran_heist_boss_DALA_BOSS_07h',
								'dalaran_heist_boss_DALA_BOSS_08h',
								'dalaran_heist_boss_DALA_BOSS_09h',
								'dalaran_heist_boss_DALA_BOSS_10h',
								'dalaran_heist_boss_DALA_BOSS_11h',
								'dalaran_heist_boss_DALA_BOSS_12h',
								'dalaran_heist_boss_DALA_BOSS_13h',
								'dalaran_heist_boss_DALA_BOSS_14h',
								'dalaran_heist_boss_DALA_BOSS_15h',
								'dalaran_heist_boss_DALA_BOSS_16h',
								'dalaran_heist_boss_DALA_BOSS_17h',
								'dalaran_heist_boss_DALA_BOSS_18h',
								'dalaran_heist_boss_DALA_BOSS_19h',
								'dalaran_heist_boss_DALA_BOSS_20h',
								'dalaran_heist_boss_DALA_BOSS_21h',
								'dalaran_heist_boss_DALA_BOSS_22h',
								'dalaran_heist_boss_DALA_BOSS_23h',
								'dalaran_heist_boss_DALA_BOSS_24h',
								'dalaran_heist_boss_DALA_BOSS_25h',
								'dalaran_heist_boss_DALA_BOSS_26h',
								'dalaran_heist_boss_DALA_BOSS_27h',
								'dalaran_heist_boss_DALA_BOSS_28h',
								'dalaran_heist_boss_DALA_BOSS_29h',
								'dalaran_heist_boss_DALA_BOSS_30h',
								'dalaran_heist_boss_DALA_BOSS_31h',
								'dalaran_heist_boss_DALA_BOSS_32h',
								'dalaran_heist_boss_DALA_BOSS_33h',
								'dalaran_heist_boss_DALA_BOSS_34h',
								'dalaran_heist_boss_DALA_BOSS_35h',
								'dalaran_heist_boss_DALA_BOSS_36h',
								'dalaran_heist_boss_DALA_BOSS_37h',
								'dalaran_heist_boss_DALA_BOSS_38h',
								'dalaran_heist_boss_DALA_BOSS_39h',
								'dalaran_heist_boss_DALA_BOSS_40h',
								'dalaran_heist_boss_DALA_BOSS_41h',
								'dalaran_heist_boss_DALA_BOSS_42h',
								'dalaran_heist_boss_DALA_BOSS_43h',
								'dalaran_heist_boss_DALA_BOSS_44h',
								'dalaran_heist_boss_DALA_BOSS_45h',
								'dalaran_heist_boss_DALA_BOSS_46h',
								'dalaran_heist_boss_DALA_BOSS_47h',
								'dalaran_heist_boss_DALA_BOSS_48h',
								'dalaran_heist_boss_DALA_BOSS_49h',
								'dalaran_heist_boss_DALA_BOSS_50h',
								'dalaran_heist_boss_DALA_BOSS_51h',
								'dalaran_heist_boss_DALA_BOSS_52h',
								'dalaran_heist_boss_DALA_BOSS_53h',
								'dalaran_heist_boss_DALA_BOSS_54h',
								'dalaran_heist_boss_DALA_BOSS_55h',
								'dalaran_heist_boss_DALA_BOSS_56h',
								'dalaran_heist_boss_DALA_BOSS_57h',
								'dalaran_heist_boss_DALA_BOSS_58h',
								'dalaran_heist_boss_DALA_BOSS_59h',
								'dalaran_heist_boss_DALA_BOSS_60h',
								'dalaran_heist_boss_DALA_BOSS_61h',
								'dalaran_heist_boss_DALA_BOSS_62h',
								'dalaran_heist_boss_DALA_BOSS_63h',
								'dalaran_heist_boss_DALA_BOSS_64h',
								'dalaran_heist_boss_DALA_BOSS_65h',
								'dalaran_heist_boss_DALA_BOSS_66h',
								'dalaran_heist_boss_DALA_BOSS_67h',
								'dalaran_heist_boss_DALA_BOSS_68h',
								'dalaran_heist_boss_DALA_BOSS_69h',
								'dalaran_heist_boss_DALA_BOSS_70h',
								'dalaran_heist_boss_DALA_BOSS_71h',
								'dalaran_heist_boss_DALA_BOSS_72h',
								'dalaran_heist_boss_DALA_BOSS_73h',
								'dalaran_heist_boss_DALA_BOSS_74h',
								'dalaran_heist_boss_DALA_BOSS_75h',
							],
						},
					],
				},

				{
					id: 'rumble_run',
					name: 'Rumble Run',
					icon: 'rumble_run',
					categories: [
						{
							id: 'rumble_run_progression',
							name: 'Progression',
							icon: 'achievements_progression',
							achievementTypes: [
								'rumble_run_progression_TRLA_209h_Druid_TRLA_112',
								'rumble_run_progression_TRLA_209h_Druid_TRLA_115',
								'rumble_run_progression_TRLA_209h_Druid_TRLA_116',
								'rumble_run_progression_TRLA_209h_Hunter_TRLA_110',
								'rumble_run_progression_TRLA_209h_Hunter_TRLA_162',
								'rumble_run_progression_TRLA_209h_Hunter_TRLA_163',
								'rumble_run_progression_TRLA_209h_Mage_TRLA_108',
								'rumble_run_progression_TRLA_209h_Mage_TRLA_128',
								'rumble_run_progression_TRLA_209h_Mage_TRLA_129',
								'rumble_run_progression_TRLA_209h_Paladin_TRLA_105',
								'rumble_run_progression_TRLA_209h_Paladin_TRLA_137',
								'rumble_run_progression_TRLA_209h_Paladin_TRLA_138',
								'rumble_run_progression_TRLA_209h_Priest_TRLA_114',
								'rumble_run_progression_TRLA_209h_Priest_TRLA_146',
								'rumble_run_progression_TRLA_209h_Priest_TRLA_147',
								'rumble_run_progression_TRLA_209h_Rogue_TRLA_106',
								'rumble_run_progression_TRLA_209h_Rogue_TRLA_186',
								'rumble_run_progression_TRLA_209h_Rogue_TRLA_187',
								'rumble_run_progression_TRLA_209h_Shaman_TRLA_109',
								'rumble_run_progression_TRLA_209h_Shaman_TRLA_154',
								'rumble_run_progression_TRLA_209h_Shaman_TRLA_155',
								'rumble_run_progression_TRLA_209h_Warlock_TRLA_113',
								'rumble_run_progression_TRLA_209h_Warlock_TRLA_178',
								'rumble_run_progression_TRLA_209h_Warlock_TRLA_179',
								'rumble_run_progression_TRLA_209h_Warrior_TRLA_104',
								'rumble_run_progression_TRLA_209h_Warrior_TRLA_170',
								'rumble_run_progression_TRLA_209h_Warrior_TRLA_171',
							],
						},
						{
							id: 'rumble_run_shrine_play',
							name: 'Shrines Played',
							icon: 'achievements_shrine',
							achievementTypes: [
								'rumble_run_shrine_play_TRLA_104',
								'rumble_run_shrine_play_TRLA_105',
								'rumble_run_shrine_play_TRLA_106',
								'rumble_run_shrine_play_TRLA_108',
								'rumble_run_shrine_play_TRLA_109',
								'rumble_run_shrine_play_TRLA_110',
								'rumble_run_shrine_play_TRLA_112',
								'rumble_run_shrine_play_TRLA_113',
								'rumble_run_shrine_play_TRLA_114',
								'rumble_run_shrine_play_TRLA_115',
								'rumble_run_shrine_play_TRLA_116',
								'rumble_run_shrine_play_TRLA_128',
								'rumble_run_shrine_play_TRLA_129',
								'rumble_run_shrine_play_TRLA_137',
								'rumble_run_shrine_play_TRLA_138',
								'rumble_run_shrine_play_TRLA_146',
								'rumble_run_shrine_play_TRLA_147',
								'rumble_run_shrine_play_TRLA_154',
								'rumble_run_shrine_play_TRLA_155',
								'rumble_run_shrine_play_TRLA_162',
								'rumble_run_shrine_play_TRLA_163',
								'rumble_run_shrine_play_TRLA_170',
								'rumble_run_shrine_play_TRLA_171',
								'rumble_run_shrine_play_TRLA_178',
								'rumble_run_shrine_play_TRLA_179',
								'rumble_run_shrine_play_TRLA_186',
								'rumble_run_shrine_play_TRLA_187',
							],
						},
						{
							id: 'rumble_run_teammate',
							name: 'Teammates',
							icon: 'achievements_teammate',
							achievementTypes: [
								'rumble_run_teammate_play_TRLA_121',
								'rumble_run_teammate_play_TRLA_122',
								'rumble_run_teammate_play_TRLA_123',
								'rumble_run_teammate_play_TRLA_124',
								'rumble_run_teammate_play_TRLA_125',
								'rumble_run_teammate_play_TRLA_127',
								'rumble_run_teammate_play_TRLA_130',
								'rumble_run_teammate_play_TRLA_131',
								'rumble_run_teammate_play_TRLA_132',
								'rumble_run_teammate_play_TRLA_133',
								'rumble_run_teammate_play_TRLA_134',
								'rumble_run_teammate_play_TRLA_135',
								'rumble_run_teammate_play_TRLA_139',
								'rumble_run_teammate_play_TRLA_140',
								'rumble_run_teammate_play_TRLA_141',
								'rumble_run_teammate_play_TRLA_142',
								'rumble_run_teammate_play_TRLA_143',
								'rumble_run_teammate_play_TRLA_144',
								'rumble_run_teammate_play_TRLA_148',
								'rumble_run_teammate_play_TRLA_149',
								'rumble_run_teammate_play_TRLA_150',
								'rumble_run_teammate_play_TRLA_151',
								'rumble_run_teammate_play_TRLA_152',
								'rumble_run_teammate_play_TRLA_153',
								'rumble_run_teammate_play_TRLA_156',
								'rumble_run_teammate_play_TRLA_157',
								'rumble_run_teammate_play_TRLA_158',
								'rumble_run_teammate_play_TRLA_159',
								'rumble_run_teammate_play_TRLA_160',
								'rumble_run_teammate_play_TRLA_161',
								'rumble_run_teammate_play_TRLA_164',
								'rumble_run_teammate_play_TRLA_165',
								'rumble_run_teammate_play_TRLA_166',
								'rumble_run_teammate_play_TRLA_167',
								'rumble_run_teammate_play_TRLA_168',
								'rumble_run_teammate_play_TRLA_169',
								'rumble_run_teammate_play_TRLA_172',
								'rumble_run_teammate_play_TRLA_173',
								'rumble_run_teammate_play_TRLA_174',
								'rumble_run_teammate_play_TRLA_175',
								'rumble_run_teammate_play_TRLA_176',
								'rumble_run_teammate_play_TRLA_177',
								'rumble_run_teammate_play_TRLA_180',
								'rumble_run_teammate_play_TRLA_181',
								'rumble_run_teammate_play_TRLA_182',
								'rumble_run_teammate_play_TRLA_183',
								'rumble_run_teammate_play_TRLA_184',
								'rumble_run_teammate_play_TRLA_185',
								'rumble_run_teammate_play_TRLA_188',
								'rumble_run_teammate_play_TRLA_189',
								'rumble_run_teammate_play_TRLA_190',
								'rumble_run_teammate_play_TRLA_191',
								'rumble_run_teammate_play_TRLA_192',
								'rumble_run_teammate_play_TRLA_193',
							],
						},
						{
							id: 'rumble_run_passive',
							name: 'Passives',
							icon: 'achievements_passive',
							achievementTypes: [
								'rumble_run_passive_play_TRLA_801',
								'rumble_run_passive_play_TRLA_802',
								'rumble_run_passive_play_TRLA_803',
								'rumble_run_passive_play_TRLA_804',
								'rumble_run_passive_play_TRLA_805',
								'rumble_run_passive_play_TRLA_806',
								'rumble_run_passive_play_TRLA_807',
								'rumble_run_passive_play_TRLA_808',
								'rumble_run_passive_play_TRLA_809',
							],
						},
					],
				},

				{
					id: 'monster_hunt',
					name: 'Monster Hunt',
					icon: 'monster_hunt',
					categories: [
						{
							id: 'monster_hunt_progression',
							name: 'Progression',
							icon: 'achievements_progression',
							achievementTypes: [
								'monster_hunt_progression_GILA_400h',
								'monster_hunt_progression_GILA_500h3',
								'monster_hunt_progression_GILA_600h',
								'monster_hunt_progression_GILA_900h',
								'monster_hunt_final_boss',
							],
						},
						{
							id: 'monster_hunt_boss',
							name: 'Bosses',
							icon: 'achievements_boss',
							achievementTypes: [
								'monster_hunt_boss_GILA_BOSS_20h',
								'monster_hunt_boss_GILA_BOSS_21h',
								'monster_hunt_boss_GILA_BOSS_22h',
								'monster_hunt_boss_GILA_BOSS_23h',
								'monster_hunt_boss_GILA_BOSS_24h',
								'monster_hunt_boss_GILA_BOSS_25h',
								'monster_hunt_boss_GILA_BOSS_26h',
								'monster_hunt_boss_GILA_BOSS_27h',
								'monster_hunt_boss_GILA_BOSS_29h',
								'monster_hunt_boss_GILA_BOSS_30h',
								'monster_hunt_boss_GILA_BOSS_31h',
								'monster_hunt_boss_GILA_BOSS_32h',
								'monster_hunt_boss_GILA_BOSS_33h',
								'monster_hunt_boss_GILA_BOSS_34h',
								'monster_hunt_boss_GILA_BOSS_35h',
								'monster_hunt_boss_GILA_BOSS_36h',
								'monster_hunt_boss_GILA_BOSS_37h',
								'monster_hunt_boss_GILA_BOSS_38h',
								'monster_hunt_boss_GILA_BOSS_39h',
								'monster_hunt_boss_GILA_BOSS_40h',
								'monster_hunt_boss_GILA_BOSS_41h',
								'monster_hunt_boss_GILA_BOSS_42h',
								'monster_hunt_boss_GILA_BOSS_43h',
								'monster_hunt_boss_GILA_BOSS_44h',
								'monster_hunt_boss_GILA_BOSS_45h',
								'monster_hunt_boss_GILA_BOSS_46h',
								'monster_hunt_boss_GILA_BOSS_47h',
								'monster_hunt_boss_GILA_BOSS_48h',
								'monster_hunt_boss_GILA_BOSS_49h',
								'monster_hunt_boss_GILA_BOSS_50h',
								'monster_hunt_boss_GILA_BOSS_51h',
								'monster_hunt_boss_GILA_BOSS_52h',
								'monster_hunt_boss_GILA_BOSS_54h',
								'monster_hunt_boss_GILA_BOSS_55h',
								'monster_hunt_boss_GILA_BOSS_56h',
								'monster_hunt_boss_GILA_BOSS_57h',
								'monster_hunt_boss_GILA_BOSS_58h',
								'monster_hunt_boss_GILA_BOSS_59h',
								'monster_hunt_boss_GILA_BOSS_60h',
								'monster_hunt_boss_GILA_BOSS_61h',
								'monster_hunt_boss_GILA_BOSS_62h',
								'monster_hunt_boss_GILA_BOSS_63h',
								'monster_hunt_boss_GILA_BOSS_64h',
								'monster_hunt_boss_GILA_BOSS_65h',
								'monster_hunt_boss_GILA_BOSS_66h',
								'monster_hunt_boss_GILA_BOSS_67h',
								'monster_hunt_boss_GILA_BOSS_68h',
							],
						},
						{
							id: 'monster_hunt_treasure',
							name: 'Treasures',
							icon: 'achievements_treasure',
							achievementTypes: [
								'monster_hunt_treasure_play_GILA_401',
								'monster_hunt_treasure_play_GILA_403',
								'monster_hunt_treasure_play_GILA_410',
								'monster_hunt_treasure_play_GILA_411',
								'monster_hunt_treasure_play_GILA_412',
								'monster_hunt_treasure_play_GILA_413',
								'monster_hunt_treasure_play_GILA_501',
								'monster_hunt_treasure_play_GILA_503',
								'monster_hunt_treasure_play_GILA_506t',
								'monster_hunt_treasure_play_GILA_507',
								'monster_hunt_treasure_play_GILA_508',
								'monster_hunt_treasure_play_GILA_509',
								'monster_hunt_treasure_play_GILA_510',
								'monster_hunt_treasure_play_GILA_608',
								'monster_hunt_treasure_play_GILA_610',
								'monster_hunt_treasure_play_GILA_611',
								'monster_hunt_treasure_play_GILA_612',
								'monster_hunt_treasure_play_GILA_801',
								'monster_hunt_treasure_play_GILA_802',
								'monster_hunt_treasure_play_GILA_803',
								'monster_hunt_treasure_play_GILA_804',
								'monster_hunt_treasure_play_GILA_806',
								'monster_hunt_treasure_play_GILA_810',
								'monster_hunt_treasure_play_GILA_811',
								'monster_hunt_treasure_play_GILA_812',
								'monster_hunt_treasure_play_GILA_816a',
								'monster_hunt_treasure_play_GILA_816b',
								'monster_hunt_treasure_play_GILA_816c',
								'monster_hunt_treasure_play_GILA_817',
								'monster_hunt_treasure_play_GILA_818',
								'monster_hunt_treasure_play_GILA_819',
								'monster_hunt_treasure_play_GILA_820',
								'monster_hunt_treasure_play_GILA_821a',
								'monster_hunt_treasure_play_GILA_821b',
								'monster_hunt_treasure_play_GILA_821c',
								'monster_hunt_treasure_play_GILA_824',
								'monster_hunt_treasure_play_GILA_825',
								'monster_hunt_treasure_play_GILA_826',
								'monster_hunt_treasure_play_GILA_827',
								'monster_hunt_treasure_play_GILA_850b',
								'monster_hunt_treasure_play_GILA_851a',
								'monster_hunt_treasure_play_GILA_851b',
								'monster_hunt_treasure_play_GILA_851c',
								'monster_hunt_treasure_play_GILA_852a',
								'monster_hunt_treasure_play_GILA_852b',
								'monster_hunt_treasure_play_GILA_852c',
								'monster_hunt_treasure_play_GILA_853b',
								'monster_hunt_treasure_play_GILA_854',
								'monster_hunt_treasure_play_GILA_854t',
								'monster_hunt_treasure_play_GILA_901',
								'monster_hunt_treasure_play_GILA_903',
								'monster_hunt_treasure_play_GILA_904',
								'monster_hunt_treasure_play_GILA_906',
								'monster_hunt_treasure_play_GILA_907',
								'monster_hunt_treasure_play_GILA_910',
								'monster_hunt_treasure_play_GILA_BOSS_23t',
								'monster_hunt_treasure_play_GILA_BOSS_26t2',
								'monster_hunt_treasure_play_GILA_BOSS_27t',
								'monster_hunt_treasure_play_GILA_BOSS_29t',
								'monster_hunt_treasure_play_GILA_BOSS_33t',
								'monster_hunt_treasure_play_GILA_BOSS_37t',
								'monster_hunt_treasure_play_GILA_BOSS_43t',
								'monster_hunt_treasure_play_GILA_BOSS_57t',
							],
						},
						{
							id: 'monster_hunt_passive',
							name: 'Passives',
							icon: 'achievements_passive',
							achievementTypes: [
								'monster_hunt_passive_play_GILA_414',
								'monster_hunt_passive_play_GILA_415',
								'monster_hunt_passive_play_GILA_506',
								'monster_hunt_passive_play_GILA_511',
								'monster_hunt_passive_play_GILA_513',
								'monster_hunt_passive_play_GILA_602',
								'monster_hunt_passive_play_GILA_603',
								'monster_hunt_passive_play_GILA_605',
								'monster_hunt_passive_play_GILA_607',
								'monster_hunt_passive_play_GILA_805',
								'monster_hunt_passive_play_GILA_813',
								'monster_hunt_passive_play_GILA_814',
								'monster_hunt_passive_play_GILA_911',
								'monster_hunt_passive_play_GILA_913',
								'monster_hunt_passive_play_LOOTA_800',
								'monster_hunt_passive_play_LOOTA_801',
								'monster_hunt_passive_play_LOOTA_803',
								'monster_hunt_passive_play_LOOTA_804',
								'monster_hunt_passive_play_LOOTA_824',
								'monster_hunt_passive_play_LOOTA_825',
								'monster_hunt_passive_play_LOOTA_831',
							],
						},
					],
				},

				{
					id: 'dungeon_run',
					name: 'Dungeon Run',
					icon: 'dungeon_run',
					categories: [
						{
							id: 'dungeon_run_progression',
							name: 'Progression',
							icon: 'achievements_progression',
							achievementTypes: [
								'dungeon_run_progression_HERO_01',
								'dungeon_run_progression_HERO_02',
								'dungeon_run_progression_HERO_03',
								'dungeon_run_progression_HERO_04',
								'dungeon_run_progression_HERO_05',
								'dungeon_run_progression_HERO_06',
								'dungeon_run_progression_HERO_07',
								'dungeon_run_progression_HERO_08',
								'dungeon_run_progression_HERO_09',
							],
						},
						{
							id: 'dungeon_run_boss',
							name: 'Bosses',
							icon: 'achievements_boss',
							achievementTypes: [
								'dungeon_run_boss_LOOTA_BOSS_04h',
								'dungeon_run_boss_LOOTA_BOSS_05h',
								'dungeon_run_boss_LOOTA_BOSS_06h',
								'dungeon_run_boss_LOOTA_BOSS_09h',
								'dungeon_run_boss_LOOTA_BOSS_10h',
								'dungeon_run_boss_LOOTA_BOSS_11h',
								'dungeon_run_boss_LOOTA_BOSS_12h',
								'dungeon_run_boss_LOOTA_BOSS_13h',
								'dungeon_run_boss_LOOTA_BOSS_15h',
								'dungeon_run_boss_LOOTA_BOSS_16h',
								'dungeon_run_boss_LOOTA_BOSS_17h',
								'dungeon_run_boss_LOOTA_BOSS_18h',
								'dungeon_run_boss_LOOTA_BOSS_19h',
								'dungeon_run_boss_LOOTA_BOSS_20h',
								'dungeon_run_boss_LOOTA_BOSS_21h',
								'dungeon_run_boss_LOOTA_BOSS_22h',
								'dungeon_run_boss_LOOTA_BOSS_23h',
								'dungeon_run_boss_LOOTA_BOSS_24h',
								'dungeon_run_boss_LOOTA_BOSS_25h',
								'dungeon_run_boss_LOOTA_BOSS_26h',
								'dungeon_run_boss_LOOTA_BOSS_27h',
								'dungeon_run_boss_LOOTA_BOSS_28h',
								'dungeon_run_boss_LOOTA_BOSS_29h',
								'dungeon_run_boss_LOOTA_BOSS_30h',
								'dungeon_run_boss_LOOTA_BOSS_31h',
								'dungeon_run_boss_LOOTA_BOSS_33h',
								'dungeon_run_boss_LOOTA_BOSS_34h',
								'dungeon_run_boss_LOOTA_BOSS_35h',
								'dungeon_run_boss_LOOTA_BOSS_36h',
								'dungeon_run_boss_LOOTA_BOSS_37h',
								'dungeon_run_boss_LOOTA_BOSS_38h',
								'dungeon_run_boss_LOOTA_BOSS_39h',
								'dungeon_run_boss_LOOTA_BOSS_40h',
								'dungeon_run_boss_LOOTA_BOSS_41h',
								'dungeon_run_boss_LOOTA_BOSS_42h',
								'dungeon_run_boss_LOOTA_BOSS_43h',
								'dungeon_run_boss_LOOTA_BOSS_44h',
								'dungeon_run_boss_LOOTA_BOSS_45h',
								'dungeon_run_boss_LOOTA_BOSS_46h',
								'dungeon_run_boss_LOOTA_BOSS_47h',
								'dungeon_run_boss_LOOTA_BOSS_48h',
								'dungeon_run_boss_LOOTA_BOSS_49h',
								'dungeon_run_boss_LOOTA_BOSS_50h',
								'dungeon_run_boss_LOOTA_BOSS_51h',
								'dungeon_run_boss_LOOTA_BOSS_52h',
								'dungeon_run_boss_LOOTA_BOSS_53h',
								'dungeon_run_boss_LOOTA_BOSS_54h',
								'dungeon_run_boss_LOOTA_BOSS_99h',
							],
						},
						{
							id: 'dungeon_run_treasure',
							name: 'Treasures',
							icon: 'achievements_treasure',
							achievementTypes: [
								'dungeon_run_treasure_play_LOOT_998k',
								'dungeon_run_treasure_play_LOOT_998l',
								'dungeon_run_treasure_play_LOOTA_805',
								'dungeon_run_treasure_play_LOOTA_806',
								'dungeon_run_treasure_play_LOOTA_811',
								'dungeon_run_treasure_play_LOOTA_812',
								'dungeon_run_treasure_play_LOOTA_813',
								'dungeon_run_treasure_play_LOOTA_814',
								'dungeon_run_treasure_play_LOOTA_816',
								'dungeon_run_treasure_play_LOOTA_817',
								'dungeon_run_treasure_play_LOOTA_819',
								'dungeon_run_treasure_play_LOOTA_820',
								'dungeon_run_treasure_play_LOOTA_821',
								'dungeon_run_treasure_play_LOOTA_822',
								'dungeon_run_treasure_play_LOOTA_823',
								'dungeon_run_treasure_play_LOOTA_826',
								'dungeon_run_treasure_play_LOOTA_827',
								'dungeon_run_treasure_play_LOOTA_829',
								'dungeon_run_treasure_play_LOOTA_830',
								'dungeon_run_treasure_play_LOOTA_834',
								'dungeon_run_treasure_play_LOOTA_835',
								'dungeon_run_treasure_play_LOOTA_836',
								'dungeon_run_treasure_play_LOOTA_837',
								'dungeon_run_treasure_play_LOOTA_838',
								'dungeon_run_treasure_play_LOOTA_839',
								'dungeon_run_treasure_play_LOOTA_840',
								'dungeon_run_treasure_play_LOOTA_841',
								'dungeon_run_treasure_play_LOOTA_842',
								'dungeon_run_treasure_play_LOOTA_842a',
								'dungeon_run_treasure_play_LOOTA_842b',
								'dungeon_run_treasure_play_LOOTA_843',
								'dungeon_run_treasure_play_LOOTA_847',
							],
						},
						{
							id: 'dungeon_run_passive',
							name: 'Passives',
							icon: 'achievements_passive',
							achievementTypes: [
								'dungeon_run_passive_play_LOOTA_800',
								'dungeon_run_passive_play_LOOTA_801',
								'dungeon_run_passive_play_LOOTA_802',
								'dungeon_run_passive_play_LOOTA_803',
								'dungeon_run_passive_play_LOOTA_804',
								'dungeon_run_passive_play_LOOTA_818',
								'dungeon_run_passive_play_LOOTA_824',
								'dungeon_run_passive_play_LOOTA_825',
								'dungeon_run_passive_play_LOOTA_828',
								'dungeon_run_passive_play_LOOTA_831',
								'dungeon_run_passive_play_LOOTA_832',
								'dungeon_run_passive_play_LOOTA_833',
								'dungeon_run_passive_play_LOOTA_845',
								'dungeon_run_passive_play_LOOTA_846',
							],
						},
					],
				},
			],
		};

		return categoryConfiguration.categories.map(category => this.buildCategory(category, achievements));
	}

	private buildCategory(
		category: AchievementCategoryConfiguration,
		achievements: readonly VisualAchievement[],
	): VisualAchievementCategory {
		return VisualAchievementCategory.create({
			id: category.id,
			name: category.name,
			icon: category.icon,
			achievements: this.buildAchievements(category.achievementTypes, achievements),
			categories:
				(category.categories?.map(cat =>
					this.buildCategory(cat, achievements),
				) as readonly VisualAchievementCategory[]) || [],
			// TODO: make that configurable via data
			filterOptions: this.filterOptions(),
		} as VisualAchievementCategory);
	}

	private buildAchievements(
		achievementTypes: readonly string[],
		achievements: readonly VisualAchievement[],
	): readonly VisualAchievement[] {
		if (!achievementTypes) {
			return [];
		}
		return achievements.filter(ach => achievementTypes.includes(ach.type));
	}

	public static buildCompletionSteps(
		achievementForCompletionSteps: readonly (Achievement | CompletionStep)[],
		achievement: Achievement,
		text: string,
	): [readonly CompletionStep[], string] {
		const areProgressionSteps =
			achievementForCompletionSteps
				.map(achv => achv.priority)
				.filter((value, index, self) => self.indexOf(value) === index).length !== 1;
		// console.log('[completion-steps] areProgressionSteps', areProgressionSteps);
		const invertedCompletionSteps = [];
		let alreadyDefinedText = achievement.text || false;
		// Useful to make sure we have some consistency in the number of comletions
		let maxNumberOfCompletions = 0;
		for (let i = achievementForCompletionSteps.length - 1; i >= 0; i--) {
			const achv = achievementForCompletionSteps[i];
			// console.log('[completion-steps] handling step', achv);
			const completions: number = areProgressionSteps
				? Math.max(maxNumberOfCompletions, achv.numberOfCompletions)
				: achv.numberOfCompletions;
			// console.log('[completion-steps] completions', completions);
			maxNumberOfCompletions = completions;
			if (completions > 0 && !alreadyDefinedText) {
				text = achv.completedText;
				alreadyDefinedText = true;
			}
			invertedCompletionSteps.push({
				id: `${achv.id}`,
				numberOfCompletions: areProgressionSteps ? completions : achv.numberOfCompletions,
				icon: achv.icon,
				completedText: achv.completedText,
				priority: achv.priority,
				text(showTimes = false): string {
					const times = ``;
					return `${achv.completedText} <span class="number-of-times">${times}</span>`;
				},
			} as CompletionStep);
		}
		// console.log('[completion-steps] invertedCompletionSteps', invertedCompletionSteps);
		return [invertedCompletionSteps.reverse() as readonly CompletionStep[], text];
	}

	private isAchievementVisualRoot(achievement: Achievement): boolean {
		return achievement.root;
	}

	protected filterOptions(): readonly FilterOption[] {
		return [
			{
				value: 'ALL_ACHIEVEMENTS',
				label: 'All achievements',
				filterFunction: a => true,
				emptyStateIcon: 'empty_state_Only_cards_I_have_illustration',
				emptyStateTitle: 'Holy Moly, you are epic!',
				emptyStateText: '100% of achievements in this category complete.',
			},
			{
				value: 'ONLY_MISSING',
				label: 'Incomplete achievements',
				filterFunction: (a: VisualAchievement) => {
					return a.completionSteps.some(step => step.numberOfCompletions === 0);
				},
				emptyStateIcon: 'empty_state_Only_cards_I_don’t_have_illustration',
				emptyStateTitle: 'Tons of achievements are awaiting you!',
				emptyStateText: 'Find them listed here once completed.',
			},
			{
				value: 'ONLY_COMPLETED',
				label: 'Completed achievements',
				filterFunction: (a: VisualAchievement) => {
					return a.completionSteps.every(step => step.numberOfCompletions > 0);
				},
				emptyStateIcon: 'empty_state_Only_cards_I_have_illustration',
				emptyStateTitle: 'Tons of achievements are awaiting you!',
				emptyStateText: 'Find them listed here once completed.',
			},
		];
	}

	private waitForInit(): Promise<void> {
		return new Promise<void>(resolve => {
			const dbWait = () => {
				if (this.categories) {
					resolve();
				} else {
					// console.log('[achievement-repository] waiting for DB init');
					setTimeout(() => dbWait(), 50);
				}
			};
			dbWait();
		});
	}
}

export interface AchievementConfiguration {
	categories: readonly AchievementCategoryConfiguration[];
}

export interface AchievementCategoryConfiguration {
	id: string;
	name: string;
	icon: string;
	categories?: readonly AchievementCategoryConfiguration[];
	achievementTypes?: readonly string[];
}
