/**
 * TODO(release 35.4 event): replace with real player/hero enchant {@link CardIds} from the live client.
 */
export const PLACEHOLDER_ANIMAL_COMPANION_PLAYER_ENCHANT = 'TODO_TEMP_ANIMAL_COMPANION_ENCHANT';
export const PLACEHOLDER_LEYLINE_SPELL_COST_PLAYER_ENCHANT = 'TODO_TEMP_LEYLINE_SPELL_COST_ENCHANT';
export const PLACEHOLDER_LEYLINE_BONUS_TRIGGERS_ENCHANT = 'TODO_TEMP_LEYLINE_BONUS_TRIGGERS_ENCHANT';
export const PLACEHOLDER_SILVER_HAND_RECRUIT_PLAYER_ENCHANT = 'TODO_TEMP_SILVER_HAND_RECRUIT_ENCHANT';
export const PLACEHOLDER_TALYA_EARTHSTRIDER_GLOBAL_ENCHANT = 'TODO_TEMP_TALYA_EARTHSTRIDER_GLOBAL_ENCHANT';
