/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by build-reverse-mappings.ts
 * SPELL-SPECIFIC REVERSE SYNERGIES
 */

import { CardIds } from '@firestone-hs/reference-data';
import { CardsFacadeService, HighlightSide } from '@firestone/shared/framework/core';
import { Selector } from '../cards-highlight-common.service';
import { and, or, side, inDeck, inHand, cardIs } from '../selectors';

export const reverseSpellSelector = (
	cardId: string,
	inputSide: HighlightSide,
	allCards: CardsFacadeService,
): Selector | null => {
	const refCard = allCards.getCard(cardId);
	if (!refCard) return null;

	const matchingCardIds: CardIds[] = [];

	// COST_MORE_0 + HAS_MECHANIC_GENERATES_SPELL + SHADOW (1 cards)
	if (refCard.cost != null && refCard.cost > 0 && refCard.mechanics?.includes('GENERATES_SPELL') && refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		matchingCardIds.push(
			CardIds.TamsinRoame_BAR_918
		);
	}

	// COST_MORE_0 + SHADOW + SPELL (1 cards)
	if (refCard.cost != null && refCard.cost > 0 && refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.TamsinRoame_BAR_918
		);
	}

	// FIRE + HAS_MECHANIC_DEAL_DAMAGE + SPELL (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE' && refCard.mechanics?.includes('DEAL_DAMAGE') && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.Saruun_GDB_304
		);
	}

	// ARCANE + HAS_MECHANIC_GENERATES_SPELL (7 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE' && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.AzureQueenSindragosa_AzureKingMalygosToken_TIME_852t1,
			CardIds.AzureQueenSindragosa_TIME_852,
			CardIds.LadyNazjar_TID_709,
			CardIds.MagistersApprentice,
			CardIds.StarlightReactor_GDB_108,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.Vexallus
		);
	}

	// ARCANE + SPELL (11 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.AzureQueenSindragosa_AzureKingMalygosToken_TIME_852t1,
			CardIds.AzureQueenSindragosa_TIME_852,
			CardIds.HalduronBrightwing,
			CardIds.LadyNazjar_TID_709,
			CardIds.MagistersApprentice,
			CardIds.SilvermoonFarstrider_RLK_826,
			CardIds.SorcerersGambit,
			CardIds.Stargazing_WW_425,
			CardIds.StarlightReactor_GDB_108,
			CardIds.UnstableMagicTavernBrawl,
			CardIds.Vexallus
		);
	}

	// COST_EQUAL_1 + HAS_MECHANIC_GENERATES_SPELL (2 cards)
	if (refCard.cost === 1 && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.Gazlowe,
			CardIds.NiriOfTheCrater_TLC_836
		);
	}

	// COST_EQUAL_1 + SPELL (3 cards)
	if (refCard.cost === 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.Gazlowe,
			CardIds.NiriOfTheCrater_TLC_836,
			CardIds.TrinketTracker
		);
	}

	// COST_EQUAL_2 + SPELL (2 cards)
	if (refCard.cost === 2 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.BarakKodobane_BAR_551,
			CardIds.BarakKodobane_CORE_BAR_551
		);
	}

	// COST_EQUAL_8 + SPELL (1 cards)
	if (refCard.cost === 8 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.ArcaneBrilliance
		);
	}

	// COST_LESS_3 + SPELL (2 cards)
	if (refCard.cost != null && refCard.cost < 3 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.SunsapperLynessa_VAC_507,
			CardIds.VioletTreasuregill_TLC_438
		);
	}

	// COST_LESS_4 + SPELL (1 cards)
	if (refCard.cost != null && refCard.cost < 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.StonehearthVindicator
		);
	}

	// COST_LESS_5 + SPELL (1 cards)
	if (refCard.cost != null && refCard.cost < 5 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.CracklingCloudstrider_CATA_563
		);
	}

	// COST_MORE_1 + HAS_MECHANIC_GENERATES_SPELL (1 cards)
	if (refCard.cost != null && refCard.cost > 1 && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.PlaguebringerTavernBrawl
		);
	}

	// COST_MORE_1 + SPELL (1 cards)
	if (refCard.cost != null && refCard.cost > 1 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.PlaguebringerTavernBrawl
		);
	}

	// COST_MORE_4 + SPELL (7 cards)
	if (refCard.cost != null && refCard.cost > 4 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.AshleafPixie_FIR_961,
			CardIds.BumblingBellhop_VAC_521,
			CardIds.FaeTrickster_EDR_571,
			CardIds.Groundskeeper,
			CardIds.HagathaTheFabled_TOY_504,
			CardIds.SunreaverWarmage,
			CardIds.WeaverOfTheCycle_EDR_472
		);
	}

	// COST_MORE_5 + HAS_MECHANIC_GENERATES_SPELL (1 cards)
	if (refCard.cost != null && refCard.cost > 5 && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.GreySageParrot
		);
	}

	// COST_MORE_5 + SPELL (1 cards)
	if (refCard.cost != null && refCard.cost > 5 && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.GreySageParrot
		);
	}

	// FEL + HAS_MECHANIC_GENERATES_SPELL (5 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL' && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.FelfireBlaze_FIR_904,
			CardIds.HeraldOfChaos,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.WitherTheWeakTavernBrawl
		);
	}

	// FEL + SPELL (16 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.FelfireBlaze_FIR_904,
			CardIds.FelfireInTheHole,
			CardIds.Felgorger_SW_043,
			CardIds.FossilFanatic,
			CardIds.GraveDefiler,
			CardIds.HeraldOfChaos,
			CardIds.IllidanStormrage_FelInside_THD_004p,
			CardIds.ImpCredibleTrousersTavernBrawl,
			CardIds.JaceDarkweaver,
			CardIds.LoadTheChamber_WW_409,
			CardIds.MalevolentMutant_CATA_697,
			CardIds.NespirahEnthralled_CATA_527,
			CardIds.PopgarThePutrid_WW_091,
			CardIds.RavenousFelfisher_CATA_529,
			CardIds.Scorchreaver_FIR_952,
			CardIds.WitherTheWeakTavernBrawl
		);
	}

	// FIRE + HAS_MECHANIC_GENERATES_SPELL (11 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE' && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.FirekeepersIdolTavernBrawl,
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.GrandMagusAntonidas,
			CardIds.HotStreak,
			CardIds.InfernoHerald_FIR_913,
			CardIds.LadyNazjar_TID_709,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.SunfuryChampion,
			CardIds.Thoribelore
		);
	}

	// FIRE + SPELL (18 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.EruptingVolcano_CATA_584,
			CardIds.FirekeepersIdolTavernBrawl,
			CardIds.FlameWavesTavernBrawl,
			CardIds.FlamesOfTheKirinTorTavernBrawl,
			CardIds.GrandMagusAntonidas,
			CardIds.HotStreak,
			CardIds.InfernoHerald_FIR_913,
			CardIds.LadyNazjar_TID_709,
			CardIds.LivingFlame_FIR_929,
			CardIds.MechanizedMagma_TLC_224,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.ScorchingWinds_FIR_910,
			CardIds.SorcerersGambit,
			CardIds.SteamGuardian,
			CardIds.SunfuryChampion,
			CardIds.Thoribelore,
			CardIds.VolcanicThrasher_TLC_223,
			CardIds.WrathspineEnchanter
		);
	}

	// FROST + HAS_MECHANIC_GENERATES_SPELL (6 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST' && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.IceRevenant,
			CardIds.LadyNazjar_TID_709,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.Rimetongue
		);
	}

	// FROST + SPELL (15 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.FrostweaveDungeoneer,
			CardIds.GlacialDownpourTavernBrawl,
			CardIds.HarbingerOfWinterCore_RLK_511,
			CardIds.HeraldOfLokholar,
			CardIds.IceRevenant,
			CardIds.LadyDeathwhisper_RLK_713,
			CardIds.LadyNazjar_TID_709,
			CardIds.NorthernNavigation,
			CardIds.OverseerFrigidaraCore_RLK_Prologue_RLK_224,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.RambunctiousStuffy_TOY_821,
			CardIds.Rimetongue,
			CardIds.SorcerersGambit,
			CardIds.WatercolorArtist_TOY_376,
			CardIds.WrathspineEnchanter
		);
	}

	// HAS_MECHANIC_CHOOSE_ONE + HAS_MECHANIC_GENERATES_SPELL (1 cards)
	if (refCard.mechanics?.includes('CHOOSE_ONE') && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.KeeperStalladris
		);
	}

	// HAS_MECHANIC_CHOOSE_ONE + SPELL (3 cards)
	if (refCard.mechanics?.includes('CHOOSE_ONE') && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.JerryRigCarpenter,
			CardIds.KeeperStalladris,
			CardIds.Pathmaker
		);
	}

	// HAS_MECHANIC_DEAL_DAMAGE + HAS_MECHANIC_GENERATES_SPELL (1 cards)
	if (refCard.mechanics?.includes('DEAL_DAMAGE') && refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.EtherealOracle_GDB_310
		);
	}

	// HAS_MECHANIC_DEAL_DAMAGE + SPELL (2 cards)
	if (refCard.mechanics?.includes('DEAL_DAMAGE') && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.EtherealOracle_GDB_310,
			CardIds.VelensChosen
		);
	}

	// HAS_MECHANIC_GENERATES_SPELL + HOLY (15 cards)
	if (refCard.mechanics?.includes('GENERATES_SPELL') && refCard.spellSchool?.toUpperCase() === 'HOLY') {
		matchingCardIds.push(
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.FlickeringLightbot_MIS_918,
			CardIds.GladesongSiren_TLC_819,
			CardIds.GuardianLightTavernBrawl,
			CardIds.HeraldOfLight,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.InvigoratingLightTavernBrawl,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ReachEquilibrium_TLC_817,
			CardIds.StarlightGroove,
			CardIds.TheGardensGrace,
			CardIds.VeteranWarmedic,
			CardIds.VeteranWarmedic_CORE_BAR_878
		);
	}

	// HAS_MECHANIC_GENERATES_SPELL + NATURE (9 cards)
	if (refCard.mechanics?.includes('GENERATES_SPELL') && refCard.spellSchool?.toUpperCase() === 'NATURE') {
		matchingCardIds.push(
			CardIds.DeviateDreadfang,
			CardIds.GroveShaper_EDR_271,
			CardIds.HeraldOfNature,
			CardIds.IronRootsTavernBrawl,
			CardIds.MendingPoolsTavernBrawl,
			CardIds.PrimordialOverseer_TIME_213,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.TopiorTheShrubbagazzor
		);
	}

	// HAS_MECHANIC_GENERATES_SPELL + PROTOSS (2 cards)
	if (refCard.mechanics?.includes('GENERATES_SPELL') && refCard.mechanics?.includes('PROTOSS')) {
		matchingCardIds.push(
			CardIds.Colossus_SC_758,
			CardIds.ShieldBattery_SC_759
		);
	}

	// HAS_MECHANIC_GENERATES_SPELL + SHADOW (8 cards)
	if (refCard.mechanics?.includes('GENERATES_SPELL') && refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		matchingCardIds.push(
			CardIds.EerieStoneTavernBrawl,
			CardIds.GladesongSiren_TLC_819,
			CardIds.HeraldOfShadows,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.ReachEquilibrium_TLC_817,
			CardIds.ShadowclothNeedle,
			CardIds.StaffOfPainTavernBrawl
		);
	}

	// HAS_MECHANIC_SECRET + SPELL (25 cards)
	if (refCard.mechanics?.includes('SECRET') && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.ApexisSmuggler,
			CardIds.ArcaneFlakmage,
			CardIds.BlackjackStunner,
			CardIds.CannonmasterSmythe_BAR_879,
			CardIds.CloakedHuntress_CORE_KAR_006,
			CardIds.CloakedHuntress_KAR_006,
			CardIds.CommanderRhyssa,
			CardIds.ContractConjurer,
			CardIds.Halkias,
			CardIds.InconspicuousRider,
			CardIds.LesserEmeraldSpellstone,
			CardIds.LesserEmeraldSpellstone_EmeraldSpellstoneToken,
			CardIds.LesserEmeraldSpellstone_GreaterEmeraldSpellstoneToken,
			CardIds.MedivhsValet,
			CardIds.OrionMansionManager,
			CardIds.PettingZoo,
			CardIds.PhaseStalker,
			CardIds.ProfessorPutricide_CORE_ICC_204,
			CardIds.ProfessorPutricide_ICC_204,
			CardIds.SaygeSeerOfDarkmoon,
			CardIds.SecretkeeperLegacy,
			CardIds.SecretkeeperVanilla,
			CardIds.SparkjoyCheat,
			CardIds.StarstrungBow,
			CardIds.SwordOfTheFallen
		);
	}

	// HAS_SPELL_SCHOOL + SPELL (9 cards)
	if (!!refCard.spellSchool && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.CoralKeeper,
			CardIds.DiscoveryOfMagic,
			CardIds.ElementalInspiration,
			CardIds.InquisitiveCreation,
			CardIds.MagisterDawngrasp_AV_200,
			CardIds.Multicaster,
			CardIds.RazzleDazzler_VAC_301,
			CardIds.Sif,
			CardIds.WisdomOfNorgannon
		);
	}

	// HOLY + SPELL (21 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.CarielRoame_BAR_902,
			CardIds.DevoutDungeoneer,
			CardIds.FlickeringLightbot_FlickeringLightbotToken_MIS_918t,
			CardIds.FlickeringLightbot_MIS_918,
			CardIds.GladesongSiren_TLC_819,
			CardIds.GuardianLightTavernBrawl,
			CardIds.HeraldOfLight,
			CardIds.HiHoSilverwing_WW_344,
			CardIds.HolyCowboy_WW_335,
			CardIds.HolyGlowsticks_MIS_709,
			CardIds.InvigoratingLightTavernBrawl,
			CardIds.KureTheLightBeyond_GDB_442,
			CardIds.LightmawNetherdrake,
			CardIds.ReachEquilibrium_CleanseTheShadowToken_TLC_817t,
			CardIds.ReachEquilibrium_TLC_817,
			CardIds.ShimmeringSunfish,
			CardIds.SpiritGuide_CORE_AV_328,
			CardIds.StarlightGroove,
			CardIds.TheGardensGrace,
			CardIds.VeteranWarmedic,
			CardIds.VeteranWarmedic_CORE_BAR_878
		);
	}

	// NATURE + SPELL (15 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.DeviateDreadfang,
			CardIds.GroveShaper_EDR_271,
			CardIds.HamuulRunetotem_EDR_845,
			CardIds.HeraldOfNature,
			CardIds.IronRootsTavernBrawl,
			CardIds.MendingPoolsTavernBrawl,
			CardIds.Overheat_FIR_906,
			CardIds.PrimalDungeoneer,
			CardIds.PrimordialOverseer_TIME_213,
			CardIds.RadianceOfAzshara_TSC_635,
			CardIds.SpreadingSaplingsTavernBrawl,
			CardIds.ToadOfTheWilds,
			CardIds.TopiorTheShrubbagazzor,
			CardIds.WidowbloomSeedsman,
			CardIds.WrathspineEnchanter
		);
	}

	// PROTOSS + SPELL (2 cards)
	if (refCard.mechanics?.includes('PROTOSS') && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.Colossus_SC_758,
			CardIds.ShieldBattery_SC_759
		);
	}

	// SHADOW + SPELL (15 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW' && refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.EerieStoneTavernBrawl,
			CardIds.GladesongSiren_TLC_819,
			CardIds.HeraldOfShadows,
			CardIds.KaraTheDarkStar_GDB_127,
			CardIds.LadyDarkvein,
			CardIds.LadyDarkvein_CORE_REV_373,
			CardIds.LightmawNetherdrake,
			CardIds.ReachEquilibrium_CorruptTheLightToken_TLC_817t2,
			CardIds.ReachEquilibrium_TLC_817,
			CardIds.Shadowborn,
			CardIds.ShadowclothNeedle,
			CardIds.SketchArtist_TOY_916,
			CardIds.SpiritGuide_CORE_AV_328,
			CardIds.StaffOfPainTavernBrawl,
			CardIds.TwilightDeceptor
		);
	}

	// ARCANE (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'ARCANE') {
		matchingCardIds.push(
			CardIds.ArcaneFluxTavernBrawl,
			CardIds.ArcaneQuiver_RLK_817,
			CardIds.ArcaniteCrystalTavernBrawl
		);
	}

	// FEL (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FEL') {
		matchingCardIds.push(
			CardIds.CorruptedFelstoneTavernBrawl
		);
	}

	// FIRE (1 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FIRE') {
		matchingCardIds.push(
			CardIds.BlazingAccretion_GDB_302
		);
	}

	// FROST (2 cards)
	if (refCard.spellSchool?.toUpperCase() === 'FROST') {
		matchingCardIds.push(
			CardIds.OverseerFrigidaraCore_RLK_224,
			CardIds.OverseerFrigidara_LEG_RLK_224
		);
	}

	// HAS_MECHANIC_GENERATES_SPELL (128 cards)
	if (refCard.mechanics?.includes('GENERATES_SPELL')) {
		matchingCardIds.push(
			CardIds.AncientKrakenbane,
			CardIds.AnimatedMoonwell_EDR_254,
			CardIds.ArcaneArtificer,
			CardIds.ArcaneArtificerCore,
			CardIds.ArchmageAntonidas,
			CardIds.ArchmageAntonidasLegacy,
			CardIds.ArchmageAntonidas_CORE_EX1_559,
			CardIds.ArchmageKalec_CATA_458,
			CardIds.ArchmageVargoth,
			CardIds.ArrowSmith,
			CardIds.BabaNaga,
			CardIds.Bloodbloom,
			CardIds.BrollBearmantle_EDR_853,
			CardIds.CardGrader_TOY_054,
			CardIds.ChattyMacaw_VAC_407,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_SCH_Active48,
			CardIds.ClockworkAssistantTavernBrawl_PVPDR_Toki_T5,
			CardIds.ClockworkAssistant_GILA_907,
			CardIds.ClockworkAssistant_ONY_005ta11,
			CardIds.CoilskarCommander,
			CardIds.CommanderSivara_TSC_087,
			CardIds.Conductivity_YOG_522,
			CardIds.ContaminatedLasher_YOG_528,
			CardIds.CosmicKeyboard,
			CardIds.CrushclawEnforcer,
			CardIds.DarkmoonMagician_MIS_303,
			CardIds.Deathchiller_CORE_RLK_083,
			CardIds.Deathchiller_RLK_083,
			CardIds.DoubleTime,
			CardIds.DozingKelpkeeper,
			CardIds.ExarchHataaru_TheGalaxysLensToken_GDB_136t,
			CardIds.FarseerNobundo_GDB_447,
			CardIds.FarseerWo_TIME_013,
			CardIds.FelscaleEvoker,
			CardIds.Flamewaker,
			CardIds.Flamewaker_TUTR_BRM_002,
			CardIds.FragmentOfNothing_END_026,
			CardIds.GlacialAdvance_RLK_512,
			CardIds.GolgannethTheThunderer,
			CardIds.GuidingFigure_GDB_106,
			CardIds.HallazealTheAscended,
			CardIds.HallazealTheAscended_WON_336,
			CardIds.Handmaiden,
			CardIds.HedraTheHeretic_TSC_658,
			CardIds.HighAbbessAlura,
			CardIds.IdolsOfEluneTavernBrawl,
			CardIds.InkmasterSolia,
			CardIds.JungleJammer,
			CardIds.KhadgarsScryingOrb,
			CardIds.KingKrush_KingsDecree_THD_012p,
			CardIds.KingTide_VAC_524,
			CardIds.KolkarPackRunner,
			CardIds.LadyStheno_TSC_218,
			CardIds.LearnDraconic,
			CardIds.LightOfTheNewMoon_FIR_918,
			CardIds.LinaShopManager_TOY_531,
			CardIds.LockAndLoad_AT_061,
			CardIds.LockAndLoad_CORE_AT_061,
			CardIds.LockAndLoad_WON_023,
			CardIds.LorewalkerChoLegacy,
			CardIds.LorewalkerChoVanilla,
			CardIds.LorewalkerCho_CORE_EX1_100,
			CardIds.LoveEverlasting,
			CardIds.ManaCyclone,
			CardIds.MantleShaper_DEEP_004,
			CardIds.MaroonedArchmage_VAC_435,
			CardIds.MarshlandThresher_TLC_256,
			CardIds.Marshspawn_BT_115,
			CardIds.Marshspawn_CORE_BT_115,
			CardIds.MeddlesomeServant_YOG_518,
			CardIds.MedivhTheHallowed_AtieshTheGreatstaffToken_TIME_890t,
			CardIds.MistahVistah_VAC_519,
			CardIds.MurkwaterScribe,
			CardIds.NagaGiant,
			CardIds.NordrassilDruid,
			CardIds.NordrassilDruidLegacy,
			CardIds.NostalgicInitiate_NostalgicInitiateToken_TOY_340t1,
			CardIds.NostalgicInitiate_TOY_340,
			CardIds.OopsAllSpellsTavernBrawl,
			CardIds.ParchedDesperado_WW_407,
			CardIds.PartyPortalTavernBrawl_PVPDR_SCH_Active08,
			CardIds.PreparationCore,
			CardIds.PreparationLegacy,
			CardIds.PreparationVanilla,
			CardIds.PriestessValishj,
			CardIds.PrisonBreaker_YOG_411,
			CardIds.Pyrotechnician,
			CardIds.QueenAzshara_TSC_641,
			CardIds.Queensguard,
			CardIds.RaidTheSkyTemple,
			CardIds.RajNazjan,
			CardIds.RayllaSandSculptor_VAC_424,
			CardIds.RhoninsScryingOrbTavernBrawl,
			CardIds.RimescaleSiren,
			CardIds.RingOfRefreshmentTavernBrawl,
			CardIds.RitualOfTheNewMoon_EDR_461,
			CardIds.SaroniteShambler_YOG_521,
			CardIds.SethekkVeilweaver,
			CardIds.ShadowOfDemise,
			CardIds.ShadowOfDemise_CORE_RLK_567,
			CardIds.ShatariCloakfield_GDB_103,
			CardIds.ShirvallahTheTiger,
			CardIds.SlitheringDeathscale,
			CardIds.SpectralTrainee,
			CardIds.Spellcoiler,
			CardIds.SpitelashSiren,
			CardIds.SunstridersCrownTavernBrawl,
			CardIds.SwiftscaleTrickster,
			CardIds.TheFistOfRaDen,
			CardIds.TheGalacticProjectionOrb_TOY_378,
			CardIds.TidePools_VAC_522,
			CardIds.TidepoolPupil_VAC_304,
			CardIds.TwinbowTerrorcoil,
			CardIds.Tyrande_EDR_464,
			CardIds.UmbralOwl,
			CardIds.UmbralOwl_CORE_DMF_060,
			CardIds.ViciousSlitherspear_CORE_TSC_827,
			CardIds.ViciousSlitherspear_TSC_827,
			CardIds.Whirlweaver,
			CardIds.WickedWitchdoctor,
			CardIds.WickedWitchdoctor_WON_083,
			CardIds.WildPyromancerCore,
			CardIds.WildPyromancerLegacy,
			CardIds.WildPyromancerVanilla,
			CardIds.WishOfTheNewMoon_EDR_460,
			CardIds.YoggSaronHopesEnd_OG_134,
			CardIds.YoggSaronMasterOfFate,
			CardIds.YsielWindsinger
		);
	}

	// HAS_MECHANIC_SECRET (24 cards)
	if (refCard.mechanics?.includes('SECRET')) {
		matchingCardIds.push(
			CardIds.AncientMysteries,
			CardIds.AnonymousInformant,
			CardIds.AnonymousInformant_CORE_REV_841,
			CardIds.Arcanologist,
			CardIds.ArcanologistCore,
			CardIds.ChattyBartender,
			CardIds.CostumedSinger,
			CardIds.DunBaldarBunker,
			CardIds.EaglehornBowLegacy,
			CardIds.EaglehornBowVanilla,
			CardIds.GhastlyGravedigger,
			CardIds.GlacialMysteries_CORE_ICC_086,
			CardIds.GlacialMysteries_ICC_086,
			CardIds.KabalCrystalRunner,
			CardIds.KabalCrystalRunner_WON_308,
			CardIds.MadScientist,
			CardIds.MysteriousChallenger,
			CardIds.MysteriousChallenger_WON_334,
			CardIds.PrivateEye,
			CardIds.Product9_MIS_914,
			CardIds.ScuttlebuttGhoul,
			CardIds.ScuttlebuttGhoul_CORE_REV_900,
			CardIds.SecretStudiesTavernBrawl,
			CardIds.SpringTheTrap
		);
	}

	// HAS_MECHANIC_SPELLPOWER (3 cards)
	if (refCard.mechanics?.includes('SPELLPOWER')) {
		matchingCardIds.push(
			CardIds.BottomlessToyChest_TOY_851,
			CardIds.SorcerousSubstitute,
			CardIds.WoodlandWonders_TOY_804
		);
	}

	// HAS_SPELL_SCHOOL (3 cards)
	if (!!refCard.spellSchool) {
		matchingCardIds.push(
			CardIds.Buttons_VAC_437,
			CardIds.CabaretHeadliner_VAC_954,
			CardIds.CarressCabaretStar_VAC_449
		);
	}

	// HOLY (3 cards)
	if (refCard.spellSchool?.toUpperCase() === 'HOLY') {
		matchingCardIds.push(
			CardIds.CreatureOfTheSacredCave_TLC_430,
			CardIds.DivineIlluminationTavernBrawl,
			CardIds.SpiritGuide
		);
	}

	// NATURE (2 cards)
	if (refCard.spellSchool?.toUpperCase() === 'NATURE') {
		matchingCardIds.push(
			CardIds.ChampionOfStorms,
			CardIds.CrashOfThunder
		);
	}

	// SHADOW (4 cards)
	if (refCard.spellSchool?.toUpperCase() === 'SHADOW') {
		matchingCardIds.push(
			CardIds.CrystalsmithCultist,
			CardIds.Darkbomb,
			CardIds.Darkbomb_WON_095,
			CardIds.SpiritGuide
		);
	}

	// SPELL (90 cards)
	if (refCard.type?.toUpperCase() === 'SPELL') {
		matchingCardIds.push(
			CardIds.AdvancedTargetingMonocle,
			CardIds.ArkoniteRevelation_GDB_852,
			CardIds.AudioSplitter,
			CardIds.BalindaStonehearth,
			CardIds.BarbaricSorceress,
			CardIds.BargainBin_MIS_105,
			CardIds.BenevolentBanker_WW_384,
			CardIds.BlindeyeSharpshooter_WW_402,
			CardIds.BookOfSpecters,
			CardIds.CactusCutter_WW_327,
			CardIds.ChaosSupplicant_CATA_786,
			CardIds.ChiaDrake_Cultivate_TOY_801a,
			CardIds.ChiaDrake_TOY_801,
			CardIds.ClearancePromoter_TOY_390,
			CardIds.ClericOfAnshe,
			CardIds.ClericOfScales,
			CardIds.ConchsCall,
			CardIds.ConjurationSpecialist_CATA_979,
			CardIds.ConjuredBookkeeper_TLC_226,
			CardIds.Cosmonaut_GDB_443,
			CardIds.DeckOfLunacy,
			CardIds.DeepwaterEvoker,
			CardIds.DoorOfShadows,
			CardIds.DoorOfShadows_DoorOfShadowsToken,
			CardIds.DragonsFury,
			CardIds.DryscaleDeputy_WW_383,
			CardIds.ElementalAllies,
			CardIds.EnergyShaper,
			CardIds.Fetch_TOY_352,
			CardIds.Flowrider,
			CardIds.GlowflySwarm,
			CardIds.GreenThumbGardener,
			CardIds.GuffRunetotem_BAR_720,
			CardIds.GuitarSoloist,
			CardIds.HarnessTheElementsTavernBrawl,
			CardIds.Hullbreaker,
			CardIds.IcebloodTower,
			CardIds.Illuminate,
			CardIds.IncantersFlow,
			CardIds.JotunTheEternal,
			CardIds.Kindle_DALA_911,
			CardIds.Kindle_ULDA_911,
			CardIds.KingPhaoris,
			CardIds.KnightOfAnointment,
			CardIds.LadyAnacondra_WC_006,
			CardIds.LadyVashj_VashjPrimeToken,
			CardIds.LifebindersGift,
			CardIds.LifebindersGrowth,
			CardIds.MagathaBaneOfMusic,
			CardIds.MagisterUnchainedTavernBrawlToken,
			CardIds.MalygosTheSpellweaverCore,
			CardIds.MalygosTheSpellweaver_LEG_CS3_034,
			CardIds.NightshadeBud,
			CardIds.NightshadeBud_CORE_REV_311,
			CardIds.PalmReading,
			CardIds.PortalmancerSkyla_WORK_063,
			CardIds.PowerWordFortitude,
			CardIds.PrimordialProtector_BAR_042,
			CardIds.Reforestation_AidOfTheForest_EDR_843a,
			CardIds.Reforestation_EDR_843,
			CardIds.Reforestation_ReforestationToken_EDR_843t1,
			CardIds.RefreshingSpringWater,
			CardIds.Rewind_ETC_532,
			CardIds.RimefangSwordCore,
			CardIds.RimefangSword_LEG_RLK_710,
			CardIds.RobesOfShrinkingTavernBrawl,
			CardIds.RuleModifier_SpreadOfCorruptionToken_TTN_002t45,
			CardIds.ScrollSavvy,
			CardIds.ShadowVisions,
			CardIds.SheldrasMoontree,
			CardIds.ShiveringSorceress,
			CardIds.SkulkingGeist_CORE_ICC_701,
			CardIds.SkulkingGeist_ICC_701,
			CardIds.SpitefulSummoner,
			CardIds.Starscryer,
			CardIds.Surfalopod_VAC_443,
			CardIds.Swindle,
			CardIds.TangledWrath,
			CardIds.TheStoneOfJordanTavernBrawlToken,
			CardIds.TheUpperHand,
			CardIds.ThriveInTheShadowsCore,
			CardIds.TimewayWanderer,
			CardIds.TortollanPilgrim,
			CardIds.Triangulate_GDB_451,
			CardIds.TrolleyProblem_WW_436,
			CardIds.UnderTheSea_VAC_431,
			CardIds.UngoroBrochure_DalaranBrochureToken_WORK_050t,
			CardIds.Ursol_EDR_259,
			CardIds.VoidFlayer,
			CardIds.VolumeUp
		);
	}

	// Return combined selector if any matches found
	if (matchingCardIds.length > 0) {
		return and(side(inputSide), or(inDeck, inHand), cardIs(...matchingCardIds));
	}
	return null;
};