export type CurrentAppType =
	| 'collection'
	| 'achievements'
	| 'decktracker'
	| 'replays'
	| 'battlegrounds'
	| 'mercenaries'
	| 'general'
	| 'duels'
	| 'arena'
	| 'tavern-brawl'
	| 'profile'
	| 'streams'
	| 'mailbox'
	| 'live';
