<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>FirestoneGameEventsHelper</AssemblyName>
    <RootNamespace>FirestoneGameEventsHelper</RootNamespace>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\HearthstoneReplays\HearthstoneReplays.Linux.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>
