import { CardIds, normalizeHeroCardId } from '@firestone-hs/reference-data';
import { CardsFacadeService } from '@firestone/shared/framework/core';

export const getBuddy = (heroCardId: CardIds, allCards: CardsFacadeService): CardIds | null => {
	switch (normalizeHeroCardId(heroCardId, allCards)) {
		case CardIds.AFKay_TB_BaconShop_HERO_16:
			return CardIds.SnackVendor_TB_BaconShop_HERO_16_Buddy;
		case CardIds.Alakir:
			return CardIds.SpiritOfAir_TB_BaconShop_HERO_76_Buddy;
		case CardIds.Alexstrasza_TB_BaconShop_HERO_56:
			return CardIds.Vaelastrasz_TB_BaconShop_HERO_56_Buddy;
		case CardIds.ArannaStarseeker_ArannaUnleashedToken:
		case CardIds.ArannaStarseeker_TB_BaconShop_HERO_59:
			return CardIds.SklibbDemonHunter_TB_BaconShop_HERO_59_Buddy;
		case CardIds.ArchVillainRafaam_TB_BaconShop_HERO_45:
			return CardIds.LoyalHenchman_TB_BaconShop_HERO_45_Buddy;
		case CardIds.Brukan_BG22_HERO_001:
			return CardIds.SpiritRaptor_BG22_HERO_001_Buddy;
		case CardIds.CaptainEudora_TB_BaconShop_HERO_64:
			return CardIds.DagwikStickytoe_TB_BaconShop_HERO_64_Buddy;
		case CardIds.CaptainHooktusk_TB_BaconShop_HERO_67:
			return CardIds.RagingContender_TB_BaconShop_HERO_67_Buddy;
		case CardIds.CarielRoame_BG21_HERO_000:
			return CardIds.CaptainFairmount_BG21_HERO_000_Buddy;
		case CardIds.Chenvaala_TB_BaconShop_HERO_78:
			return CardIds.SnowElemental_TB_BaconShop_HERO_78_Buddy;
		case CardIds.CookieTheCook_BG21_HERO_020:
			return CardIds.SousChef_BG21_HERO_020_Buddy;
		case CardIds.Cthun_TB_BaconShop_HERO_29:
			return CardIds.TentacleOfCthun_TB_BaconShop_HERO_29_Buddy;
		case CardIds.DancinDeryl:
			return CardIds.AsherTheHaberdasher_TB_BaconShop_HERO_36_Buddy;
		case CardIds.DeathSpeakerBlackthorn_BG20_HERO_103:
			return CardIds.DeathsHeadSage_BG20_HERO_103_Buddy;
		case CardIds.Deathwing_TB_BaconShop_HERO_52:
			return CardIds.LadySinestra_TB_BaconShop_HERO_52_Buddy;
		case CardIds.DinotamerBrann_TB_BaconShop_HERO_43:
			return CardIds.BrannsEpicEgg_TB_BaconShop_HERO_43_Buddy;
		case CardIds.Drekthar_BG22_HERO_002:
			return CardIds.FrostwolfLieutenant_BG22_HERO_002_Buddy;
		case CardIds.EdwinVancleef_TB_BaconShop_HERO_01:
			return CardIds.Si7Scout_TB_BaconShop_HERO_01_Buddy;
		case CardIds.EliseStarseeker_TB_BaconShop_HERO_42:
			return CardIds.JrNavigator_TB_BaconShop_HERO_42_Buddy;
		case CardIds.ForestWardenOmu_TB_BaconShop_HERO_74:
			return CardIds.EvergreenBotani_TB_BaconShop_HERO_74_Buddy;
		case CardIds.FungalmancerFlurgl:
			return CardIds.SparkfinSoothsayer_TB_BaconShop_HERO_55_Buddy;
		case CardIds.Galakrond:
			return CardIds.ApostleOfGalakrond_TB_BaconShop_HERO_02_Buddy;
		case CardIds.Galewing:
			return CardIds.FlightTrainer_BG20_HERO_283_Buddy;
		case CardIds.GeorgeTheFallen_TB_BaconShop_HERO_15:
			return CardIds.KarlTheLost_TB_BaconShop_HERO_15_Buddy;
		case CardIds.Greybough_TB_BaconShop_HERO_95:
			return CardIds.WanderingTreant_TB_BaconShop_HERO_95_Buddy;
		case CardIds.GuffRunetotem_BG20_HERO_242:
			return CardIds.BabyKodo_BG20_HERO_242_Buddy;
		case CardIds.IllidanStormrage_TB_BaconShop_HERO_08:
			return CardIds.EclipsionIllidari_TB_BaconShop_HERO_08_Buddy;
		case CardIds.InfiniteToki:
			return CardIds.ClockworkAssistant_TB_BaconShop_HERO_28_Buddy;
		case CardIds.JandiceBarov_TB_BaconShop_HERO_71:
			return CardIds.JandicesApprentice_TB_BaconShop_HERO_71_Buddy;
		case CardIds.KaelthasSunstrider_TB_BaconShop_HERO_60:
			return CardIds.CrimsonHandCenturion_TB_BaconShop_HERO_60_Buddy;
		case CardIds.KingMukla_TB_BaconShop_HERO_38:
			return CardIds.CrazyMonkey_TB_BaconShop_HERO_38_Buddy;
		case CardIds.KurtrusAshfallen_BG20_HERO_280:
			return CardIds.LivingNightmare_BG20_HERO_280_Buddy;
		case CardIds.LichBazhial:
			return CardIds.UnearthedUnderling_TB_BaconShop_HERO_25_Buddy;
		case CardIds.LordBarov_TB_BaconShop_HERO_72:
			return CardIds.BarovsApprentice_TB_BaconShop_HERO_72_Buddy;
		case CardIds.LordJaraxxus_TB_BaconShop_HERO_37:
			return CardIds.Kilrek_TB_BaconShop_HERO_37_Buddy;
		case CardIds.MaievShadowsong_TB_BaconShop_HERO_62:
			return CardIds.ShadowWarden_TB_BaconShop_HERO_62_Buddy;
		case CardIds.Malygos:
			return CardIds.NexusLord_TB_BaconShop_HERO_58_Buddy;
		case CardIds.MasterNguyen:
			return CardIds.LeiFlamepaw_BG20_HERO_202_Buddy;
		case CardIds.MillhouseManastorm_TB_BaconShop_HERO_49:
			return CardIds.MagnusManastorm_TB_BaconShop_HERO_49_Buddy;
		case CardIds.MillificentManastorm:
			return CardIds.ElementiumSquirrelBomb_TB_BaconShop_HERO_17_Buddy;
		case CardIds.MrBigglesworth_TB_BaconShop_HERO_70:
			return CardIds.LilKT_TB_BaconShop_HERO_70_Buddy;
		case CardIds.MutanusTheDevourer_BG20_HERO_301:
			return CardIds.NightmareEctoplasm_BG20_HERO_301_Buddy;
		case CardIds.Nozdormu_TB_BaconShop_HERO_57:
			return CardIds.Chromie_TB_BaconShop_HERO_57_Buddy;
		case CardIds.Nzoth:
			return CardIds.BabyNzoth_TB_BaconShop_HERO_93_Buddy;
		case CardIds.OverlordSaurfang_BG20_HERO_102:
			return CardIds.DranoshSaurfang_BG20_HERO_102_Buddy;
		case CardIds.PatchesThePirate_TB_BaconShop_HERO_18:
			return CardIds.TuskarrRaider_TB_BaconShop_HERO_18_Buddy;
		case CardIds.Patchwerk_TB_BaconShop_HERO_34:
			return CardIds.Weebomination_TB_BaconShop_HERO_34_Buddy;
		case CardIds.Pyramad:
			return CardIds.TitanicGuardian_TB_BaconShop_HERO_39_Buddy;
		case CardIds.QueenWagtoggle_TB_BaconShop_HERO_14:
			return CardIds.ElderTaggawag_TB_BaconShop_HERO_14_Buddy;
		case CardIds.RagnarosTheFirelord_TB_BaconShop_HERO_11:
			return CardIds.Lucifron_TB_BaconShop_HERO_11_Buddy;
		case CardIds.Rakanishu_TB_BaconShop_HERO_75:
			return CardIds.LanternTender_TB_BaconShop_HERO_75_Buddy;
		case CardIds.RenoJackson_TB_BaconShop_HERO_41:
			return CardIds.SrTombDiver_TB_BaconShop_HERO_41_Buddy;
		case CardIds.ScabbsCutterbutter_BG21_HERO_010:
			return CardIds.WardenThelwater_BG21_HERO_010_Buddy;
		case CardIds.Shudderwock_TB_BaconShop_HERO_23:
			return CardIds.Muckslinger_TB_BaconShop_HERO_23_Buddy;
		case CardIds.SilasDarkmoon_TB_BaconShop_HERO_90:
			return CardIds.Burth_TB_BaconShop_HERO_90_Buddy;
		case CardIds.Sindragosa_TB_BaconShop_HERO_27:
			return CardIds.ThawedChampion_TB_BaconShop_HERO_27_Buddy;
		case CardIds.SirFinleyMrrgglton_TB_BaconShop_HERO_40:
			return CardIds.MaxwellMightySteed_TB_BaconShop_HERO_40_Buddy;
		case CardIds.SkycapnKragg_TB_BaconShop_HERO_68:
			return CardIds.Sharkbait_TB_BaconShop_HERO_68_Buddy;
		case CardIds.Sneed_BG21_HERO_030:
			return CardIds.PilotedWhirlOTron_BG21_HERO_030_Buddy;
		case CardIds.TamsinRoame_BG20_HERO_282:
			return CardIds.Monstrosity_BG20_HERO_282_Buddy;
		case CardIds.TavishStormpike_BG22_HERO_000:
			return CardIds.Crabby_BG22_HERO_000_Buddy;
		case CardIds.TessGreymane_TB_BaconShop_HERO_50:
			return CardIds.HunterOfOld_TB_BaconShop_HERO_50_Buddy;
		case CardIds.TheCurator_TB_BaconShop_HERO_33:
			return CardIds.Mishmash_TB_BaconShop_HERO_33_Buddy;
		case CardIds.TheGreatAkazamzarak:
			return CardIds.StreetMagician_TB_BaconShop_HERO_21_Buddy;
		case CardIds.TheLichKing_TB_BaconShop_HERO_22:
			return CardIds.Arfus_TB_BaconShop_HERO_22_Buddy;
		case CardIds.TheRatKing_TB_BaconShop_HERO_12:
			return CardIds.PigeonLord_TB_BaconShop_HERO_12_Buddy;
		case CardIds.Tickatus_TB_BaconShop_HERO_94:
			return CardIds.TicketCollector_TB_BaconShop_HERO_94_Buddy;
		case CardIds.TradePrinceGallywix_TB_BaconShop_HERO_10:
			return CardIds.BilgewaterMogul_TB_BaconShop_HERO_10_Buddy;
		case CardIds.VanndarStormpike_BG22_HERO_003:
			return CardIds.StormpikeLieutenant_BG22_HERO_003_Buddy;
		case CardIds.Voljin_BG20_HERO_201:
			return CardIds.MasterGadrin_BG20_HERO_201_Buddy;
		case CardIds.Xyrella_BG20_HERO_101:
			return CardIds.BabyElekk_BG20_HERO_101_Buddy;
		case CardIds.YoggSaronHopesEnd_TB_BaconShop_HERO_35:
			return CardIds.AcolyteOfYoggSaron_TB_BaconShop_HERO_35_Buddy;
		case CardIds.Ysera_TB_BaconShop_HERO_53:
			return CardIds.ValithriaDreamwalker_TB_BaconShop_HERO_53_Buddy;
		case CardIds.Yshaarj:
			return CardIds.BabyYshaarj_TB_BaconShop_HERO_92_Buddy;
		case CardIds.ZephrysTheGreat_TB_BaconShop_HERO_91:
			return CardIds.Phyresz_TB_BaconShop_HERO_91_Buddy;
		case CardIds.VardenDawngrasp_BG22_HERO_004:
			return CardIds.VardensAquarrior_BG22_HERO_004_Buddy;
		case CardIds.Rokara_BG20_HERO_100:
			return CardIds.IcesnarlTheMighty_BG20_HERO_100_Buddy;
		case CardIds.Onyxia_BG22_HERO_305:
			return CardIds.ManyWhelps_BG22_HERO_305_Buddy;
		case CardIds.AmbassadorFaelin_BG22_HERO_201:
			return CardIds.SubmersibleChef_BG22_HERO_201_Buddy;
		case CardIds.IniStormcoil_BG22_HERO_200:
			return CardIds.SubScrubber_BG22_HERO_200_Buddy;
		case CardIds.QueenAzshara_BG22_HERO_007:
			return CardIds.ImperialDefender_BG22_HERO_007_Buddy;
		case CardIds.Ozumat_BG23_HERO_201:
			return CardIds.Tamuzo_BG23_HERO_201_Buddy;
		case CardIds.LadyVashj_BG23_HERO_304:
			return CardIds.CoilfangElite_BG23_HERO_304_Buddy;
		case CardIds.HeistbaronTogwaggle_BG23_HERO_305:
			return CardIds.WaxadredTheDrippy_BG23_HERO_305_Buddy;
		case CardIds.SireDenathrius_BG24_HERO_100:
			return CardIds.ShadyAristocrat_BG24_HERO_100_Buddy;
		case CardIds.SylvanasWindrunner_BG23_HERO_306:
			return CardIds.NathanosBlightcaller_BG23_HERO_306_Buddy;
		case CardIds.TheJailer_TB_BaconShop_HERO_702:
			return CardIds.MawswornSoulkeeper_TB_BaconShop_HERO_702_Buddy;
		case CardIds.EnhanceOMechano_BG24_HERO_204:
			return CardIds.EnhanceOMedico_BG24_HERO_204_Buddy;
		case CardIds.ProfessorPutricide_BG25_HERO_100:
			return CardIds.Festergut_BG25_HERO_100_Buddy;
		case CardIds.TeronGorefiend_BG25_HERO_103:
			return CardIds.ShadowyConstruct_BG25_HERO_103_Buddy;
		case CardIds.MurlocHolmes_BG23_HERO_303:
			return CardIds.Watfin_BG23_HERO_303_Buddy;
		case CardIds.ETCBandManager_BG25_HERO_105:
			return CardIds.TalentScout_BG25_HERO_105_Buddy;
		case CardIds.CapnHoggarr_BG26_HERO_101:
			return CardIds.ShiningSailor_BG26_HERO_101_Buddy;
		case CardIds.IngeTheIronHymn:
			return CardIds.SolemnSerenader_BG26_HERO_102_Buddy;
		case CardIds.RockMasterVoone_BG26_HERO_104:
			return CardIds.AkaliRockRhino_BG26_HERO_104_Buddy;
		case CardIds.ThorimStormlord_BG27_HERO_801:
			return CardIds.VeranusStormlordsMount_BG27_HERO_801_Buddy;
		case CardIds.SnakeEyes_BG28_HERO_400:
			return CardIds.BoxCars_BG28_HERO_400_Buddy;
		case CardIds.DoctorHollidae_BG28_HERO_801:
			return CardIds.TheNineFrogs_BG28_HERO_801_Buddy;
		case CardIds.TaethelanBloodwatcher_BG28_HERO_800:
			return CardIds.ReliquaryAttendant_BG28_HERO_800_Buddy;
		case CardIds.TheNamelessOne_BGDUO_HERO_100:
			return CardIds.FacelessOne_BGDUO_HERO_100_Buddy;
		case CardIds.Cho_BGDUO_HERO_222:
			return CardIds.HalfusTheMighty_BGDUO_HERO_222_Buddy;
		case CardIds.Gall_BGDUO_HERO_223:
			return CardIds.HalfusTheWise_BGDUO_HERO_223_Buddy;
		case CardIds.MadamGoya_BGDUO_HERO_104:
			return CardIds.MisterChu_BGDUO_HERO_104_Buddy;
		case CardIds.FlobbidinousFloop_BGDUO_HERO_101:
			return CardIds.GloriousGloopling_BGDUO_HERO_101_Buddy;
		default:
			if (!!heroCardId) {
				console.error('missing buddy section for ', heroCardId);
			}
			return null;
	}
};
