<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>HearthstoneReplays</AssemblyName>
    <RootNamespace>HearthstoneReplays</RootNamespace>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0618;SYSLIB0011;CS0168;CS0219;CA1416</NoWarn>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**/*.cs" Exclude="obj/**;bin/**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="DeepCloner" Version="0.10.4" />
  </ItemGroup>
</Project>
