export declare const enum TempCardIds {
	Cremate = 'Cremate',
	FrostburnMatriarch = 'FrostburnMatriarch',
	ScorchingWinds = 'ScorchingWinds',
	InfernoHerald = 'InfernoHerald',
	LivingFlame = 'LivingFlame',
	Overheat = 'Overheat',
	PetalPicked = 'PetalPicked',
	CharredChameleon = 'CharredChameleon',
	TendingDragonkin = 'TendingDragonkin',
	SmokeBomb = 'SmokeBomb',
	Cindersword = 'Cindersword',
	SmolderingStrength = 'SmolderingStrength',
	SearingReflection = 'SearingReflection',
	AshleafPixie = 'AshleafPixie',
	FelfireBlaze = 'FelfireBlaze',
	Scorchreaver = 'Scorchreaver',
	FlamesOfTheFirelord = 'FlamesOfTheFirelord',
	EmberscarredWhelp = 'EmberscarredWhelp',
	KeeperOfFlame = 'KeeperOfFlame',
	ShadowflameSuffusion = 'ShadowflameSuffusion',
	DragonTurtle = 'DragonTurtle',
	LightOfTheNewMoon = 'LightOfTheNewMoon',
	ShadowflameStalker = 'ShadowflameStalker',
}
