export declare const enum TempCardIds {
	Finality = 'Finality',
	BrutishEndmaw = 'BrutishEndmaw',
	TrienniumRex = 'TrienniumRex',
	DimensionalWeaponsmith = 'DimensionalWeaponsmith',
	EternalToil = 'EternalToil',
	FlamesOfInfinity = 'FlamesOfInfinity',
	EternalFireboltEnchantment = 'EternalFireboltEnchantment',
	FragmentOfNothing = 'FragmentOfNothing',
	VoodooTotem = 'VoodooTotem',
	HaywireHornswog = 'HaywireHornswog',
	Morchie = 'Morchie',
	BlessingOfTheBronze = 'BlessingOfTheBronze',
	WingsOfEternity = 'WingsOfEternity',
	SplinteredReality = 'SplinteredReality',
	Chronikar_Enchantment = 'Chronikar_Enchantment',
	RemnantOfRage = 'RemnantOfRage',
	BygoneEchoes = 'BygoneEchoes',
	WickedBlightspawn = 'WickedBlightspawn',
	BlessingOfTheInfinite = 'BlessingOfTheInfinite',
	PrescientSlitherdrake = 'PrescientSlitherdrake',
}
