<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>HackF5.UnitySpy.HearthstoneLib</AssemblyName>
    <RootNamespace>HackF5.UnitySpy.HearthstoneLib</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);CS0618;CA1416;SYSLIB0011</NoWarn>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup><Compile Include="**/*.cs" Exclude="obj/**;bin/**" /></ItemGroup>
  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2023.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <ProjectReference Include="..\UnitySpy\UnitySpy.Linux.csproj" />
  </ItemGroup>
</Project>
